src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Possible_Fraud__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Possible Fraud?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store (only for VW)</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/objects/Bad_Customer__c.object
<CustomObject>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to determine if this is an active bad record.</description>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Bad Customer</label>
    <nameField>
        <displayFormat>BC-{00000}</displayFormat>
        <label>Bad Customer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bad Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Status_Detail__c.object
<CustomObject>
    <description>Child object of Order Line Items, contains status updates from AS400</description>
    <fields>
        <fullName>Current_Sku__c</fullName>
        <label>Current Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Status_Code__c</fullName>
        <description>2 Digit AS400 status code</description>
        <inlineHelpText>2 Digit AS400 status code</inlineHelpText>
        <label>Current Status Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status_Code__c</fullName>
        <label>Order Status Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Item Status Details</relationshipLabel>
        <relationshipName>Order_Line_Item_Status_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item Status Detail</label>
    <nameField>
        <displayFormat>0{0000000000}</displayFormat>
        <label>Status Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item Status Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>AS400_Cancellation_Details__c</fullName>
        <label>AS400 Cancellation Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Archive_Summary__c</fullName>
        <label>Archive Summary</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled_Reason__c</fullName>
        <inlineHelpText>Why is the Order Status set to &quot;Cancelled&quot;?</inlineHelpText>
        <label>Cancelled Reason</label>
        <picklist>
            <controllingField>Order_Status__c</controllingField>
            <picklistValues>
                <fullName>Orphan Order Clean-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Order Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS400 Error Exception Clean Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Credit Card Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Review_Reason__c</fullName>
        <inlineHelpText>Why is the Order Status set to &quot;Internal Review&quot;?</inlineHelpText>
        <label>Internal Review Reason</label>
        <picklist>
            <controllingField>Order_Status__c</controllingField>
            <picklistValues>
                <fullName>Manually Added by Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Over $5,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over 100 of a Single Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ship Complete was checked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Status_Code__c</fullName>
        <description>Stores AS400 order status code (PB,PA,SA, etc.)</description>
        <label>Order Status Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_Fraud__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Potential Fraud?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Bad_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Bad Address</label>
        <referenceTo>Bad_Customer__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Bad_Email__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Bad Email</label>
        <referenceTo>Bad_Customer__c</referenceTo>
        <relationshipLabel>Orders (Related Bad Email)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Order_ID__c</fullName>
        <formula>IF(ISBLANK(Webstack_Order_ID__c), Name, Webstack_Order_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Web Order ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_ID__c</fullName>
        <label>Webstack ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WebStoresData__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Is_Editable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Editable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <description>The sales channel to be displayed. Such as Amazon JP, Brand Website, etc.</description>
        <label>Sales Channel</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Web Stores Data</label>
</CustomObject>

src/classes/Order_DetailsExtension.cls
public with sharing class Order_DetailsExtension {

	public boolean showInternalReviewBtn {get;set;}
	public boolean showCancelOrderBtn {get;set;}
	public boolean showEditBtn {get;set;} 
	public boolean showCloneBtn {get;set;}
	public boolean showAdminCancelBtn {get;set;}
	public boolean showBackOfficeEdit {get;set;}
	public boolean showReleaseOrder {get;set;}
	public boolean cancelSuccessful;
	public Boolean showFraudRelease {get;set;}
	public string OrderId {get;set;}
	public Orders__c orderSObj {get;set;}
	public string selectedCancelReason {get;set;}
	public List<SelectOption> cancelReasonList {get;set;}
	public string selectedReviewReason {get;set;}
	public List<SelectOption> reviewReasonList {get;set;}
	public boolean showCancelOrderPanel {get;set;}
	public boolean showInternalReviewPanel {get;set;}
	public boolean showAdminCancelSave {get;set;}
	public boolean showPreWareHouseCancel {get;set;}
	public boolean showPostWareHouseCancel {get;set;}
	public boolean showBackOrderCancel {get;set;}
	public OrderStatusQueryController statusQueryController {get;set;}
	private ApexPages.StandardController orderdetailController;
	
	private list<Order_Line_Item_Status_Detail__c> lststatus = new list<Order_Line_Item_Status_Detail__c>();

	
	public Order_DetailsExtension(ApexPages.StandardController stdController) {
		OrderId = stdController.getId();
		orderdetailController = stdController;
		statusQueryController = new OrderStatusQueryController(OrderId);
		orderSObj = (Orders__c) stdController.getRecord();
		orderSObj = [Select Id, Archived__c, Archive_summary__c, Potential_Fraud__c, Related_Bad_Address__c, Related_Bad_Email__c, OwnerId, name, Sales_Channel__c, 
						Order_Submitted__c, Order_Status__c, Order_Status_Code__c, Internal_Review_Reason__c, AS400_Cancellation_Details__c,Web_Order_ID__c, CreatedById, Customer__c, 
						Webstack_Id__c from Orders__c where id=:orderSObj.id];
		// DE880 -- incorporating the custom setting for editability.
		if (!String.IsBlank(orderSObj.Webstack_Id__c) && !WebStoresData__c.getValues(orderSObj.Webstack_Id__c).Is_Editable__c) { //orderSObj.Sales_Channel__c=='Amazon'){
		 	String sSalesChannel = WebStoresData__c.getValues(orderSObj.Webstack_Id__c).Sales_Channel__c;
		 	if (!String.IsBlank(sSalesChannel)){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, sSalesChannel + ' orders may not be edited.'));
		 	} else {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Orders from this Sales Channel may not be edited.'));
		 	}
    	 }
    	 else if (orderSobj.order_submitted__c){
    	 	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Submitted Orders cannot be edited.'));
    	 }
		string OrderId = ApexPages.currentPage().getParameters().get('Id');
		
		list<Order_Line_Item_Status_Detail__c> lststatustemp = new list<Order_Line_Item_Status_Detail__c>();
		lststatustemp = [Select Order_Status__c, Order_Status_Code__c, Current_Status_Code__c, Current_Sku__c, CreatedDate From Order_Line_Item_Status_Detail__c where Order__c =:OrderId Order by CreatedDate Desc];
		if (lststatustemp.size() > 0) {
			datetime crDate = lststatustemp[0].CreatedDate;	
			for (Order_Line_Item_Status_Detail__c templst :lststatustemp) {
				system.debug('~~~ Create DateTime:' + templst.CreatedDate);
				if (templst.CreatedDate < crDate) // Order status duplicate Scenerio.. get last run status
	 				break;
				lststatus.add(templst);
			}
		}
		resetBtns();
		cancelReasonList = new List <SelectOption>();
		cancelReasonList.add(new SelectOption ('None', '--- Select Reason ---'));
		for (Schema.PicklistEntry p : Schema.SObjectType.Orders__c.fields.getMap().get('Cancelled_Reason__c').getDescribe().getPicklistValues()) {
			cancelReasonList.add(new SelectOption(p.getLabel(), p.getValue()));
		}
		
		reviewReasonList = new List <SelectOption>();
		reviewReasonList.add(new SelectOption ('None', '--- Select Reason ---'));
		for (Schema.PicklistEntry p : Schema.SObjectType.Orders__c.fields.getMap().get('Internal_Review_Reason__c').getDescribe().getPicklistValues()) {
			reviewReasonList.add(new SelectOption(p.getLabel(), p.getValue()));
		}
		if (orderSObj.Potential_Fraud__c && checkUserProfile()) {
			showFraudRelease = true;
		} else {
			showFraudRelease = false;
		}
	}
	
	public void resetBtns() {
		showInternalReviewPanel = false;
		showCancelOrderPanel=false;
		boolean showCancel = orderUtilities.statusSetToCancel(OrderId);
		showCancelOrderBtn = showCancel; // Non submitted orders
		showPreWareHouseCancel = showCancel?false:OrderUtilities.statusSetToPreWareHouseCancel(lststatus);
		showPostWareHouseCancel = showCancel?false:OrderUtilities.statusSetToPostWareHouseCancel(lststatus);
		showBackOrderCancel = showCancel?false:OrderUtilities.statusSetToBackOrderCancel(lststatus);
		showInternalReviewBtn = orderUtilities.statusSetToInternalReview(OrderId); 
		if (orderSobj.Order_Status_Code__c == 'BO' || orderSobj.Order_Status_Code__c == 'ER') {
			showEditBtn = false;
			showCloneBtn = false;
		} else {
			showEditBtn = true;
			showCloneBtn = true;
		}
		showAdminCancelBtn = orderUtilities.checkProfile('System Administrator')||orderUtilities.checkProfile('Back-Office Team');
		showBackOfficeEdit = orderSobj.Order_Status__c!='Pending Submission' && (orderUtilities.checkProfile('System Administrator') || orderUtilities.checkProfile('Back-Office Team')); 
		if ((orderUtilities.checkProfile('System Administrator') || orderUtilities.checkProfile('Back-Office Team')) && !orderSobj.Order_Submitted__c && orderSobj.Order_Status__c == 'Internal Review') {
			showReleaseOrder = true;
		} else {
			showReleaseOrder = false;
		}
	}
	
	//reset Custom Actions Panel
	public void processCancel(){
		resetBtns();
		selectedReviewReason = 'None';
		selectedCancelReason = 'None';
	}
	
	public void processInternalReviewBtn(){
		showInternalReviewPanel = true;
		hideButtons();
	}
	
	public void processOrderCancelBtn_Admin(){
		processOrderCancelBtn();
		showAdminCancelSave=true;
	}
	
	public void processOrderPrewarehouseCancel(){
		boolean retCode = CancelOrderbyProgId('1');
	}
	
	public void processOrderPOSTwarehouseCancel(){
		boolean retCode = CancelOrderbyProgId('3');
	}
	
	public void processOrderBackOrderCancel(){
		boolean retCode = CancelOrderbyProgId('2');
	}
	
	public void processOrderCancelBtn(){
		showCancelOrderPanel = true;
		hideButtons();
	}
	
	public static Boolean checkUserProfile() {
		Id userId = UserInfo.getProfileId();
		String pName = [SELECT Name FROM Profile WHERE Id = :userId].Name;
		if (pName == 'System Administrator' || pName == 'Back-Office Team') {
			return true;
		} else {
			return false;
		}
	}
	
	public pageReference processBackOfficeEdit() {
		PageReference pageRef = new PageReference( '/'+OrderId + '/e?retURL=%2F' + OrderId+ '&override=1');
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	public pageReference processReleaseOrder() {
		orderSObj.Order_Status__c='Pending Submission';
		update orderSObj;
		PageReference pageRef = new PageReference( '/'+OrderId );
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	public pageReference releasePotentialFraud() {
		Set<Id> bcSet = new Set<Id>{orderSObj.Related_Bad_Address__c, orderSObj.Related_Bad_Email__c};
		List<Bad_Customer__c> bdCustList = [SELECT Id, isActive__c FROM Bad_Customer__c WHERE Id IN :bcSet];
		for (Bad_Customer__c bc : bdCustList) {
			bc.isActive__c = false;
		}
		update bdCustList;
		orderSObj.Order_Status__c='Pending Submission';
		orderSObj.Potential_Fraud__c = false;
		orderSObj.Related_Bad_Address__c = null;
		orderSObj.Related_Bad_Email__c = null;
		orderSObj.OwnerId = orderSObj.CreatedById;
		update orderSObj;
		Account acct = [SELECT Id, Possible_Fraud__c FROM Account WHERE Id = :orderSObj.Customer__c];
		acct.Possible_Fraud__c = false;
		update acct;
		PageReference pageRef = new PageReference( '/'+OrderId );
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	public void hideButtons() {
		showEditBtn = false;
		showCloneBtn = false;
		showInternalReviewBtn = false;
		showCancelOrderBtn = false;
		showAdminCancelBtn = false;
		showBackOfficeEdit = false;
		showReleaseOrder = false;
	}
	
	public void saveCancelOrder() {
		if(selectedCancelReason == 'None') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please enter a order cancellation reason'));
		} else {
			resetBtns();
			cancelSuccessful=OrderUtilities.processOrderCancel(OrderId,selectedCancelReason);
		}
	}
	
	public void saveCancelOrder_Admin() {
		saveCancelOrder();
		if (!cancelSuccessful) {
			OrderUtilities.forceCancel(OrderId, selectedCancelReason);
		}
	}
	
	private boolean CancelOrderbyProgId(string ProgramId) {
		if(selectedCancelReason == 'None') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please enter a order cancellation reason'));
		}
		boolean retCode = false;
		try{
			WS_OrderLineItemCancellation.CancelOrderPort wsCancelOrder = new WS_OrderLineItemCancellation.CancelOrderPort();
			WS_OrderLineItemCancellation.OrderCancellationResponse_element cancelResponse = new WS_OrderLineItemCancellation.OrderCancellationResponse_element();
			system.debug('~~~~~~~~~~~~~~~ Entered here');
			string SFDCOrderNumber = string.isNotBlank(orderSObj.Web_Order_ID__c) ? orderSObj.Web_Order_ID__c : orderSObj.Name ;
			SFDCOrderNumber = orderutilities.zeroLPAD(SFDCOrderNumber, 10);
			cancelResponse = wsCancelOrder.CancelOrder(SFDCOrderNumber, SFDCOrderNumber, ProgramId, '', '', '', '' , selectedCancelReason,'' , '');
			//process response
			if (cancelResponse.Status != 'Success') {
				retCode = false;
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error Cancelling order: ' + cancelResponse.StatusCode + '-'+ cancelResponse.StatusMessage ));
			} else {
				retCode = true;
			}
		} catch(exception e) {
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error invoking cancellation web service'));
			system.debug('--------Error invoking cancellation Web Service' + e.getmessage());
			
		}
		return retcode;
	}
	
	
	public void saveInternalReview(){
		if (selectedReviewReason == 'None') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please enter a internal review reason'));
		} else {
			resetBtns();
			OrderUtilities.processInternalReview(OrderId, selectedReviewReason);
		}
	}
}