src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AS_400_Customer_Number__c</fullName>
        <externalId>true</externalId>
        <label>AS/400 Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store (only for VW)</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>VW_Passport_Number__c</fullName>
        <label>VW Passport Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>First Line of Address</description>
        <inlineHelpText>First Line of the Address for the Customer&apos;s Address</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the Customer&apos;s address</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_4__c</fullName>
        <label>Address Line 4</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UNITED STATES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASCENSION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BONAIRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Foreign_Postal_Code__c</fullName>
        <label>Foreign Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Providence__c</fullName>
        <description>State or Province for the Customer&apos;s Address</description>
        <inlineHelpText>State or Province for the Customer&apos;s Address</inlineHelpText>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Status_Detail__c.object
<CustomObject>
    <description>Child object of Order Line Items, contains status updates from AS400</description>
    <fields>
        <fullName>Order_Status_Code__c</fullName>
        <label>Order Status Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status_Description__c</fullName>
        <label>Order Status Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item Status Detail</label>
    <nameField>
        <displayFormat>0{0000000000}</displayFormat>
        <label>Status Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item Status Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>AS400_Cancellation_Details__c</fullName>
        <label>AS400 Cancellation Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Archive_Summary__c</fullName>
        <label>Archive Summary</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders (Bill To Address)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cancelled_Reason__c</fullName>
        <inlineHelpText>Why is the Order Status set to &quot;Cancelled&quot;?</inlineHelpText>
        <label>Cancelled Reason</label>
        <picklist>
            <controllingField>Order_Status__c</controllingField>
            <picklistValues>
                <fullName>Orphan Order Clean-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Order Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS400 Error Exception Clean Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Credit Card Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Review_Reason__c</fullName>
        <inlineHelpText>Why is the Order Status set to &quot;Internal Review&quot;?</inlineHelpText>
        <label>Internal Review Reason</label>
        <picklist>
            <controllingField>Order_Status__c</controllingField>
            <picklistValues>
                <fullName>Manually Added by Associate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order Over $5,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over 100 of a Single Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ship Complete was checked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Status_Update__c</fullName>
        <label>Last Status Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Status_Code__c</fullName>
        <description>Stores AS400 order status code (PB,PA,SA, etc.)</description>
        <label>Order Status Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status_Description__c</fullName>
        <description>Long description of order status</description>
        <label>Order Status Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signals if the order is a valid duplicate.</description>
        <label>Valid Duplicate?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Web_Order_ID__c</fullName>
        <formula>IF(ISBLANK(Webstack_Order_ID__c), Name, Webstack_Order_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Web Order ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_ID__c</fullName>
        <label>Webstack ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_Order_ID__c</fullName>
        <label>Webstack Order ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderStatusQueryController.cls
/*
	OrderStatusQueryController
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey |	10/14/13	|	Created

*/

public class OrderStatusQueryController {
	
	private static final String BO = 'BO';
	private static final String ER = 'ER';
	private static final String VW = 'Vitamin_World_Customer';
	private static final String CNTY = 'UNITED STATES';
	public Orders__c ord {get;set;}
	public Order_Line_Item_Status_Detail__c olisd {get;set;}
	public List<Order_Line_Item_Status_Detail__c> ordStatusDetails {get;set;}
	public List<SelectOption> cancelReasonList {get;set;}
	public List<SelectOption> DispositionList {get;set;}
	public List<SelectOption> clearOptions {get;set;}
	public Boolean showResults {get;set;}
	public Boolean showError {get;set;}
	public Boolean showSnippet {get;set;}
	public Boolean noCallout {get;set;}
	public Boolean isStart {get;set;}
	public Boolean showAdminCancelSave {get;set;}
	public Boolean showPreWareHouseCancel {get;set;}
	public Boolean showPostWareHouseCancel {get;set;}
	public Boolean showBackOrderCancel {get;set;}
	public Boolean showCancelOrderBtn {get;set;}
	public Boolean showCancelOrderPanel {get;set;}
	public Boolean showCancelOrderDisposition {get;set;}
	public Boolean showTable {get;set;}
	public Boolean showClearButton {get;set;}
	public Boolean showClearCancel {get;set;}
	public Boolean cancelCloneNewTab {get;set;}
	public String selectedDisposition {get;set;}
	public String selectedCancelReason {get;set;}
	public String selectedClearOption {get;set;}
	public String newTabStr {get;set;}
	public String redirectStr {get;set;}
	public String trackingStr {get;set;}
	public OSQResponse rawResponse {get;set;}
	public faultWrapper fault {get;set;}
	private String status {get;set;}
	private String orderId {get;set;}
	private WS_OrderStatusQuery.OrderStatusQueryResponse_element response_Element {get;set;}
	private String ProgramID = '';
	private Boolean isDupe;
	
	public OrderStatusQueryController(ApexPages.StandardController controller) {
		orderId = controller.getId();
		system.debug('-------------------------------------OrderId: ' + orderId);
		ord = [SELECT Id, Last_Status_Update__c,Archived__c, Archive_summary__c, name, Sales_Channel__c, Order_Submitted__c, Order_Status__c, 
				Internal_Review_Reason__c, AS400_Cancellation_Details__c, Web_Order_ID__c, Webstack_Order_ID__c, Webstack_ID__c, Customer__r.RecordType.DeveloperName, Customer__r.VW_Passport_Number__c, 
				Customer__r.AS_400_Customer_Number__c, Bill_To_Address__r.Address_Line_1__c, Bill_To_Address__r.Address_Line_2__c, Bill_To_Address__r.Address_Line_3__c, 
				Bill_To_Address__r.Address_Line_4__c, Bill_To_Address__r.Country_Picklist__c, Bill_To_Address__r.State_Providence__c, Bill_To_Address__r.Country__c, 
				Bill_To_Address__r.City__c, Bill_To_Address__r.Foreign_Postal_Code__c, Bill_To_Address__r.Zip_Code__c, Valid_Duplicate__c FROM Orders__c WHERE Id = :orderId];
		showResults = false;
		showError = false;
		isStart=true;
		showTable = true;
		showClearButton = false;
		cancelCloneNewTab = false;
		//isDupe = false;
		setNewTabString();
	}
	
	public OrderStatusQueryController(Id OrdId) {
		orderId =ordId;
		system.debug('-------------------------------------OrderId: ' + orderId);
		ord = [SELECT Id, Last_Status_Update__c,Archived__c, Archive_summary__c, name, Sales_Channel__c, Order_Submitted__c, Order_Status__c, 
				Internal_Review_Reason__c, AS400_Cancellation_Details__c, Web_Order_ID__c, Webstack_Order_ID__c, Webstack_ID__c, Customer__r.RecordType.DeveloperName, Customer__r.VW_Passport_Number__c, 
				Customer__r.AS_400_Customer_Number__c, Bill_To_Address__r.Address_Line_1__c, Bill_To_Address__r.Address_Line_2__c, Bill_To_Address__r.Address_Line_3__c, 
				Bill_To_Address__r.Address_Line_4__c, Bill_To_Address__r.Country_Picklist__c, Bill_To_Address__r.State_Providence__c, Bill_To_Address__r.Country__c, 
				Bill_To_Address__r.City__c, Bill_To_Address__r.Foreign_Postal_Code__c, Bill_To_Address__r.Zip_Code__c, Valid_Duplicate__c FROM Orders__c WHERE Id = :orderId];
		
		cancelReasonList = new List <SelectOption>();
		cancelReasonList.add(new SelectOption ('None', '--- Select Reason ---'));
		for (Schema.PicklistEntry p : Schema.SObjectType.Orders__c.fields.getMap().get('Cancelled_Reason__c').getDescribe().getPicklistValues()) {
			cancelReasonList.add(new SelectOption(p.getLabel(), p.getValue()));
		}
		
		showSnippet = (ord.Order_Submitted__c /*&& ord.Order_Status__c != 'Shipped/Complete'*/) ? true :false;
		showResults = false;
		showError = false;
		isStart=true;
		showTable = true;
		showClearButton = false;
		showClearCancel = false;
		cancelCloneNewTab = false;
		//isDupe = false;
		setNewTabString();
	}
	
	public void init() {
		isStart=false;
		if (showSnippet) {
			response_Element = new WS_OrderStatusQuery.OrderStatusQueryResponse_element();
			response_Element = WS_OrderStatusQueryUtils.doCallout(orderId);
			
			clearOptions = new List<SelectOption>();
			clearOptions.add(new SelectOption ('None', '--- Select Option ---'));
			clearOptions.add(new SelectOption ('Resubmit', 'Resubmit'));
			clearOptions.add(new SelectOption ('Cancel', 'Cancel'));
			if (ord.Webstack_ID__c != '18' && ord.Webstack_ID__c != '45' && ord.Webstack_ID__c != '47') {
				clearOptions.add(new SelectOption ('CancelClone', 'Cancel & Clone'));
			}
			if (ord.Customer__r.RecordType.DeveloperName == VW) {
				clearOptions.add(new SelectOption ('BadBill', 'Update Billing Info & Resubmit'));
			}
			
			if (response_Element.OrderStatusSuccess != null) {
				buildWrapper(response_Element.OrderStatusSuccess);
				system.debug('---------------------------------------------------------Success');
				ordStatusDetails = WS_OrderStatusQueryUtils.processSuccess(response_Element.OrderStatusSuccess);
				if (ordStatusDetails != null) {
					Set<String> olisdIds = new Set<String>();
					for (Order_Line_Item_Status_Detail__c a : ordStatusDetails) {
						olisdIds.add(a.Id);
						if ((a.Order_Status_Code__c == BO || a.Order_Status_Code__c == ER) && checkUserProfile()) {
							showClearButton = true;
						}
						if (a.Order_Status_Description__c == 'DUPLICATE CUSTOMER ORDER') {
							isDupe = true;
						} else {
							isDupe = false;
						}
					}
					OrderStatusQueryUtils.processUpdates(olisdIds);
					olisd = ordStatusDetails[0];
					if (ordStatusDetails.size() < 2 && ordStatusDetails[0].Order_Line_Item__c == null) {
						showTable = false;
					}
					showResults = true;
					showError = false;
					//setPageMessages('SUCCESS!');
					/*****************Code moved here**************************
					cancelReasonList = new List <SelectOption>();
					cancelReasonList.add(new SelectOption ('None', '--- Select Reason ---'));
					for (Schema.PicklistEntry p : Schema.SObjectType.Orders__c.fields.getMap().get('Cancelled_Reason__c').getDescribe().getPicklistValues())
					{
						cancelReasonList.add(new SelectOption(p.getLabel(), p.getValue()));
					}
					***************************END**************************/
					ShowCancelOrderButtons();
					
				} else {
					showResults = false;
					showError = false;
					setPageMessages('Status Updates Not Available.');
				}
				
			} else if (response_Element.OrderStatusFault != null) {
				system.debug('---------------------------------------------------------Failure');
				showError = true;
				showResults = false;
				WS_OrderStatusQuery.OrderStatusSuccess oss = new WS_OrderStatusQuery.OrderStatusSuccess();
				oss.OrderStatus = response_Element.OrderStatusFault.FaultCode;
				oss.OrderStatusDetail = response_Element.OrderStatusFault.FaultMessage;
				oss.SFOrderNumber = ord.Name;
				List<WS_OrderStatusQuery.LineItem> aList = null;
				WS_OrderStatusQuery.LineItemList lineItemList = new WS_OrderStatusQuery.LineItemList();
				lineItemList.LineItem = aList;
				oss.LineItemList = lineItemList;
				List<Order_Line_Item_Status_Detail__c> xp = WS_OrderStatusQueryUtils.processSuccess(oss);
				system.debug('---------------------------------------------------------xp: ' + xp);
				if (xp != null) {
					Set<String> olisdIds = new Set<String>();
					for(Order_Line_Item_Status_Detail__c a : xp){
						olisdIds.add(a.Id);
					}
					OrderStatusQueryUtils.processUpdates(olisdIds);
				}
				fault = new faultWrapper(response_Element.OrderStatusFault);
				system.debug('---------------------------------------------------------fault: ' + fault);
			}
		} else {// Order not submiited
			showCancelOrderBtn = ord.order_status__C != 'Cancelled';
			showCancelOrderPanel = false;
			
		}
	}
	
	public class faultWrapper {
		public String code {get;set;}
		public String msg {get;set;}
		public faultWrapper(WS_OrderStatusQuery.OrderStatusFault f) {
			code = f.FaultCode;
			msg = f.FaultMessage;
		}
	}
	
	public void buildWrapper(WS_OrderStatusQuery.OrderStatusSuccess resp) {
		rawResponse = new OSQResponse(resp);
	}
	
	public class OSQResponse {
		public String SFOrderNumber {get;set;} 
		public OSQResponse(WS_OrderStatusQuery.OrderStatusSuccess resp) {
			SFOrderNumber = resp.SFOrderNumber;
		}
	}
	
	public void processOrderPrewarehouseCancel() {
		if (!showCancelOrderPanel) {
			showCancelOrderPanel = true;
			ProgramID = '1';
			showPreWareHouseCancel = false;
			return;
		}
		/*boolean retCode = CancelOrderbyProgId('1');
		if(retCode)
		{
		//resetButtons(showPreWareHouseCancel);
		showPreWareHouseCancel = false;
		showCancelOrderPanel = false;
		}*/
	}
	
	public void processOrderPOSTwarehouseCancel() {
		if (!showCancelOrderPanel) {
			showCancelOrderPanel = true;
			showPostWareHouseCancel = false;
			showCancelOrderDisposition = true;
			ProgramID = '3';
			return;
		}
		/*if(selectedDisposition == 'None'){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please select disposition.'));
   
		}
		else{
		boolean retCode = CancelOrderbyProgId('3');
			if (retCode) {
				//resetButtons(showPostWareHouseCancel);
				showPostWareHouseCancel = false;
				showCancelOrderPanel = false;
				
			}
		} */
	}
	
	public void ProcessAllOrderCancelSave(){
		
		if(selectedCancelReason == 'None') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please select order cancellation reason'));
			return;
		}
		
		if (ProgramID == '3') {
			if (selectedDisposition == 'None') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please select disposition.'));
			return;}
		}
		
		boolean retCode = CancelOrderbyProgId(ProgramID);
		if (retCode) {
			showCancelOrderPanel = false;
		}
	}
	
	public void ProcessAllOrderCancelCancel() {
		showCancelOrderPanel = false;
		IF(ProgramID == '3')showPostWareHouseCancel = true;
		IF(ProgramID == '2')showPreWareHouseCancel = true;
		
		
	}
	
	public void processOrderBackOrderCancel() {
		if (!showCancelOrderPanel) {
			showCancelOrderPanel = true;
			return;
		}
		boolean retCode = CancelOrderbyProgId('2');
		if (retCode)
			resetButtons(showBackOrderCancel);
	}
	
	public void processOrderCancelBtn() {
		if (!showCancelOrderPanel) {
			showCancelOrderPanel = true;
			return;
		}
		if (selectedCancelReason == 'None') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please enter a order cancellation reason'));
		} else {
			boolean cancelSuccessful=OrderUtilities.processOrderCancel(OrderId,selectedCancelReason);
			if (cancelSuccessful) {
				resetButtons(showCancelOrderBtn);
				showCancelOrderPanel = false;
			}
		}	
	}
	
	private boolean CancelOrderbyProgId(string ProgramId) {
		boolean retcode = false;
		try {
			// DE DE806 string SFDCOrderNumber = string.isNotBlank(ord.Web_Order_ID__c) ? ord.Web_Order_ID__c : ord.Name ;
			string SFDCOrderNumber = orderutilities.zeroLPAD(ord.Name, 10);
			WS_OrderLineItemCancellation.OrderCancellationResponse_element cancelResponse = new WS_OrderLineItemCancellation.OrderCancellationResponse_element();
			cancelResponse = soa_WebservicesClientUtil.CancelOrderbyProgId(ProgramId, SFDCOrderNumber, selectedCancelReason, selectedDisposition);
			//CancelOrder(String SFDCOrderNumber,String OrderNumber,String ProgramID,String Date_x,String SKU,String SKUPrefix,String Quantity,String Reason,String Alias,String DispositionNumber)
			//process response
			if (cancelResponse.Status != 'Success') {
				retCode = false;
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error Cancelling order: ' + cancelResponse.StatusCode + '-'+ cancelResponse.StatusMessage ));
			} else {
				ord.Cancelled_Reason__c = selectedCancelReason;
				ord.Order_Status__c = 'Cancelled';
				update ord;
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Order Successfully Cancelled'));
				retCode = true;
			}
		}
		catch (exception e) {
			retCode = false;
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error invoking cancellation web service'));
			system.debug('--------Error invoking cancellation Web Service' + e.getmessage());
		}
		
		return retcode;
	}
	
	public void setPageMessages(String msg) {
		ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.INFO, msg);
		ApexPages.AddMessage(pageMsg);
	}
	
	public void setPageMessagesError(String msg) {
		ApexPages.Message pageMsg = new ApexPages.Message(ApexPages.Severity.ERROR, msg);
		ApexPages.AddMessage(pageMsg);
	}
	
	private void resetButtons(boolean showButton) {
		showButton = false;
		
		//showCancelOrderPanel = showPreWareHouseCancel || showPostWareHouseCancel || showBackOrderCancel || showCancelOrderBtn;
		
	}
	
	private void ShowCancelOrderButtons() {
		//ordStatusDetails
		boolean showCancel = orderUtilities.statusSetToCancel(OrderId);
		boolean isUserCSR = orderUtilities.checkProfile('CSR');
		showCancelOrderBtn = showCancel; // Non submitted non cancelled orders
		system.debug('---- Show Cancel --' + showCancelOrderBtn);
		set<string> dispositionSet = new set<string>();
		list<string> dispositionTempList = new list<string>();
		
		system.debug('-----------------Order Status Detail' + ordStatusDetails);
		// If not submitted then no pre, post and back order cancellation.
		showPreWareHouseCancel= showCancel?false:OrderUtilities.statusSetToPreWareHouseCancel(ordStatusDetails);
		showPostWareHouseCancel= (showCancel || !orderUtilities.isUserForPostWarehouseCancel())?false:OrderUtilities.statusSetToPostWareHouseCancel(ordStatusDetails);
		// DE 797 dont show this button showBackOrderCancel= showCancel?false:OrderUtilities.statusSetToBackOrderCancel(ordStatusDetails);
		showBackOrderCancel = false; 
		showCancelOrderPanel = false;
		//showCancelOrderPanel = showPreWareHouseCancel || showPostWareHouseCancel || showBackOrderCancel;
		
		
		DispositionList = new List <SelectOption>();
		if(showPostWareHouseCancel){
			DispositionList.add(new SelectOption ('none','--Select Disposition--'));
			if(showResults){  // Some data in ordStatusDetails
				for(Order_Line_Item_Status_Detail__c ols :ordStatusDetails){
					dispositionSet.add(ols.Disposition_Number__c);
					//DispositionList.add(new SelectOption (ols.Disposition_Number__c,ols.Disposition_Number__c));
				}
				dispositionTempList.addall(dispositionSet);
				dispositionTempList.sort();
				for(string s :dispositionTempList)
					DispositionList.add(new SelectOption (s,s));
			}
		}
	}
	
	public void startClearService() {
		Boolean isBadBill = false;
		ws_Soa_Loyalty_UpdateBillingInfo.updateBillingInformationResponse resp = new ws_Soa_Loyalty_UpdateBillingInfo.updateBillingInformationResponse();
		if (selectedClearOption == 'Resubmit' || selectedClearOption == 'badBill') {
			try {
				WS_soa_ClearOrderService.ER_BO_Response_element response = new WS_soa_ClearOrderService.ER_BO_Response_element();
				response = soa_WebservicesClientUtil.ClearERBOByOrderNumber(orderutilities.zeroLPAD(WS_soa_SendOrderService_v2_Utils.returnSequenceNumber(ord), 10));//
				setPageMessages(response.statusMessage);
				if (response.status == 'Success') {
					system.debug('--------------------------------------------------isDupe: ' + isDupe);
					if (isDupe) {
						system.debug('--------------------------------------------------INSIDE Dupe Code: ');
						//if the order fails as a duplicate but is valid and the order is cleared, set flad for resubmit
						ord.Valid_Duplicate__c = true;
						update ord;
					}
					if (selectedClearOption == 'badBill') {
						isBadBill = true;
						resp = updateBillTo();
					}
					if (isBadBill) {
						if (resp.success == 'T') {
							setPageMessages('Billing Info Successfully Updated');
							setPageMessages('Order placed in pending submission');
							showClearButton = false;
							ord.Order_Status__c = 'Pending Submission';
							ord.Order_Submitted__c = false;
							update ord;
						} else if (resp.success == 'F') {
							setPageMessages(resp.detailMsg);
						}
					} else {
						setPageMessages('Order placed in pending submission');
						showClearButton = false;
						ord.Order_Status__c = 'Pending Submission';
						ord.Order_Submitted__c = false;
						update ord;
					}
					
				}//else do nothing
				
			} catch (exception e) {
				setPageMessagesError('An unknown error has occurred, please contact your System Administrator.');
			}
			
		} else if (selectedClearOption == 'Cancel') {
			showClearButton = false;
			showClearCancel = true;
			
			
		} else if (selectedClearOption == 'CancelClone') {
			showClearButton = false;
			showClearCancel = true;
			
			
		} else if (selectedClearOption == 'None') {
			setPageMessages('You must select a clear option');
		}
		
	}
	
	public ws_Soa_Loyalty_UpdateBillingInfo.updateBillingInformationResponse updateBillTo() {
		String state;
		String province;
		String zip;
		String addLine4;
		String country;
		system.debug('--------------------------------------------------ord.Bill_To_Address__r.Foreign_Postal_Code__c: ' + ord.Bill_To_Address__r.Foreign_Postal_Code__c);
		system.debug('--------------------------------------------------ord.Bill_To_Address__r.Zip_Code__c: ' + ord.Bill_To_Address__r.Zip_Code__c);
		system.debug('--------------------------------------------------ord.Bill_To_Address__r.Country_Picklist__c: ' + ord.Bill_To_Address__r.Country_Picklist__c);
		if (ord.Bill_To_Address__r.Country_Picklist__c == CNTY) {
			system.debug('---------------------------Inside US');
			country = 'US';
			state = ord.Bill_To_Address__r.State_Providence__c;
			zip = ord.Bill_To_Address__r.Zip_Code__c;
			system.debug('---------------------------ZIP: ' + zip);
		} else {
			system.debug('---------------------------Outside US');
			province = ord.Bill_To_Address__r.State_Providence__c;
			zip = ord.Bill_To_Address__r.Foreign_Postal_Code__c;
		}
		
		ws_Soa_Loyalty_UpdateBillingInfo.updateBillingInformationResponse response = new ws_Soa_Loyalty_UpdateBillingInfo.updateBillingInformationResponse();
		response = WS_SOA_LoyaltyServicesUtils.updateBillInfoCallout(ord.Customer__r.AS_400_Customer_Number__c, ord.Customer__r.VW_Passport_Number__c, ord.Bill_To_Address__r.Address_Line_1__c, 
							ord.Bill_To_Address__r.Address_Line_2__c, ord.Bill_To_Address__r.City__c, addLine4, ord.Bill_To_Address__r.Country__c, state, province, zip);
		return response;
	}
	
	public void finishClearService() {
		if (selectedClearOption == 'None') {
			setPageMessages('You must select a clear option');
		} else {
			try {
				WS_soa_ClearOrderService.ER_BO_Response_element response = new WS_soa_ClearOrderService.ER_BO_Response_element();
				//response = temp_Release3MockServices.mockERBOService(ord.Name);
				response = soa_WebservicesClientUtil.ClearERBOByOrderNumber(orderutilities.zeroLPAD(WS_soa_SendOrderService_v2_Utils.returnSequenceNumber(ord), 10));
				setPageMessages(response.statusMessage);
				
				if (response.status == 'Success') {
					showClearButton = false;
					showClearCancel = false;
					ord.Order_Status__c = 'Cancelled';
					ord.Cancelled_Reason__c = selectedCancelReason;
					ord.Order_Submitted__c = false;
					update ord;
					//Clone the order if cancelClone was chosen
					if (selectedClearOption == 'cancelClone') {
						cancelCloneNewTab = true;
					}
				} else {
					showClearButton = true;
					showClearCancel = false;
				}
				
			} catch (exception e) {
				setPageMessagesError('An unknown error has occurred, please contact your System Administrator.');
			}
			
		}
		
	}
	
	public void setNewTabString() {
		// /apex/Order_EditOverride?clone=1
		newTabStr = '/apex/Order_EditOverride?clone=1&id=' + ord.Id;
	}
	
	public static Boolean checkUserProfile() {
		Id userId = UserInfo.getProfileId();
		String pName = [SELECT Name FROM Profile WHERE Id = :userId].Name;
		if (pName == 'System Administrator' || pName == 'Back-Office Team') {
			return true;
		} else {
			return false;
		}
	}
	
	public void setTrackingUrl() {
		system.debug('------------------------------------------------------inside Tracking Method: ' + redirectStr);
		//trackingStr = redirectStr;
	}
	
}