src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>No_Catalogs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer does not want to receive Catalogs.</description>
        <inlineHelpText>Check if this Customer does not want to receive Catalogs.</inlineHelpText>
        <label>No Catalogs?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Invoices__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer does not want to receive a printed Invoice of their order with their shipment.</description>
        <inlineHelpText>Check if this Customer does not want to receive a printed Invoice of their order with their shipment.</inlineHelpText>
        <label>No Invoice?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Peanuts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer does not wish to have packing peanuts used with their shipment.</description>
        <inlineHelpText>Check if this Customer does not wish to have packing peanuts used with their shipment.</inlineHelpText>
        <label>No Peanuts?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Profile_Id__c</fullName>
        <label>Payment Profile ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store (only for VW)</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Ship_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer wishes their Order to be shipped only when able to be shipped in its entirety.</description>
        <inlineHelpText>Check if this Customer wishes their Order to be shipped only when able to be shipped in its entirety.</inlineHelpText>
        <label>Ship Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Substitutes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer does not want to receive substitute items or sizes.</description>
        <inlineHelpText>Check if this Customer does not want to receive substitute items or sizes.</inlineHelpText>
        <label>No Substitutes?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Archive_Summary__c</fullName>
        <label>Archive Summary</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders (Bill To Address)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Date__c</fullName>
        <label>Credit Card Expiration Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Token__c</fullName>
        <label>Credit Card Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <controllingField>Payment_Type__c</controllingField>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JCB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Future_Order_Date__c</fullName>
        <inlineHelpText>What is the date of the Future Order?</inlineHelpText>
        <label>Future Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Future_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this Order is a Future Order.</inlineHelpText>
        <label>Future Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gift_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this Order is a gift.</inlineHelpText>
        <label>Gift Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Catalogs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used to indicate if a customer does not want to receive catalogs.</description>
        <inlineHelpText>This check box is used to indicate if a customer does not want to receive catalogs.</inlineHelpText>
        <label>No Catalogs?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer does not want to receive a printed Invoice of their order with their shipment.</description>
        <inlineHelpText>Check if Customer does not want to receive a printed Invoice of their order with their shipment.</inlineHelpText>
        <label>No Invoice?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Peanuts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer does not wish to have packing peanuts used with their shipment.</description>
        <inlineHelpText>Check if Customer does not wish to have packing peanuts used with their shipment.</inlineHelpText>
        <label>No Peanuts?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Substitutes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer does not want to receive substitute items or sizes.</description>
        <inlineHelpText>Check if Customer does not want to receive substitute items or sizes.</inlineHelpText>
        <label>No Substitutes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Profile_ID__c</fullName>
        <label>Payment Profile ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Customer&apos;s method of payment</description>
        <label>Payment Type</label>
        <picklist>
            <controllingField>Sales_Channel__c</controllingField>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Promotions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotions</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pull_Order_Reason_Multi__c</fullName>
        <label>Pull Order Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Make Sure Caps are Tight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Shipping Traffic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Please Bubble Wrap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ship in More than One Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Catalog</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Shipping Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Advertisements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Peanuts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice on Outside of Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Pull_Order_Reason_Other__c</fullName>
        <label>Pull Order Reason Other</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pull_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if Customer wants to pull this Order.</inlineHelpText>
        <label>Pull Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ship_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer wishes their Order to be shipped only when able to be shipped in its entirety.</description>
        <inlineHelpText>Check if Customer wishes their Order to be shipped only when able to be shipped in its entirety.</inlineHelpText>
        <label>Ship Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_First_Name__c</fullName>
        <label>Ship to First Name</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_to_Last_Name__c</fullName>
        <label>Ship to Last Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Code__c</fullName>
        <description>Source code returned by promotions service</description>
        <label>Source Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_ID__c</fullName>
        <label>Webstack ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Order_EditOverride.cls
/* Order_EditOverride.cls
*  2014-01-30:  Added more fields to orderObj soql query/ Pavan Jasthi
*/
public   class Order_EditOverride {
	private ApexPages.StandardController ctrl;
	public	Orders__c orderObj {get;set;}
	// DE864 -- Allowing Pending Submission orders to be edited
	public static set <String> csrEditableOrderSet = new Set <String>{'Open','Pending Submission','Awaiting Authorization', 'Rejected'};
	public static set <String> nonCsrEditableOrderSet = new Set <String>{'Open','Internal Review','Awaiting Physical Payment','Pending Submission','Awaiting Authorization', 'Rejected','Awaiting Approval'};
	public static set <String> nonEditableSalesChannelSet   = new Set <String> {'Amazon'};
	public static set <String> csrWipeOrderSet = new Set <String>{'Pending Submission'};
	public static set <String> nonCsrWipeOrderSet = new Set <String>{'Pending Submission','Submission Failed'};
	public static boolean canReverseAuth;
	public	boolean isClone ;
	public	boolean isNew ;
	public boolean isMail;
	public boolean isEditOverride;
	public string ProdId;
	public String redirectStr {get;set;}
	public string orderName {get;set;}
	private boolean canUseMailOrderWizard {get; set;}
	public Map<Id, Profile> profileMap {get; set;}
	//public Boolean noTabClose {get;set;}
	
	public Order_EditOverride(ApexPages.StandardController stdController){
		//noTabClose = false;
		redirectStr = '';
		isClone = ApexPages.currentPage().getParameters().get('clone')!=null;
		isMail = ApexPages.currentPage().getParameters().get('mo')!=null;
		isNew = ApexPages.currentPage().getParameters().get('CustId')!=null;
		isEditOverride = ApexPages.currentPage().getParameters().get('override')!=null;
		ProdId = ApexPages.currentPage().getParameters().get('prodId');
		ctrl = stdController;
		Orders__c temporder  = (Orders__c) ctrl.getRecord();
		if (!isNew) {
			// DE643 -- Added fields for pull order items to query for cloning to copy correctly.
			orderObj = [Select Ship_To_Address__c, Bill_To_Address__c, Payment_Profile_Id__c, Credit_Card_Expiration_Date__c, Credit_Card_Token__c ,Credit_card_type__c, Id, Name, Customer__c, Order_Status__c, Sales_Channel__c, Payment_Type__c, Archive_Summary__c, webstack_id__c, pull_order__c, pull_order_reason_multi__c, gift_order__c, future_order__c, ship_complete__c, pull_order_reason_other__c, future_order_date__c,Ship_to_First_Name__c,Ship_to_Last_Name__c,Source_Code__c, Promotions__c From Orders__c where Id =: temporder.Id ];
			orderName = orderObj.name;
			canReverseAuth=orderObj.Payment_Type__c=='Credit Card';
			if(orderObj.Sales_Channel__c == 'Mail')
				isMail = true;
		}
		

	}
	public Orders__c createOrder(Id custId){
		Account customer = [select id, no_peanuts__c, Substitutes__c, No_Catalogs__c, No_Invoices__c, Ship_Complete__c from Account where id =:custId];
		Orders__c newOrder = new Orders__c(Customer__c =customer.id, Pull_Order__c = (customer.No_Catalogs__c ||  customer.No_Peanuts__c || !customer.Substitutes__c || customer.No_Invoices__c || customer.Ship_Complete__c) , No_Catalogs__c = customer.No_Catalogs__c, No_Peanuts__c=customer.No_Peanuts__c,No_Substitutes__c=!customer.Substitutes__c, No_Invoice__c=customer.No_Invoices__c, ship_complete__c = customer.Ship_Complete__c );
		system.debug('*****ismail ' + isMail);
		if(isMail)
			newOrder.Sales_Channel__c = 'Mail';
		insert newOrder;
		orderName =[select name from orders__c where id=:newOrder.id].name;
		return newOrder;
	}
	
	public static boolean  isEditOverride(Orders__c orderObj){
		if ( OrderUtilities.checkProfile('System Administrator')||OrderUtilities.checkProfile('Back-Office Team')){ 
			//return !nonEditableSalesChannelSet.contains(orderObj.sales_channel__c); //check is configured set contains status; return true/false
			// DE880 -- use new function
			return OrderUtilities.CanEditSalesChannel(orderObj.Webstack_Id__c);
		}
		else {
			return false;
		}
	}
	
	public static boolean  isEditableOrder(Orders__c orderObj){
		// DE880 -- use new function to block editing where needed
		if (OrderUtilities.checkProfile('CSR')){ 
			return csrEditableOrderSet.contains(orderObj.order_status__c)&&OrderUtilities.CanEditSalesChannel(orderObj.Webstack_Id__c);//!nonEditableSalesChannelSet.contains(orderObj.sales_channel__c); //check is configured set contains status; return true/false
		}
		else {
			return nonCsrEditableOrderSet.contains(orderObj.order_status__c)&&OrderUtilities.CanEditSalesChannel(orderObj.Webstack_Id__c);//!nonEditableSalesChannelSet.contains(orderObj.sales_channel__c);
		}
	}
	
	public static boolean isWipeOrder(Orders__c orderObj){
		if (OrderUtilities.checkProfile('CSR')){
			return canReverseAuth&&csrWipeOrderSet.contains(orderObj.order_status__c)&&!nonEditableSalesChannelSet.contains(orderObj.sales_channel__c); //check is configured set contains status; return true/false
		}
		else {
			return canReverseAuth&&nonCsrWipeOrderSet.contains(orderObj.order_status__c)&&!nonEditableSalesChannelSet.contains(orderObj.sales_channel__c);
		}
	}
	
	public void redirect(){

		if (isNew){  //New order
			Orders__c newOrder =createOrder(ApexPages.currentPage().getParameters().get('CustId'));
			if (ProdId!=null){
				redirectStr = '/apex/OrderWizard?id='+newOrder.Id+'&prodId='+ProdId;
			}
			else if(isMail) //New Mail Order
			{
				redirectStr = '/apex/OrderWizardMailOrders?id='+newOrder.Id;

			}
			else {
				redirectStr = '/apex/OrderWizard?id='+newOrder.Id;
			}
		}
		else if (isClone){ //Clone order
			Orders__c newOrder =orderObj.clone(false,false,false,false);
			newOrder.order_status__c='Open';
			newOrder.sales_channel__c= isMail? 'Mail':'Phone';
			try {
			insert newOrder;
			}
			catch (exception e){
				if (e.getMessage().contains('USPS')){
					newOrder.Shipping_Method__c = 'USPS';
				}
				try {
					insert newOrder;
				}
				catch (exception et){
					  ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,et.getMessage()));
				}
			}
			// DE606 -- Cloned orders were not displaying new order number. this let's them.
			orderName = [select name from orders__c where id=:newOrder.id].name;
			
			List <Order_Line_Items__c> oliList =    [SELECT Id, Product_Name__c, Product_Quantity__c, Original_Quantity__c, Product_Number__c, Price_Override__c, Override_Reason__c, Unit_Price__c, Final_Price__c, Tax__c  
																				FROM 	Order_Line_Items__c 
																				WHERE 	order__c=:orderObj.id
																				AND		Product_name__r.is_active__c=true//possibility products may not be active anymore
																				];
			if (oliList.size() == 0){
				try {
					oliList = OrderLineItemArchiveUtilities.restoreOlisFromArchive(orderObj);
				}
				catch (exception e){
					system.debug('Cannot restore from archive');
				}
			}
			if (oliList!=null){
				oliList = oliList.deepClone(false, false, false);
				for (Order_Line_Items__c oli: oliList){
					oli.order__c = newOrder.id;
				}
				insert oliList;
			}
			// DE884 -- Was allowing CSR to use Mail Order through cloning only
			canUseMailOrderWizard = false;
			// Get current user Id
			String userId = [Select Id from User where Name =: userInfo.getName()].Id;
			// Get Mail Order Permission set Id
			PermissionSet ps = [Select Id from PermissionSet where Name = 'Mail_Order'];
			// See if this user is in the PermissionSetAssignment list
			List<PermissionSetAssignment> psa = [Select Id from PermissionSetAssignment where PermissionSetId =: ps.Id and AssigneeId =: userId];
			// if the list found 1 (or more?) they can edit			
			if (psa.size() > 0) {
				canUseMailOrderWizard = true;
			}
			// DE884 -- update to DE863 
			// DE863 -- Allow cloning of mail order to open in mail order wizard right away
			if (isMail && canUseMailOrderWizard){
				redirectStr = '/apex/OrderWizardMailOrders?Id=' + newOrder.Id;
			} else {
				redirectStr = '/apex/OrderWizard?id='+newOrder.Id;
			}
			orderObj = newOrder;
		}
		else if (isEditOverride) {
			if (isEditOverride(orderObj)){
				//notabClose = true;
				redirectStr = '/'+orderObj.id + '/e?retURL=%2F' + orderObj.id + '&nooverride=1';
			}
		} // Mail order change
		else if(isMail) //Edit
		{
			if(orderutilities.isUserForMailOrder())
				redirectStr = '/apex/OrderWizardMailOrders?Id='+orderObj.Id;
			 else // Error
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'User not authorized to edit Mail Order. \n Please contact System Admin.'));
			
		}
		else {//edit order to determine edit page to show
			if (isEditableOrder(orderObj)){
				redirectStr = '/apex/OrderWizard?Id='+orderObj.Id;
			}
			else if (isWipeOrder(orderObj)){ //reverse auth and wipe payment details for web order; set as phone order
				redirectStr = '/apex/OrderWizard?Id='+orderObj.Id+'&reverse=1';
			}
			else {
				redirectStr = '/apex/Order_Detail?id='+orderObj.id;
			}
		}
	//	PageReference pageRef = new PageReference( redirectStr);
	//	pageRef.setRedirect(true);
	//	return pageRef;
	}
}