src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AS_400_Customer_Number__c</fullName>
        <externalId>true</externalId>
        <label>AS/400 Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VW_Passport_Number__c</fullName>
        <label>VW Passport Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>First Line of Address</description>
        <inlineHelpText>First Line of the Address for the Customer&apos;s Address</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the Customer&apos;s address</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_4__c</fullName>
        <label>Address Line 4</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UNITED STATES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASCENSION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BONAIRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Bill_To_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This designates the primary Billing address for the Customer.</description>
        <inlineHelpText>Check this box to designate that this address is the primary Billing address for the Customer.</inlineHelpText>
        <label>Primary Bill To Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Providence__c</fullName>
        <description>State or Province for the Customer&apos;s Address</description>
        <inlineHelpText>State or Province for the Customer&apos;s Address</inlineHelpText>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MockResponse_Loyalty_RetrieveInfo.cls
@isTest
global class MockResponse_Loyalty_RetrieveInfo  implements WebServiceMock {
	
	public static string maketoken(integer tokenLength) {
		string text = '';
		string possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
		for( integer i=0; i < tokenLength; i++ ){
			integer loc = integer.valueOf(Math.floor(Math.random() * possible.length()));
			text += possible.substring(loc,loc+1);
		}
		system.debug(text);
		return text;
	} 
	global void doInvoke(Object stub,Object request,Map<String, Object> response,String endpoint,String soapAction,
							String requestName,
							String responseNS,
							String responseName,
							String responseType) {
		
		ws_Soa_Loyalty_RetrieveInfo.retrieveInfoResponse retrieveInfoResponse = new ws_Soa_Loyalty_RetrieveInfo.retrieveInfoResponse();
		ws_Soa_Loyalty_RetrieveInfo.retrieveInfoSuccessResponse successResponse;
		ws_Soa_Loyalty_RetrieveInfo.retrieveInfoFailureResponse  failureResponse;
		// retrieveInfoResponse.customerNumber=CustomerNumber;
		Account  acct = [select id, AS_400_Customer_Number__c,VW_Passport_Number__c from Account where AS_400_Customer_Number__c='987654321' and recordType.developerName ='Vitamin_World_Customer' limit 1 ];
		if (acct!=null){
		//if (string.valueOf(acct.AS_400_Customer_Number__c).substring(string.valueOf(acct.AS_400_Customer_Number__c).length()-1,string.valueOf(acct.AS_400_Customer_Number__c).length())=='1'){
			//failureResponse = new ws_Soa_Loyalty_RetrieveInfo.retrieveInfoFailureResponse ();
		//} else {
				successResponse = new ws_Soa_Loyalty_RetrieveInfo.retrieveInfoSuccessResponse();
				Address__c address = [select Address_Line_1__c, Address_Line_2__c, Address_Line_3__c, Address_Line_4__c,City__c,Zip_Code__c,State_Providence__c, Country_Picklist__c from Address__c where customer__c=:acct.id and primary_bill_to_address__c = true];
			//	retrieveInfoResponse.LoyaltyNumber=acct.VW_Passport_Number__c;
			//	retrieveInfoResponse.passportNumber=integer.valueOf(math.floor(math.random()*100));
				successResponse.BillingInfo = new ws_Soa_Loyalty_RetrieveInfo.billingInfo ();
				successResponse.BillingInfo.AddressLine1=address.Address_Line_1__c;
				successResponse.BillingInfo.AddressLine2=address.Address_Line_2__c;
				successResponse.BillingInfo.AddressLine3=address.Address_Line_3__c;
				successResponse.BillingInfo.AddressLine4=address.Address_Line_4__c;
			//	successResponse.BillingInfo.City=address.City__c;
				successResponse.BillingInfo.Country=address.Country_Picklist__c;
				successResponse.BillingInfo.State=address.State_Providence__c;
				successResponse.BillingInfo.ZipCode=address.Zip_Code__c;
				successResponse.pointsToDate=string.valueOf(math.floor(math.random()*100));
				successResponse.Coupons = new List <ws_Soa_Loyalty_RetrieveInfo.couponDetail >();
				integer randomSize = integer.valueOf(math.floor(math.random()*10));
				
				for (integer k=0; k<randomSize; k++){
					ws_Soa_Loyalty_RetrieveInfo.couponDetail coupon = new ws_Soa_Loyalty_RetrieveInfo.couponDetail();
					boolean randomBool = math.random() > .5?true:false;
					coupon.Amount=string.valueOf(decimal.valueOf(math.random()*10).setScale(2));
					coupon.Code=makeToken(4);
					integer randomNeg = math.random()> .5 ? -1 : 1;
					coupon.ExpirationDate=string.valueOf(system.today().addDays(integer.valueOf(math.floor(randomNeg*math.random()*365))));
					coupon.status = date.valueOf(coupon.ExpirationDate) > system.today() ? (randomBool ?  'active': 'redeemed') : (randomBool ?  'expired': 'redeemed');
					successResponse.Coupons.add(coupon);
				}
		//}
		}
		retrieveInfoResponse.retrieveInfoSuccessResponse=successResponse;
		retrieveInfoResponse.retrieveInfoFailureResponse=failureResponse;
		system.debug('response~~~~'+retrieveInfoResponse);

			

			response.put('response_x', retrieveInfoResponse);
				
		}

}