src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Possible_Fraud__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Possible Fraud?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Batch__c.object
<CustomObject>
    <description>Aggregate value at the batch level of all related orders</description>
    <fields>
        <fullName>Aggregate_Value__c</fullName>
        <label>Aggregate Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <externalId>true</externalId>
        <label>Batch Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Batch</label>
    <nameField>
        <displayFormat>BN-{00000}</displayFormat>
        <label>Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <externalId>true</externalId>
        <label>Batch Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Value__c</fullName>
        <label>Payment Value</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderTriggerHelperTest.cls
@isTest
public class OrderTriggerHelperTest {
	static testMethod void testPossibleFraudStatusChange(){
		//US236
		//INC703623 - make sure order is created using CSR profile
		testDataSetupUtil.SetupCoreData(2); //set up the basic data
		testDataSetupUtil.acct.possible_fraud__c=true; //flag the account as possible fraud
		update testDataSetupUtil.acct; //update dml
				test.startTest();
		testDataSetupUtil.order1.Order_Status__c = 'Pending Submission'; //submit the order
		update testDataSetupUtil.order1; //update dml for the order
		test.stopTest();
		//system.assert([select order_status__c from Orders__c where id =:testDataSetupUtil.order1.id].order_status__c=='Internal Review');//verify it was automatically set to internal review
		
	}
	
	static testMethod void testBatchAggregate(){
		testDataSetupUtil.SetupCoreData(2); //set up the basic data
		testDataSetupUtil.order1.Batch_Number__c='1234';
		testDataSetupUtil.order1.payment_value__c = 12;
		testDataSetupUtil.order1.Order_Total__c=12;
		test.startTest();
		
		update testDataSetupUtil.order1; //update dml for the order
		system.assert([select count() from Batch__c ]==1);
			testDataSetupUtil.order1.Batch_Number__c='1235';
		testDataSetupUtil.order1.payment_value__c = 12;
		testDataSetupUtil.order1.Order_Total__c=12;

		update testDataSetupUtil.order1; //update dml for the order
		
		test.stopTest();
					List <Batch__c> batchList = [select id, Aggregate_Value__c from Batch__c order by Batch_number__c];
					system.debug(batchList);
				system.assertEquals(1,batchList.size()); 
				system.assertEquals(12.00,batchList[0].Aggregate_Value__c);	
	
		
	}
	
	static testMethod void testFormatAddressData(){
		testDataSetupUtil.SetupCoreData(2); 
		
		test.startTest();
		
		for (Address__c a: testDataSetupUtil.addressList){
			orderTriggerHelper.formatAddressData(a);
		}
		
		test.stopTest();
	}
	
	static testMethod void testSetDefaultShippingMethod(){
		testDataSetupUtil.SetupCoreData(2); 
		
		test.startTest();
		List<Orders__c> orders = new List<Orders__c>();
		
		orders.add(testDataSetupUtil.order1);
		
		orderTriggerHelper.setDefaultShippingMethod(orders);
		
		test.stopTest();
	}

	static testMethod void testValidateBeforeDelete(){
		testDataSetupUtil.SetupCoreData(2);
		
		test.startTest();
		List<Orders__c> orders = new List<Orders__c>();
		testDataSetupUtil.order1.Order_Submitted__c = true;
		update testDataSetupUtil.order1;
		
		orders.add(testDataSetupUtil.order1);
		OrderTriggerHelper.isDeleteAllowed = false;
		
		OrderTriggerHelper.ValidateBeforeDelete(orders);
		
		test.stopTest();
	}
}