src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AS_400_Customer_Number__c</fullName>
        <externalId>true</externalId>
        <label>AS/400 Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store (only for VW)</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CTI_Search__c</fullName>
        <label>CTI Search</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>CTI_Search__c</fullName>
        <label>CTI Search</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Channel__c</fullName>
        <label>Sales Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_Order_ID__c</fullName>
        <label>Webstack Order ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting for all Web Service Integration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value Associated for the Name</description>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>WS_Integration</label>
</CustomObject>

src/classes/TestInboundCallController.cls
/* 
	TestInboundCallController
	Test Class for CTI
	------------------------------------------------------------------
	Author			|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey   	|	4/16/2013	|	Created

*/

@isTest
private class TestInboundCallController {

	static testMethod void myUnitTest() {
		TestDataSetupUtil.processCrtBrandMapping();
		WS_Integration__c turnOffBadCust = new WS_Integration__c();
		turnOffBadCust.Name = 'BadCustOff';
		turnOffBadCust.Value__c = 'true';
		insert turnOffBadCust;
		JSONGenerator gen = JSON.createGenerator(true);
		gen.writeStartObject();
		gen.writeStringField('PerVar1', '');
		gen.writeStringField('PerVar2', '');
		gen.writeStringField('PerVar3', '');
		gen.writeStringField('PerVar4', 'Vitamin World');
		gen.writeStringField('PerVar5', '');
		gen.writeStringField('PerVar6', '');
		gen.writeStringField('PerVar7', 'Ent.Tele_Sales');
		gen.writeStringField('PerVar8', '');
		gen.writeStringField('PerVar9', '');
		gen.writeStringField('PerVar10', '');
		gen.writeStringField('Id', '33556862');
		gen.writeStringField('State', 'ACTIVE');
		gen.writeStringField('DNIS', '155917');
		gen.writeStringField('DialedNumber', '4997');
		gen.writeStringField('Sender', '4195715968');
		gen.writeStringField('Direction', 'Inbound');
		gen.writeStringField('UniqueId', '1.23456789');
		gen.writeEndObject();
		String jsonText = gen.getAsString();
		
		Task t = new Task();
		t.CNX2__UniqueCallId__c = '1.23456789';
		insert t;
		
		List<Task> tList = new List<Task>();
		for(Integer i=0; i<20; i++){
			Task t2 = new Task();
			t2.Brand__c = 'Vitamin World';
			t2.ANI__c = '4195715968';
			t2.CNX2__UniqueCallId__c = '1.23456780' + String.valueOf(i);
			tList.add(t2);
		}
		for(Integer i=0; i<10; i++){
			Task t2 = new Task();
			t2.Brand__c = 'Puritan\'s Pride';
			t2.ANI__c = '4195715968';
			t2.CNX2__UniqueCallId__c = '1.23456700' + String.valueOf(i);
			tList.add(t2);
		}
		insert tList;
		
		RecordType vw = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Vitamin_World_Customer' AND isPersonType = true];
		RecordType pp = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'Puritans_Pride_Customer' AND isPersonType = true];
		List<Account> aList = new List<Account>();
		for(Integer i=0; i<20; i++){
			Account a = new Account();
			a.RecordTypeId = vw.Id;
			a.Salutation = 'Mr.';
			a.FirstName = 'John';
			a.LastName = 'Doe' + String.valueOf(i);
			a.AS_400_Customer_Number__c = '987654321';
			a.PersonEmail = 'jDoe@test'+ String.valueOf(i) +'.com';
			a.Phone = '(419) 571-5968';
			aList.add(a);
		}
		for(Integer i=0; i<20; i++){
			Account a = new Account();
			a.RecordTypeId = pp.Id;
			a.Salutation = 'Mr.';
			a.FirstName = 'James' + String.valueOf(i);
			a.LastName = 'Doe';
			a.AS_400_Customer_Number__c = '987654321' + String.valueOf(i);
			a.PersonEmail = 'jDoe' + String.valueOf(i) + '@test.com';
			a.Phone = '(419) 571-5968';
			aList.add(a);
		}
		insert aList;
		
		List<Orders__c> ordList = new List<Orders__c>();
		for(Account acct : aList){
			Orders__c ord = new Orders__c();
			ord.Customer__c = acct.Id;
			ord.Order_Date__c = date.today();
			//ord.Order_Status__c = 'Internal Review';
			ord.Sales_Channel__c = 'Phone';
			ord.Sequence_Number__c = '2166549802';
			ord.Webstack_Order_ID__c = '1234567890';
			ord.CTI_Search__c = '(419) 571-5968';
			ordList.add(ord);
		}
		insert ordList;
		
		List<Case> cList = new List<Case>();
		for(Integer i=0; i<20; i++){
			Case c = new Case();
			c.CTI_Search__c = '4195715968';
			c.Brand__c = 'Vitamin World';
			cList.add(c);
		}
		for(Integer i=0; i<20; i++){
			Case c = new Case();
			c.CTI_Search__c = '4195715968';
			c.Brand__c = 'Puritan\'s Pride';
			cList.add(c);
		}
		insert cList;
		test.startTest();
		CnxCustomerEnhancements.updateCallLog(null, jsonText);
		
		InboundCallController a = new InboundCallController();
		a.Init();
		a.DoSearch();
		a.ABLast();
		a.ABFirst();
		a.ABNext();
		a.ABPrevious();
		a.AOLast();
		a.AOFirst();
		a.AONext();
		a.AOPrevious();
		a.lastAAB();
		a.firstAAB();
		a.nextAAB();
		a.previousAAB();
		a.lastAAO();
		a.firstAAO();
		a.nextAAO();
		a.previousAAO();
		a.lastCAB();
		a.firstCAB();
		a.nextCAB();
		a.previousCAB();
		a.lastCAO();
		a.firstCAO();
		a.nextCAO();
		a.previousCAO();
		test.stopTest();
	}
}