src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Payment_Profile_Id__c</fullName>
        <label>Payment Profile ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>First Line of Address</description>
        <inlineHelpText>First Line of the Address for the Customer&apos;s Address</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the Customer&apos;s address</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UNITED STATES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASCENSION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BONAIRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State_Providence__c</fullName>
        <description>State or Province for the Customer&apos;s Address</description>
        <inlineHelpText>State or Province for the Customer&apos;s Address</inlineHelpText>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Authorization_Amount__c</fullName>
        <label>Authorization Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_Response_Date_Time__c</fullName>
        <label>Bank Response Date &amp; Time</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders (Bill To Address)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <label>Card Holder Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Date__c</fullName>
        <label>Credit Card Expiration Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <description>Encrypted Credit Card Number for re-authorization.</description>
        <label>Credit Card Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Token__c</fullName>
        <label>Credit Card Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <controllingField>Payment_Type__c</controllingField>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JCB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Authorization_Code__c</fullName>
        <label>Payment Authorization Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Profile_ID__c</fullName>
        <label>Payment Profile ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Transaction_Reference_Index__c</fullName>
        <label>Payment Transaction Reference Index</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Transaction_Reference_Number__c</fullName>
        <label>Payment Transaction Reference Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Re_Authorize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Re-Authorize?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replay_Existing_CC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only for use within code to determine if an existing cc token or a new cc will be used for authorization.</description>
        <label>Replay Existing CC</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReplayBatch.cls
/* 
	ReplayBatch
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey   |	??/??/???	|	Created

*/


global class ReplayBatch implements Database.Batchable<sObject> , Database.AllowsCallouts{
	
	public Set<String> ordStatuses;
	
	global ReplayBatch(){
		if(ordStatuses == null){
			ordStatuses = new Set<String>{'Awaiting Authorization','Payment Authorization Failed'};
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		String query = 'SELECT Id, Name, Replay_Existing_CC__c, Credit_Card_Expiration_Date__c, Credit_Card_Type__c, Credit_Card_Number__c, Card_Holder_Name__c, Re_Authorize__c, CreatedById, ';
		query += 'Credit_Card_Token__c, Order_Status__c, customer__r.Payment_Profile_Id__c, customer__r.recordType.developerName, Bill_To_Address__c, Order_Total__c FROM Orders__c WHERE Re_Authorize__c = true AND Order_Status__c IN :ordStatuses';
		return Database.getQueryLocator(query);
	}
	
	global static void processReAuth(List <Orders__c> ordlist) {
		string groupType = 'Queue';
		Map <String, QueueSobject> oQueueMap = new Map <String, QueueSobject>();
		for (QueueSobject q : [SELECT Id, QueueId, Queue.DeveloperName FROM QueueSobject WHERE SobjectType = 'Orders__c']) {
			oQueueMap.put(q.Queue.DeveloperName, q);
		}
		
		for (Orders__c ord : ordList) {
			WS_soa_AuthorizePaymentService.paymentResponse resp = new WS_soa_AuthorizePaymentService.paymentResponse();
			WS_soa_AuthorizePaymentService.PaymentInfo paymentInfo = new WS_soa_AuthorizePaymentService.PaymentInfo();
			system.debug('-----------------------------------------------------Order Total: ' + ord.Order_Total__c);
			try {
				if (ord.Replay_Existing_CC__c) {
					resp = soa_WebservicesClientUtil.payfromExistingCard(ord.id,ord.Credit_Card_Token__c);
				} else {
					Address__c addr = [SELECT Id, Zip_Code__c, State_Providence__c, Country__c, Country_Picklist__c, City__c, 
										Address_Line_2__c, Address_Line_1__c FROM Address__c WHERE Id = :ord.Bill_To_Address__c];
					
					paymentInfo.orderId = ord.name;
					paymentInfo.amount = ord.Order_Total__c.setScale(2);
					system.debug('-----------------------------------------------------paymentInfo.amount: ' + paymentInfo.amount);
					paymentInfo.creditCardNumber = ord.Credit_Card_Number__c.replace('-','');
					paymentInfo.expiryYYYYMM = ord.Credit_Card_Expiration_Date__c;
					paymentInfo.creditCardType = ord.Credit_Card_Type__c;
					paymentInfo.nameOnCard = ord.Card_Holder_Name__c;
					paymentInfo.countryCode = addr.Country__c;
					if (paymentInfo.state == null && paymentInfo.countryCode != 'US' && paymentInfo.countryCode != 'CA') {
						paymentInfo.state = 'FO';
					} else {
						paymentInfo.state = addr.State_Providence__c;
					}
					paymentInfo.city = addr.City__c;
					paymentInfo.zipCode = addr.Zip_Code__c;
					paymentInfo.addressLine1 = addr.Address_Line_1__c==null? '': addr.Address_Line_1__c;
					paymentInfo.addressLine2 =  addr.Address_Line_2__c==null? '': addr.Address_Line_2__c;
					paymentInfo.merchantKey = NBTYUtils.getRecordTypeBrandMappingMap().get(ord.customer__r.recordType.developerName).merchant_key__c;
					boolean hasPaymentProfile =  ord.customer__r.Payment_Profile_Id__c != null;
					paymentInfo.paymentProfileID = hasPaymentProfile? ord.customer__r.Payment_Profile_Id__c : '';
					system.debug('paymentInfo~~~'+paymentInfo);
					resp = soa_WebservicesClientUtil.ProcessPaymentForNewCard(paymentInfo,hasPaymentProfile);
					
				}
			} catch (exception e) {
				ord.Order_Status__c='Payment Authorization Failed';
				ord.OwnerId = oQueueMap.get('Orders_Payment_Authorization_Failed').QueueId;
				//Set Queue to Orders - Payment Authorization Failed
			}
		
			system.debug('----------------------------------------------------------Response resp: ' + resp);
			if (resp.TokenNumber != '') {
				system.debug('----------------------------------------------------------Replay Success');
				//ord.ownerId=userInfo.getUserId();//US468 this needs to be the original owner CreatedByID
				ord.OwnerId = ord.CreatedById;
				// 060982013 RB changes for Payment information
				system.debug('~~~~~ Expiration date of existing card' + paymentInfo.expiryYYYYMM);
				ord.Payment_Authorization_Code__c = resp.AuthorizationCode;
				ord.Credit_Card_Token__c = resp.TokenNumber;
				ord.Payment_Profile_ID__c = resp.PaymentProfileID;
				ord.Payment_Transaction_Reference_Number__c = resp.TransactionReferenceNumber;
				ord.Payment_Transaction_Reference_Index__c = resp.TransactionReferenceIndex;
				ord.Bank_Response_Date_Time__c = resp.BankResponseDateTime;
				if (ord.Replay_Existing_CC__c) {
					ord.Authorization_Amount__c = ord.Order_Total__c;
				} else {
					ord.Authorization_Amount__c = paymentInfo.amount;
				}
				ord.Order_Status__c='Pending Submission';
				//Null out the CC # encrypted field
				ord.Credit_Card_Number__c = null;
				ord.Re_Authorize__c = false;
			} else if(resp.StatusCode != '') {
				//Leave all fields
				//Set status to Payment Authorization Declined
				ord.Order_Status__c = 'Payment Declined';
				//Set Queue to Orders - Payment Declined
				ord.OwnerId = oQueueMap.get('Orders_Payment_Declined').QueueId;
			} else {
				system.debug('----------------------------------------------------------Replay Fault');
				//Leave all fields
				//Set status to Payment Authorization Failed
				ord.Order_Status__c = 'Payment Authorization Failed';
				//Set Queue to Orders - Payment Authorization Failed
				ord.OwnerId = oQueueMap.get('Orders_Payment_Authorization_Failed').QueueId;
			}
		}
		update ordList;
	}
	
	global static void processRequest() {
		
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		//Scope is always 1
		List<Orders__c> ordList = (List<Orders__c>)scope;
		processReAuth(ordList);
	}

	global void finish(Database.BatchableContext BC) {
		AuthDownTimeUtils.checkScheduleStatus2();
	}
}