src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AS_400_Customer_Number__c</fullName>
        <externalId>true</externalId>
        <label>AS/400 Customer Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Bundle__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Bundles</relationshipLabel>
        <relationshipName>Bundles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Rec_Type_Brand_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Brand_Image__c</fullName>
        <description>Name of static resource that represents the brand.</description>
        <label>Brand Image</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Suffix_c__c</fullName>
        <label>Product_Suffix__c</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TenantID__c</fullName>
        <description>Tenant ID for AgilOne recommendations</description>
        <label>TenantID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Customer Rec Type Brand Mapping</label>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_Suffix__c</fullName>
        <description>0011 - PP 0070 VB</description>
        <label>Item Suffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecommendationsWrapper.cls
/* RecommendationsWrapper 
*  Wrapper class for Recommendations on Customer page and Order wizard page.
*  2014-01-10:  Not checking for As400 number for new customers/ Pavan Jasthi
*/
public  class RecommendationsWrapper {
    public List <Item__c>   productList {get;set;}
    public Account              acct            {get;set;}
    public Item__c              product     {get;set;}
    public Id                           orderId         {get;set;}
    public string                   tenantId;
    public static string productSuffix;
    public string                   errorMessage    {get;set;}
    public StaticResource brandLogo {get; set;}
    public boolean              hasRecs             {get;set;}
    public RecommendationsWrapper(Id orderId){              
            Orders__c ord = [select Customer__c, id from Orders__c where Id =: orderId ];
            acct = [Select PersonEmail, AS_400_Customer_Number__c,RecordType.Name From Account where id=:ord.Customer__c ];
            tenantId=setTenantIdForAccount(acct);
            initWrapper(true);
    }
    
    public RecommendationsWrapper(Account account){
            hasRecs=false;
            acct = [Select PersonEmail, AS_400_Customer_Number__c,RecordType.DeveloperName, RecordType.name From Account where id=:account.id ];
            tenantId=setTenantIdForAccount(acct);
            this.brandLogo = setBrandLogoForAccount(acct);
            if(string.isBlank(tenantID))
                errorMessage = 'No Recommendation available for customer type: ' + acct.RecordType.Name; 
            else
            {
                initWrapper(true); 
            }
            
            if(productlist== null){
                      
                     // Show API error messages
                     errorMessage = string.isnotblank(errorMessage) ? errorMessage : 'No Recommendations available for this customer.';
                  
            }
            else {
                if (productList.isEmpty()) errorMessage = string.isnotblank(errorMessage) ? errorMessage : 'No Recommendations available for this customer.'; 
                else hasRecs=true;
            }
            
    }
    
    
    public RecommendationsWrapper(Item__c product){
        this.product =product;
         tenantID = NBTYUtils.getSuffixToBrandMappingMap().get(product.Product_Suffix__c).tenantId__c;
        initWrapper(false);
    }
    
    public static string setTenantIdForAccount (Account acct){
        string tenantId;
        string accRecordType = acct.RecordType.DeveloperName;
         system.debug('**** ' + accRecordType);
         Customer_Rec_Type_Brand_Mapping__c rtbm = NBTYUtils.getRecordTypeBrandMappingMap().get(acct.RecordType.DeveloperName);
         tenantID =  rtbm.tenantID__c;
         productSuffix = rtbm.Product_Suffix_c__c;
         return tenantId;
    }
    
    public static StaticResource setBrandLogoForAccount(Account acct){
        StaticResource sr;
        string accRecordType = acct.RecordType.DeveloperName;
        system.debug('**** ' + accRecordType);
        Customer_Rec_Type_Brand_Mapping__c rtbm = NBTYUtils.getRecordTypeBrandMappingMap().get(acct.RecordType.DeveloperName);
        try {
            sr =[ select id, name from StaticResource where name =:rtbm.brand_image__c];
        } 
        catch (exception e){
            system.debug('cannot find logo');
        }
        return sr;
    }
    
    
    public void initWrapper(boolean isU2P){
          try{
                productList = new List <Item__c>();
                List <Bundle__c> bundleList = NBTYWSUtil.getActiveBundles(productSuffix);
                if (!bundleList.isEmpty()){
                    for (Bundle__c b: bundleList){
                        productList.add(b.item__r);
                    }
                }
                if (tenantId!=null){
                    if (isU2P){
                        if(string.isNotBlank(acct.AS_400_Customer_Number__c)){
                            productList.addAll( NBTYWSUtil.getU2PAgileOneProductsByAccountID(acct.AS_400_Customer_Number__c,tenantID));
                        }
                    }
                    else {
                        productList.addAll( NBTYWSUtil.getP2PAgileOneProducts(product.id, tenantID));
                    }
                }
          }
            
          
            Catch(NBTYException e){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
                errorMessage = e.getMessage();
            }
            Catch(Exception e){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Error in getting U2P recommendations.'));
                system.debug(e.getMessage());
            }
    }
}