src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Associate_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer is an Associate.</description>
        <inlineHelpText>Check if this Customer is an Associate.</inlineHelpText>
        <label>Associate Customer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Associate_ID__c</fullName>
        <label>Associate ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Catalogs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer does not want to receive Catalogs.</description>
        <inlineHelpText>Check if this Customer does not want to receive Catalogs.</inlineHelpText>
        <label>No Catalogs?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Peanuts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer does not wish to have packing peanuts used with their shipment.</description>
        <inlineHelpText>Check if this Customer does not wish to have packing peanuts used with their shipment.</inlineHelpText>
        <label>No Peanuts?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Profile_Id__c</fullName>
        <label>Payment Profile ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if this Customer wishes their Order to be shipped only when able to be shipped in its entirety.</description>
        <inlineHelpText>Check if this Customer wishes their Order to be shipped only when able to be shipped in its entirety.</inlineHelpText>
        <label>Ship Complete?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>First Line of Address</description>
        <inlineHelpText>First Line of the Address for the Customer&apos;s Address</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the Customer&apos;s address</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Foreign_Postal_Code__c</fullName>
        <label>Foreign Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Providence__c</fullName>
        <description>State or Province for the Customer&apos;s Address</description>
        <inlineHelpText>State or Province for the Customer&apos;s Address</inlineHelpText>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code_4__c</fullName>
        <label>Zip Code 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <label>Card Holder Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Catalog_Source_Code__c</fullName>
        <description>Catalog Source Code</description>
        <label>Catalog Source Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Date__c</fullName>
        <label>Credit Card Expiration Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <description>Encrypted Credit Card Number for re-authorization.</description>
        <label>Credit Card Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Token__c</fullName>
        <label>Credit Card Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <controllingField>Payment_Type__c</controllingField>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JCB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Future_Order_Date__c</fullName>
        <inlineHelpText>What is the date of the Future Order?</inlineHelpText>
        <label>Future Order Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Future_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this Order is a Future Order.</inlineHelpText>
        <label>Future Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gift_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if this Order is a gift.</inlineHelpText>
        <label>Gift Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Catalogs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This check box is used to indicate if a customer does not want to receive catalogs.</description>
        <inlineHelpText>This check box is used to indicate if a customer does not want to receive catalogs.</inlineHelpText>
        <label>No Catalogs?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer does not want to receive a printed Invoice of their order with their shipment.</description>
        <inlineHelpText>Check if Customer does not want to receive a printed Invoice of their order with their shipment.</inlineHelpText>
        <label>No Invoice?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Peanuts__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer does not wish to have packing peanuts used with their shipment.</description>
        <inlineHelpText>Check if Customer does not wish to have packing peanuts used with their shipment.</inlineHelpText>
        <label>No Peanuts?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Substitutes__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer does not want to receive substitute items or sizes.</description>
        <inlineHelpText>Check if Customer does not want to receive substitute items or sizes.</inlineHelpText>
        <label>No Substitutes?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Profile_ID__c</fullName>
        <label>Payment Profile ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Customer&apos;s method of payment</description>
        <label>Payment Type</label>
        <picklist>
            <controllingField>Sales_Channel__c</controllingField>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pull_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if Customer wants to pull this Order.</inlineHelpText>
        <label>Pull Order?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Re_Authorize__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Re-Authorize?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Replay_Existing_CC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only for use within code to determine if an existing cc token or a new cc will be used for authorization.</description>
        <label>Replay Existing CC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if Customer wishes their Order to be shipped only when able to be shipped in its entirety.</description>
        <inlineHelpText>Check if Customer wishes their Order to be shipped only when able to be shipped in its entirety.</inlineHelpText>
        <label>Ship Complete?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Shipping</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Source_Code__c</fullName>
        <description>Source code returned by promotions service</description>
        <label>Source Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AuthDownTimeUtils.cls
/*
	AuthDownTimeUtils
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Your Name   |	??/??/???	|	Created

*/

public class AuthDownTimeUtils {
	
	//Call this method to set the order for reauthorization
	public static void setOrderReAuth(OrderWizard_Wrapper wrap, String existingToken){
		wrap.newOrder.Re_Authorize__c = true;
		wrap.newOrder.Order_Status__c = 'Awaiting Authorization';
		wrap.newOrder.OwnerId = setOrderOwner('Orders - Awaiting Payment Authorization');
		if(!wrap.newOrder.Replay_Existing_CC__c){//if false this is a new card
			wrap.newOrder.Credit_Card_Expiration_Date__c = wrap.paymentInfo.expiryYYYYMM; 
			wrap.newOrder.Credit_Card_Type__c = wrap.selectedccType;
			wrap.newOrder.Credit_Card_Number__c = wrap.paymentInfo.creditCardNumber;
			wrap.newOrder.Card_Holder_Name__c = wrap.paymentInfo.nameOnCard;
			wrap.newOrder.Payment_Type__c = wrap.selectedpaymentType;
			update wrap.newOrder;
		}else{//else this is an existing card
			wrap.newOrder.Credit_Card_Type__c = wrap.selectedccType;
			wrap.newOrder.Payment_Type__c = wrap.selectedpaymentType;
			wrap.newOrder.Credit_Card_Token__c = existingToken;
			update wrap.newOrder;
		}
	}
	
	public static Id setOrderOwner(String owner){
		//sets the owner id during downtime to a queue which will hold all orders awaiting payment authorization.
		QueueSobject qs = [SELECT Id, QueueId, Queue.Name, Queue.DeveloperName FROM QueueSobject WHERE Queue.Name = :owner LIMIT 1];
		return qs.QueueId;
	}
	
	//Method pulled from Order Wizard @ln192
	public static Orders__c queryOrder(Id orderId){
		// DE640 -- added Future Order flag/date fields along with gift order
		Orders__c orderObj = [SELECT 	customer__r.Payment_Profile_Id__c,	Tax__c,Discount__c,Catalog_Source_Code__c , Source_Code__c, Ship_To_Address__r.Zip_Code__c,
								Ship_To_Address__r.Zip_Code_4__c, Ship_To_Address__r.Foreign_Postal_Code__c,Ship_To_Address__r.Country__c, Ship_To_Address__r.City__c, 
								Ship_To_Address__r.Address_Line_3__c,Shipping_Total__c,Future_Order__c,Future_Order_Date__c,Gift_Order__c,Ship_To_Address__r.Address_Line_2__c,
								Ship_To_Address__r.Address_Line_1__c,Ship_To_Address__r.State_Providence__c,customer__r.personEmail, Order_Total__c,payment_type__c,Pull_Order__c, 
								No_Invoice__c, No_Peanuts__c, No_Catalogs__c,	No_Substitutes__c, Ship_Complete__c, customer__r.recordType.developerName,customer__r.name,
								Customer__r.Associate_Customer__c, customer__r.Associate_ID__c,promotions__r.name,promotions__r.offers__c,id,name,Order_Status__c,Sales_Channel__c, 
								Shipping_Method__c,customer__c,Bill_To_Address__c ,Ship_to_address__c,Credit_Amount_Applied__c,Credit_Applied__c,Credit_Reasons__c,
								Credit_Card_Expiration_Date__c,Credit_Card_Token__c,Pull_Order_Reason_Multi__c	,Pull_Order_Reason_Other__c,Ship_To_Last_Name__c,
								Ship_To_First_Name__c , Batch_Number__c, Batch_Sequence_Number__c, Comments__c, Replay_Existing_CC__c, Re_Authorize__c, Credit_Card_Number__c,
								Card_Holder_Name__c FROM Orders__c WHERE id =:OrderId];
		return orderObj;
	}
	
	public static Boolean checkDownTimeStatus(){
		WS_Integration__c authService = WS_Integration__c.getValues('AuthServiceAvailable');
		if(authService != null){
			system.debug('--------------------------------------------authService: ' + authService);
			return Boolean.valueOf(authService.Value__c);
		}else{
			return true;
		}
		
	}
	
	@future
	public static void checkScheduleStatus(){
		List<CronTrigger> ct = [SELECT Id, State, StartTime, OwnerId, NextFireTime, CreatedDate, CronExpression, CronJobDetailId, 
								CronJobDetail.Name, CronJobDetail.JobType FROM CronTrigger];
		for(CronTrigger x :ct){
			system.debug('--------------------------------------------CT: ' + x);
			if(x.State == 'DELETED'){
				system.abortJob(x.Id);
			}
		}
	}
	
	public static void checkScheduleStatus2(){
		List<CronTrigger> ct = [SELECT Id, State, StartTime, OwnerId, NextFireTime, CreatedDate, CronExpression, CronJobDetailId, 
								CronJobDetail.Name, CronJobDetail.JobType FROM CronTrigger];
		for(CronTrigger x :ct){
			system.debug('--------------------------------------------CT: ' + x);
			if(x.State == 'DELETED'){
				system.abortJob(x.Id);
			}
		}
	}
	
	
}