src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ANI__c</fullName>
        <description>ANI - Caller ID provided by CTI</description>
        <label>ANI</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Brand Name passed from Cisco via CTI</description>
        <label>Brand</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CED__c</fullName>
        <description>Customer Entered Digits from Cisco IVR</description>
        <label>CED</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CNX2__UniqueCallId__c</fullName>
        <description>UniqueCallId</description>
        <externalId>true</externalId>
        <label>UniqueCallId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DNIS__c</fullName>
        <description>DNIS - Dialed Number Information Service provided by CTI</description>
        <label>DNIS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IVR_Case__c</fullName>
        <label>IVR_Case</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IVR_Customer__c</fullName>
        <label>IVR Customer</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IVR_Order__c</fullName>
        <label>IVR Order</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IVR_Status__c</fullName>
        <description>What IVR Flow and status the caller went through prior to the call arriving in Salesforce.</description>
        <label>IVR Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Task_Record__c</fullName>
        <label>Task Record</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/CnxCustomerEnhancements.cls
global with sharing class CnxCustomerEnhancements {
	
	public static String generateJsonFailureCallLog(String result, String longResult, String description){
		JSONGenerator gen = JSON.createGenerator(true);
		gen.writeStartObject();
		gen.writeFieldName(result);
		gen.writeStartObject();
		gen.writeStringField('Title', longResult ); 
		gen.writeStringField('Text', description );
		gen.writeEndObject();          
		gen.writeEndObject();
		return gen.getAsString();
	}
	
	public static String generateJsonSuccessCallLog(){
		JSONGenerator gen = JSON.createGenerator(true);
		gen.writeStartObject();
		gen.writeStringField('result', '');
		gen.writeEndObject();
		return gen.getAsString();
	}
	
	webservice static String updateCallLog( String sfdcId, String callObject){
		try {
			system.debug('---------------------------------callObject: ' + callObject);
			
/****************************Transformation logic for url encoded strings**********************************************/
			if(!callObject.startsWith('{')){
				callObject = encodingUtil.urlDecode(callObject, 'UTF-8');
				callObject = callObject.removeStart('callObject=');
				system.debug('----------------------------callObject Post transformation: ' + callObject);
			}
/*******************************************End transformation*********************************************************/
			
			JSONParser parser = JSON.createParser(callObject);
			String uniqueId;
			String id;
			String dnis; //DNIS__c
			String sender; //ANI__c
			String callType;
			String perVar1 = ''; //Customer
			String perVar2 = ''; //Order
			String perVar3 = ''; //Case
			String perVar4 = ''; //Brand
			String perVar5 = ''; //IVR Status
			String perVar6 = ''; //CED
			String perVar7 = ''; //QueueName
			String perVar8 = '';
			String perVar9 = '';
			String perVar10 = '';
			while (parser.nextToken() != null) {
				system.debug('------------------------------------getCurrentToken: ' + parser.getCurrentToken());
				if (parser.getCurrentToken() == JSONToken.FIELD_NAME){
					String fieldName = parser.getText();
					system.debug('------------------------------------fieldName: ' + fieldName);
					// Get the value.
					parser.nextToken();
					system.debug('------------------------------------getText: ' + parser.getText());
					if(fieldName == 'UniqueId'){
						uniqueId = parser.getText();
					}else if(fieldName == 'DNIS'){
						dnis = parser.getText();
					}else if(fieldName == 'Sender'){
						sender = parser.getText();
					}else if(fieldName == 'PerVar1'){
						perVar1 = parser.getText();
					}else if(fieldName == 'PerVar2'){
						perVar2 = parser.getText();
					}else if(fieldName == 'PerVar6'){
						perVar6 = parser.getText();
					}else if(fieldName == 'PerVar4'){
						perVar4 = parser.getText();
					}else if(fieldName == 'PerVar5'){
						perVar5 = parser.getText();
					}
				}
			}
			
			system.debug('------------------------------------UniqueId: ' + uniqueId);
			system.debug('------------------------------------sender: ' + sender);
			system.debug('------------------------------------dnis: ' + dnis);
			system.debug('------------------------------------perVar1: ' + perVar1);
			system.debug('------------------------------------perVar2: ' + perVar2);
			system.debug('------------------------------------perVar3: ' + perVar3);
			system.debug('------------------------------------perVar4: ' + perVar4);
			system.debug('------------------------------------perVar5: ' + perVar5);
			system.debug('------------------------------------perVar6: ' + perVar6);
			
			Task t = [SELECT Id,ANI__c, DNIS__c, IVR_Customer__c,IVR_Order__c, Description, CED__c, Brand__c FROM Task WHERE CNX2__UniqueCallId__c = :uniqueId];
			t.ANI__c = sender;
			t.DNIS__c = dnis;
			if(perVar1 != null && perVar1 != ''){
				t.IVR_Customer__c = perVar1;
			}
			if(perVar2 != null && perVar2 != ''){
				t.IVR_Order__c = perVar2;
			}
			if(perVar3 != null && perVar3 != ''){
				t.IVR_Case__c = perVar3;
			}
			t.Brand__c = perVar4;
			if(perVar5 != null){
				t.IVR_Status__c = perVar5;
			}
			if(perVar6 != null && perVar6 != ''){
				t.CED__c = integer.valueOf(perVar6);
			}
			
			t.Description = callObject;
			update t;
			
			String userId = userInfo.getUserId();
			User c = [SELECT Id FROM User WHERE Id = :userId];
			c.Task_Record__c = t.Id;
			system.debug('-------------------------------------------User ' + c.Task_Record__c);
			update c;
			
			system.debug('-------------------------------------------User ' + c);
			
			return generateJsonSuccessCallLog();
		
		}catch(Exception e){
			return generateJsonFailureCallLog('Failure', 'Call Failure', 'Failed to create activity');
		}
	}
	
	public static String generateJsonTransfer(String result, String objectId, String objectType){
		JSONGenerator gen = JSON.createGenerator(true);
		gen.writeStartObject();
		gen.writeFieldName(result);
		gen.writeStartObject();
		gen.writeStringField('objectId', objectId  );
		gen.writeStringField('object', objectType );
		gen.writeEndObject();  
        gen.writeEndObject();
		return gen.getAsString();
	}
	
	webService static String getScreenTransferInfo(String pageInfo, String callObject){
		try{
			//parse the pageInfo Argument
			Map<String, Object> pageInfoMap = (Map<String, Object>)JSON.deserializeUntyped(EncodingUtil.urlDecode(pageInfo, 'UTF-8'));
			String objectType = (String)pageInfoMap.get('object');
			String objectId = (String)pageInfoMap.get('objectId');
			
			//parse the callObject Argument
			Map<String, Object> callObjectMap = (Map<String, Object>)JSON.deserializeUntyped(EncodingUtil.urlDecode(callObject, 'UTF-8'));
			String sender = (String)callObjectMap .get('Sender');
			
			return generateJsonTransfer('result', objectId, objectType);
		}catch(Exception e){
			return generateJsonTransfer('error', 'Transfer Error', 'Unable to Transfer Screen');
		}
	}
	
	
	
	
}