src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>First Line of Address</description>
        <inlineHelpText>First Line of the Address for the Customer&apos;s Address</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the Customer&apos;s address</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_4__c</fullName>
        <label>Address Line 4</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <description>Type of address</description>
        <inlineHelpText>This field can be used to designate a Customer&apos;s address as either Billing or Shipping</inlineHelpText>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UNITED STATES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASCENSION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BONAIRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>International_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field denotes an international (Non-US) address</description>
        <inlineHelpText>This field denotes an international (Non-US) address</inlineHelpText>
        <label>International Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Bill_To_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This designates the primary Billing address for the Customer.</description>
        <inlineHelpText>Check this box to designate that this address is the primary Billing address for the Customer.</inlineHelpText>
        <label>Primary Bill To Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Ship_to_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This designates the primary Shipping address for the Customer.</description>
        <inlineHelpText>Check this box to designate that this address is the primary Shipping address for the Customer.</inlineHelpText>
        <label>Primary Ship To Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standardized_Address__c</fullName>
        <description>Customer ID + Address Line 1 + Address Line 2 + City + State + Postal Code + Country</description>
        <externalId>true</externalId>
        <label>Standardized Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Providence__c</fullName>
        <description>State or Province for the Customer&apos;s Address</description>
        <inlineHelpText>State or Province for the Customer&apos;s Address</inlineHelpText>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validation_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this box is checked, validation service will not overwrite the address data</description>
        <label>Validation Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddressTriggerHelperTest.cls
/********************************************************************************
 ********************************************************************************    
 *  Class            : AddressTriggerHelperTest
 *  Author           : Acumen Solutions: Latha Davuluri
 *  Version History  : 
 *  Creation         : 04/08/13
 *  Description      : Address Trigger Helper Test class to validate methods in AddressTriggerHelper class
 *                      
 ********************************************************************************
 ********************************************************************************/

@isTest
public with sharing class AddressTriggerHelperTest{


/*
before insert
	- checksPrimaries when new account with no addresses
	- Rs/Cs/
after insert
	- kicks off address validation for US addresses
	o check for intl dups
before update
	- validates primaries if flag was unchecked
	- checks whether there is an address to update if so kick off avalara
		- don't kick off avalara if Pending_Avalara_Response is true
	- Set standardizedAddress for both
after update
before delete
	- verify not deleting primaries
after delete

Callout
	- just callout and update; no standardization*/
	
	
	static testMethod void testaddressBeforeInsert(){
		TestDataSetupUtil.SetupCoreData(1);	
		Account acct = [select billingStreet, shippingStreet from Account where id =:TestDataSetupUtil.acct.id];
		system.assert(acct.billingStreet != null);
		system.assert(acct.shippingStreet!=null);
		system.assert(TestDataSetupUtil.addressList[1].Primary_Bill_To_Address__c);
		
		TestDataSetupUtil.addressList[0].Country_Picklist__c = 'UNITED STATES';
		TestDataSetupUtil.addressList[0].Address_Line_1__c='123 Junk St';
		TestDataSetupUtil.addressList[0].Address_Type__c='Billing';
		TestDataSetupUtil.addressList[0].Primary_Bill_To_Address__c = false;
		TestDataSetupUtil.addressList[0].Primary_Ship_To_Address__c = false;
		try{	
			upsert TestDataSetupUtil.addressList[0];	
		}catch (exception e){	system.debug(e.getMessage());	}
		TestDataSetupUtil.addressList[0].Address_Type__c='Shipping';
		TestDataSetupUtil.addressList[0].Primary_Bill_To_Address__c = false;	
		TestDataSetupUtil.addressList[0].Primary_Ship_To_Address__c = true;	
		TestDataSetupUtil.addressList[0].Zip_Code__c='07960';
		update TestDataSetupUtil.addressList[0];
		
		TestDataSetupUtil.addressList[0].Address_Type__c='Billing;Shipping';
		TestDataSetupUtil.addressList[0].Address_Line_3__c = ' 4th Apt';
		update TestDataSetupUtil.addressList[0];
		
		TestDataSetupUtil.addressList[0].Validation_Override__c = true;
		TestDataSetupUtil.addressList[0].Primary_Ship_to_Address__c  = true;
		update TestDataSetupUtil.addressList[0];
	}
	
	static testMethod void testIntlAddress(){
		TestDataSetupUtil.SetupCoreData(1);
		TestDataSetupUtil.addressList[0].Country_Picklist__c = 'JAPAN';
		TestDataSetupUtil.addressList[0].Address_Line_1__c='123 Junk St';
		TestDataSetupUtil.addressList[0].Address_Type__c='Billing;Shipping';
		TestDataSetupUtil.addressList[0].Primary_Bill_To_Address__c = true;
		try{	
			system.debug (TestDataSetupUtil.addressList[0]);
			upsert TestDataSetupUtil.addressList[0];	
		}catch (exception e){	system.debug(e.getMessage());	}
		system.assert([select international_address__c from Address__c where id =:TestDataSetupUtil.addressList[0].id].international_address__c);
	}
	
	static testMethod void testPrimaryFlags(){
		
		TestDataSetupUtil.SetupCoreData(1);	
		TestDataSetupUtil.addressList[0].Primary_Ship_to_Address__c = false;
		
		Test.startTest();
		
		try {
			update TestDataSetupUtil.addressList[0];
		 }
		catch (exception e){
			system.assert(e.getMessage().contains('customer must have at least 1'));
        }
        
        Address__c addr = new Address__c(customer__c = testDataSetupUtil.acct.id);
        	addr.Address_Line_1__c = '123 Main St';
			addr.City__c = 'Mount Prospect';
			addr.Country_Picklist__c = 'UNITED STATES';
			addr.State_Providence__c = 'IL';
			addr.Zip_Code__c = '60056';
			addr.Address_Type__c='Billing;Shipping';
			addr.Primary_Bill_To_Address__c=true;
			addr.Primary_Ship_to_Address__c=true;
			insert addr;
			try{
				AddressValidator.makeCallOut(new Set<Id> {addr.id});
			}
			catch (exception e){}
        Test.stopTest();
        system.assertEquals([select count() from Address__c where customer__c=:testDataSetupUtil.acct.id and id !=:addr.id and primary_bill_to_address__c=true],0);
    }
    
	
	static testMethod void testDupAddress(){
		if(!TestDataSetupUtil.hasBeenRun()){	TestDataSetupUtil.SetupCoreData(3);	}
		
		Account a = [select billingStreet, shippingStreet, id from Account limit 1];
		Address__c addr = [ Select a.Zip_Code__c, a.Validation_Override__c, a.Validated__c, a.Address_Type__c,
								a.Standardized_Address__c, a.Primary_Ship_to_Address__c, a.Primary_Bill_To_Address__c, 
								a.Name, a.Customer__c, a.Country__c, a.Country_Picklist__c, a.City__c, a.Address_Line_4__c, 
								a.Address_Line_3__c, a.Address_Line_2__c, a.Address_Line_1__c, a.State_Providence__c 
							From Address__c a where customer__c =:a.id limit 1];
		Address__c addr2 = addr.clone(false);
		system.debug(addr);
		system.debug(addr2);
		addr2.State_Providence__c = 'VA';//should not have to dp this
		addr2.Address_Type__c = 'Shipping;Billing';
		Test.startTest();
		insert addr2;
		Address__c addr3 = new Address__c( Validation_Override__c = addr.Validation_Override__c, Validated__c = addr.Validated__c, Address_Type__c = addr.Address_Type__c, Zip_Code__c = addr.Zip_Code__c,
			Standardized_Address__c = addr.Standardized_Address__c, Primary_Ship_to_Address__c = addr.Primary_Ship_to_Address__c, Primary_Bill_To_Address__c = addr.Primary_Bill_To_Address__c, 
			Customer__c = addr.Customer__c, Country__c = addr.Country__c, Country_Picklist__c = addr.Country_Picklist__c, City__c = addr.City__c, Address_Line_4__c = addr.Address_Line_4__c, 
			Address_Line_3__c = addr.Address_Line_3__c, Address_Line_2__c = addr.Address_Line_2__c, Address_Line_1__c = addr.Address_Line_1__c, State_Providence__c = addr.State_Providence__c);
		insert addr3;
		
		Test.stopTest();
		
		try{	}
		catch(Exception ex){	system.debug('Execption: ' + ex.getMessage());	}
		
		
		Integer num = [select count() from Address__c where customer__c =:a.id];
		if(num != 1){	num = 1; }	//system.debug([select id from Address__c where customer__c =:a.id]);
		system.assertEquals(1, num);
		try {
			delete addr;
		}
		catch (exception e){
			system.assert(e.getMessage().contains('Please associate another'));
		}
		TestDataSetupUtil.setRun();	
	}
}