src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>First Line of Address</description>
        <inlineHelpText>First Line of the Address for the Customer&apos;s Address</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <description>Type of address</description>
        <inlineHelpText>This field can be used to designate a Customer&apos;s address as either Billing or Shipping</inlineHelpText>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Bill_To_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This designates the primary Billing address for the Customer.</description>
        <inlineHelpText>Check this box to designate that this address is the primary Billing address for the Customer.</inlineHelpText>
        <label>Primary Bill To Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Ship_to_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This designates the primary Shipping address for the Customer.</description>
        <inlineHelpText>Check this box to designate that this address is the primary Shipping address for the Customer.</inlineHelpText>
        <label>Primary Ship To Address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Providence__c</fullName>
        <description>State or Province for the Customer&apos;s Address</description>
        <inlineHelpText>State or Province for the Customer&apos;s Address</inlineHelpText>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountSyncAddresses_Helper.cls
public with sharing class AccountSyncAddresses_Helper {

	public static boolean bAddressBatch = false; 
	public static Address__c generateAddressRecord(Account a, boolean isShipping, boolean isBilling, boolean isPrimary){
		Address__c newAddress = new Address__c(Customer__c=a.id, Active__c=true);
		if (isShipping&&isBilling){
			 newAddress.Address_Type__c='Shipping; Billing';
		}
		else if (isShipping){
			newAddress.Address_Type__c='Shipping'; 
		}
		else {
			newAddress.Address_Type__c='Billing';
		}
		if(isShipping){
			 if (isPrimary) newAddress.Primary_Ship_to_Address__c=true;
			 newAddress.Address_Line_1__c=a.shippingStreet;
			newAddress.City__c=a.shippingCity;
			newAddress.Country__c=a.shippingCountry;
			newAddress.State_Providence__c=a.shippingState;
			newAddress.Zip_Code__c=a.shippingPostalCode;
		}
		if (isBilling){
			 if (isPrimary) newAddress.Primary_Bill_to_Address__c=true;
			newAddress.Address_Line_1__c=a.BillingStreet;
			newAddress.City__c=a.BillingCity;
			newAddress.Country__c=a.BillingCountry;
			newAddress.State_Providence__c=a.BillingState;
			newAddress.Zip_Code__c=a.BillingPostalCode;
		}
		return newAddress;
	}
}