src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Webstack_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Webstack Order ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Summary</label>
    <nameField>
        <displayFormat>OS-{000000}</displayFormat>
        <label>Order Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders (Bill To Address)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Webstack_Order_ID__c</fullName>
        <label>Webstack Order ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderSummaryTriggerTest.cls
/************************************* MODIFICATION LOG ********************************************************************************
*
* DESCRIPTION : OrderSummaryTriggerTest is a test class for OrderSummaryTrigger
*
*---------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER						DATE				  REASON
*---------------------------------------------------------------------------------------------------------------------------------------
* Shivkant Vadlamani			04/15/2013			- Origininal Version
*
*													 
*/

@isTest
global class OrderSummaryTriggerTest 
{
	static testMethod void testOrderSummaryTrigger()
	{
		testDataSetupUtil.SetupCoreData(2);
		OrderSummaryTriggerHelperTest.setupInboundOrderMapping();
		OrderSummaryTriggerHelperTest.setupWebStoresData();
		Order_Summary__c OSRec = OrderSummaryTriggerHelperTest.setupOrderSummary();
		
		
		Orders__c OrdGenerated = [SELECT Id, Webstack_Order_ID__c, Customer__c, (Select Id From Order_Line_Items__r), Bill_To_Address__c, Ship_To_Address__c FROM Orders__c WHERE Webstack_Order_ID__c = :OSRec.Webstack_Order_ID__c];

		List<Address__c> AddressList = [SELECT City__c, Zip_Code__c FROM Address__c WHERE Id = :OrdGenerated.Bill_To_Address__c OR Id = :OrdGenerated.Ship_To_Address__c ];
		
		System.assert( OrdGenerated.Id != null , 'This is a valid Order record');
		System.assert(OrdGenerated.Order_Line_Items__r.size() == 2, 'There should be 2 Order line items');				
		System.assert( OrdGenerated.Bill_To_Address__c != null , 'This is NOT a valid Billing Address');
		System.assert( OrdGenerated.Ship_To_Address__c != null , 'This is NOT a valid Shipping Address');	
		
		if(AddressList[0].Id == OrdGenerated.Bill_To_Address__c)
		{
			System.assert( AddressList[0].City__c == 'RAPPERSWIL' , 'This is NOT the correct City of Billing Address');	
		}
		
		if(AddressList[0].Id == OrdGenerated.Ship_To_Address__c)
		{
			System.assert( AddressList[0].City__c == 'NORTH PORT' , 'This is NOT the correct City of Shipping Address');	
		}
	}
}