src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pending_Avalara_Response__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Pending Avalara Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validation_Error_Reason__c</fullName>
        <description>Stores validation error description from Avalara Address Validation service.</description>
        <label>Validation Error Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validation_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this box is checked, validation service will not overwrite the address data</description>
        <label>Validation Override</label>
        <type>Checkbox</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddressValidationBatchProcess.cls
/********************************************************************************
 ********************************************************************************	
 *	Class			: AddressValidationBatchProcess
 *	Author			: Acumen Solutions: Latha Davuluri
 *	Version History	: 
 *	Creation		 : 04/29/13
 *	Description		: Batch process to validate address whose Pending_Avalara_Response__c = true.
 *						
 ********************************************************************************
 ********************************************************************************/

global class AddressValidationBatchProcess implements Database.Batchable<sobject>,Database.AllowsCallouts,Database.Stateful
{
	
	//constructor
	global AddressValidationBatchProcess(){ }
		
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		List<String> countryList = new List<String> {'US','USA','UNITED STATES','UNITES STATES OF AMERICA','CANADA','CA',''};
		string Query = 'Select Id from Address__c Where Pending_Avalara_Response__c=true and Validated__c=false and Validation_Error_Reason__c=null and Validation_Override__c=false and Country__c in :countryList';
		
		return Database.getQueryLocator(Query);
	}

	global void execute(Database.BatchableContext BC, sobject[] scope)
	{
		Set<Id> adrToVal = new Set<Id>();
		for(Sobject s : scope)
		{
			Address__c a = (Address__c)s;
			adrToVal.add(a.Id);
		}
		
		if (!adrToVal.isEmpty()){
			try{
				AddressTriggerHelper.callAddressValidate(adrToVal,false); //Synchronous call out for Avalara WS
			}
			catch(Exception e){
				system.debug('**Error in Batch job :'+ e.getMessage());
			}
		}
	 }

	global void finish(Database.BatchableContext BC)
	{
		BatchUtilities.batchEmailSuccess(BC, 'AddressValidationBatch');
	}
	
	
}