src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <description>First Line of Address</description>
        <inlineHelpText>First Line of the Address for the Customer&apos;s Address</inlineHelpText>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <description>The second line of the Customer&apos;s address</description>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pending_Avalara_Response__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Pending Avalara Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Providence__c</fullName>
        <description>State or Province for the Customer&apos;s Address</description>
        <inlineHelpText>State or Province for the Customer&apos;s Address</inlineHelpText>
        <label>State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Validated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Validated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Validation_Error_Reason__c</fullName>
        <description>Stores validation error description from Avalara Address Validation service.</description>
        <label>Validation Error Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code_4__c</fullName>
        <label>Zip Code 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting for all Web Service Integration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value Associated for the Name</description>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>WS_Integration</label>
</CustomObject>

src/classes/AddressValidator.cls
/********************************************************************************
 ********************************************************************************	
 *	Class			: AddressValidator
 *	Author			: Acumen Solutions: Latha Davuluri
 *	Version History	: 
 *	Creation		 : 04/09/13
 *	Description		: Class uses the Future method to validate Address records Inserted/Updated against Avalara Address Service.
 *						
 ********************************************************************************
 * Acumen Solutions: Latha Davuluri		05/20/2013		- Modified makeCallOut() method to validate single/list of Address(es).													
 ********************************************************************************/

global class AddressValidator {
	
	public static boolean Pending_Avalara_Response = false;
	public static string StandardizedAddr = null;
	public static boolean addressValidated = true;
	
	@future(callout=true)
	public static void addressToValidate_Future(Set<Id> adrIds){
		 if (Test.isRunningTest()){
			List<Address__c> adrList = [Select Id, Customer__c,Validated__c, Address_Line_1__c,Address_Line_2__c,Address_Line_3__c,City__c,State_Providence__c,Country__c,Zip_Code__c,Pending_Avalara_Response__c	From Address__c Where Id in :adrIds]; 
				//update adrList;
		 }
		 else{
			addressToValidate(adrIds);
		 }
	}
		
	public static void addressToValidate(Set<Id> adrIds){
		 if (Test.isRunningTest()){
			List<Address__c> adrList = [Select Id, Customer__c,Validated__c, Address_Line_1__c,Address_Line_2__c,Address_Line_3__c,City__c,State_Providence__c,Country__c,Zip_Code__c,Pending_Avalara_Response__c	From Address__c Where Id in :adrIds]; 
				update adrList;
		 }
		 else{
		 	 List<Address__c> adrToUpd = new List<Address__c>();
			
			 Set <Id> chunkedIdsSet = new Set <Id>();
			 for (Id addrId: adrIds){ 
				 chunkedIdsSet.add(addrId);
				 List<Address__c> addrUpdList = new List<Address__c>();
				 if (chunkedIdsSet.size()==10)	{
						 addrUpdList = makeCallOut(chunkedIdsSet);
						 for(Address__c adr : addrUpdList){
						 	adrToUpd.add(adr);
						 }
						 chunkedIdsSet.clear();
				 }
				}
				if (!chunkedIdsSet.isEmpty()){
					 List<Address__c> addrUpdList = new List<Address__c>();
					 addrUpdList = makeCallOut(chunkedIdsSet);
					 for(Address__c adr : addrUpdList){
						adrToUpd.add(adr);
					 }
				}	
							
				try{
				 if(Pending_Avalara_Response){
					if (adrToUpd != null && adrToUpd.size()>0 ){
						update adrToUpd;
					 }
					Pending_Avalara_Response = false;
					}
				}
				catch(Exception ex){
					System.debug('**NBTY Error standardizing the address :'+ex.getMessage());
				}
		 }
		}
		
		public static List<Address__c> makeCallOut(Set<ID> adrIds){
				if(!adrIds.isEmpty()){
					List<Address__c> adrList = [Select Id, Customer__c,Validated__c, Address_Line_1__c,Address_Line_2__c,Address_Line_3__c,City__c,State_Providence__c,Country__c,Zip_Code__c,Pending_Avalara_Response__c	From Address__c Where Id in :adrIds]; 
				List<Address__c> adrToUpd = new List<Address__c>();
				 
				for(Address__c addrVal : adrList){
					Address__c addr = validateAddress(addrVal);	
					Pending_Avalara_Response = true;
					adrToUpd.add(addr);
				}// end of for
				return adrToUpd; 
				}
				return null;		
		}
		
		public static Address__c validateAddress(Address__c addrVal){
			if (addrVal != null){
				AddressSvc.AddressSvcSoap addressSvc = new AddressSvc.AddressSvcSoap(WS_Integration__c.getValues('AvaTaxEndPoint').value__C);
			addressSvc.Security = NBTYAddressService.setupSecurity();
			addressSvc.Profile.Client = 'SFDemo,1,0'; 
			 
			AddressSvc.ValidateResult vres = null;
			String SampleResult;
			String PostalCode;
			String StdAddr;
			List<String> Zipcode;
				AddressSvc.ValidateRequest vreq = new AddressSvc.ValidateRequest();
				
			vreq.Address = new AddressSvc.BaseAddress();
				
			vreq.Address.Line1 = addrVal.Address_Line_1__c;
			vreq.Address.Line2 = addrVal.Address_Line_2__c;
			vreq.Address.Line3 = addrVal.Address_Line_3__c;
			vreq.Address.City = addrVal.City__c;
			vreq.Address.Country = addrVal.Country__c;
			vreq.Address.Region = addrVal.State_Providence__c;
			vreq.Address.PostalCode = addrVal.Zip_Code__c;
				 
			try{
				if(vreq != null)	vres=addressSvc.Validate(vreq);
			}
			catch(Exception ex) {
				SampleResult = 'Address Validation Excepted: ' + ex.getmessage();
			}
	
			if(vres.ResultCode == 'Success'){
				SampleResult = 'Address Validation Returned Success - Standardized Address Appears below';
					 
				addrVal.Address_Line_1__c = vres.ValidAddresses.ValidAddress[0].Line1;
				addrVal.Address_Line_2__c = vres.ValidAddresses.ValidAddress[0].Line2;
				addrVal.Address_Line_3__c = vres.ValidAddresses.ValidAddress[0].Line3;
				addrVal.City__c = vres.ValidAddresses.ValidAddress[0].City;
				addrVal.State_Providence__c = vres.ValidAddresses.ValidAddress[0].Region;
				PostalCode = vres.ValidAddresses.ValidAddress[0].PostalCode;
				if (PostalCode.contains('-')){
					Zipcode = PostalCode.trim().split('-');
					addrVal.Zip_Code__c = Zipcode[0];
					addrVal.Zip_Code_4__c = Zipcode[1];
				}
				else{
					addrVal.Zip_Code__c = vres.ValidAddresses.ValidAddress[0].PostalCode;
				}
				addrVal.Country__c = vres.ValidAddresses.ValidAddress[0].Country; 
				addrVal.Validated__c = true;
				addrVal.Validation_Error_Reason__c = null;
				addrVal.Pending_Avalara_Response__c = false;
			}
			else {
				SampleResult = 'Address Validation Returned Other Than Success: ' + vres.ResultCode + 
				' : ' + vres.Messages.Message[0].Name + ' : ' + vres.Messages.Message[0].Summary;
				system.debug(LoggingLevel.info, SampleResult);
				addrVal.Validated__c = false;
				addrVal.Validation_Error_Reason__c = vres.Messages.Message[0].Summary;
			 }
			return addrVal;
			}
			return null; 
		}
	
}