src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Country_Picklist__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>UNITED STATES</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AFGHANISTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALBANIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMERICAN SAMOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANDORRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGOLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANGUILLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANTIGUA &amp; BARBUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARMENIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARUBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASCENSION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUSTRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZERBAIJAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZORES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHAMAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAHRAIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BANGLADESH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BARBADOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELARUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELGIUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BELIZE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BENIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BERMUDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BHUTAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOLIVIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BONAIRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country for the Customer&apos;s Address</description>
        <inlineHelpText>Country for the Customer&apos;s Address</inlineHelpText>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item_Restriction__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Restrictions</relationshipLabel>
        <relationshipName>Item_Restrictions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Restriction_Text__c</fullName>
        <label>Restriction Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item Restriction</label>
    <nameField>
        <displayFormat>IR-{00000}</displayFormat>
        <label>Item Restriction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Restrictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Name</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderLineItemTriggerHelperTest.cls
@isTest
public class OrderLineItemTriggerHelperTest {
	
	static testMethod void testOliTrigger(){
		test.startTest();
		testDataSetupUtil.SetupCoreData(2);
		Order_Line_Items__c testOli = [select name, order__r.name, line_number__c from order_line_items__c where order__c=:testDataSetupUtil.order1.id and line_number__c='1' limit 1];
		system.debug('testOli~~~'+testOli);
		Order_Line_Items__c testOli2 = [select id, name, order__r.name, line_number__c from order_line_items__c where order__c=:testDataSetupUtil.order1.id and line_number__c='2' limit 1];
		system.assertEquals(testOli.name,testOli.order__r.name+'-1');
		delete testOli;
			 testOli2 = [select name, order__r.name, line_number__c from order_line_items__c where id=:testOli2.id limit 1];
		system.assertEquals(testOli2.line_number__c,'1');
		
		
	}
	
	static testMethod void testRestrictedItems(){
		testDataSetupUtil.SetupCoreData(2);
		
		Orders__c testOrd = [select id, ship_to_address__c from Orders__c where id =:testDataSetupUtil.order1.id];
		Order_Line_Items__c testOli = [select id, product_name__c from order_line_items__c where order__c=:testDataSetupUtil.order1.id and line_number__c='1' limit 1];
		Item_Restriction__c itemr = new Item_Restriction__c(item__c=testOli.product_name__c, Restriction_Text__c='This item cannot be shipped to Japan.');
		insert itemr;
		system.debug('itemr~~~~'+itemr);
		Address__c addr = new Address__c(id=testOrd.ship_to_address__c,Country__c='JP', Country_Picklist__c='JAPAN');
		update addr;
		Order_Line_Items__c oli = new Order_Line_Items__c(product_Name__c=testOli.product_name__c, order__c=testOrd.id);
		boolean bFailed = false;
		test.startTest();
		try {
			insert oli;
					system.debug('oli~~~~'+oli);
		}
		catch (exception e){
			bFailed = true;
		}
		test.stopTest();
		system.assert(bFailed);
	}
	
	static testMethod void testSetShipComplete(){
		TestDataSetupUtil.SetupCoreData(3);
		
		List<Order_Line_Items__c> oli = TestDataSetupUtil.oliList;
		List<Order_Line_Items__c> empty = new List<Order_Line_Items__c>();
		List<Orders__c> emptyOrders = new List<Orders__c>();
		List<Orders__c> orders = new List<Orders__c>();
		orders.add(TestDataSetupUtil.order1);
		Test.startTest();
		
		OrderLineItemTriggerHelper.setShipCompleteStatus(oli, emptyOrders);
		OrderLineItemTriggerHelper.setShipCompleteStatus(empty, orders);
		
		Test.stopTest();
	}
}