src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>City for the Customer&apos;s Address</description>
        <inlineHelpText>City for the Customer&apos;s Address</inlineHelpText>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code for the Customer&apos;s Address</description>
        <inlineHelpText>Zip Code for the Customer&apos;s Address</inlineHelpText>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country_Code_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Keyboard_Translation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>There COULD be a keyboard translation error with these countries, if bill to is this country set Order to Internal review for web orders</description>
        <label>Keyboard Translation</label>
        <type>Checkbox</type>
    </fields>
    <label>Country Code Mapping</label>
</CustomObject>

src/objects/Inbound_Order_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Position__c</fullName>
        <label>End Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Position__c</fullName>
        <label>Start Position</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Inbound Order Mapping</label>
</CustomObject>

src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Allowance_Charge__c</fullName>
        <label>Allowance Charge</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Done__c</fullName>
        <label>Done</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Header__c</fullName>
        <label>Header</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Misc_Charge__c</fullName>
        <label>Miscellaneous Charges</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ship_To__c</fullName>
        <label>Ship To</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Webstack_ID__c</fullName>
        <label>Webstack ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_Order_ID__c</fullName>
        <externalId>true</externalId>
        <label>Webstack Order ID</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Summary</label>
    <nameField>
        <displayFormat>OS-{000000}</displayFormat>
        <label>Order Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders (Bill To Address)</relationshipLabel>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ship_To_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Address</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Webstack_ID__c</fullName>
        <label>Webstack ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_Order_ID__c</fullName>
        <label>Webstack Order ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WebStoresData__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Suffix__c</fullName>
        <label>Product Suffix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Web Stores Data</label>
</CustomObject>

src/objects/WS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting for all Web Service Integration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value Associated for the Name</description>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>WS_Integration</label>
</CustomObject>

src/classes/OrderSummaryTriggerHelperTest.cls
/************************************* MODIFICATION LOG ********************************************************************************
*
* DESCRIPTION : OrderSummaryTriggerHelperTest is a test class for OrderSummaryTriggerHelper
*
*---------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER						DATE				  REASON
*---------------------------------------------------------------------------------------------------------------------------------------
* Shivkant Vadlamani			04/15/2013			- Origininal Version
*
*													 
*/

@isTest
	//public static Order_Summary__c OSRec;
global class OrderSummaryTriggerHelperTest 
{
	static testMethod void testOrderSummaryKeyboardTranslation(){
		testDataSetupUtil.SetupCoreData(2);
		country_code_mapping__c ccm = country_Code_mapping__c.getValues('00135');//thailand
		ccm.keyboard_translation__c= true;
		update ccm;
		setupInboundOrderMapping();
		setupWebStoresData();
		test.startTest();
		Order_Summary__c os =setupOrderSummary_KeyboardTranslation();
		test.stopTest();
		system.assertEquals('Internal Review', [select order_status__c from Orders__c where webstack_order_id__c = :os.Webstack_Order_ID__c].order_status__c);
	}
	static testMethod void testOrderSummaryTriggerHelper() {
		testDataSetupUtil.SetupCoreData(2);
		WS_Integration__c turnOffBadCust = new WS_Integration__c();
		turnOffBadCust.Name = 'BadCustOff';
		turnOffBadCust.Value__c = 'true';
		insert turnOffBadCust;
		setupInboundOrderMapping();
		setupWebStoresData();
		List<Order_Summary__c> NewOrderSummaryRecords = new List<Order_Summary__c>();
		NewOrderSummaryRecords.add(setupOrderSummary());
		OrderSummaryTriggerHelper.ProcessOrderSummaryAfterInsert(NewOrderSummaryRecords);	
		Orders__c OrdGenerated = [SELECT Id, Webstack_Order_ID__c, Customer__c, 
									(Select Id From Order_Line_Items__r), Bill_To_Address__c, Ship_To_Address__c 
									FROM Orders__c 
									WHERE Webstack_Order_ID__c = :NewOrderSummaryRecords[0].Webstack_Order_ID__c limit 1];
		List<Address__c> AddressList = [SELECT City__c, Zip_Code__c 
										FROM Address__c 
										WHERE Id = :OrdGenerated.Bill_To_Address__c 
										OR Id = :OrdGenerated.Ship_To_Address__c ];
		test.startTest();
		System.assert( OrdGenerated.Id != null , 'This is a valid Order record');
		System.assert(OrdGenerated.Order_Line_Items__r.size() == 2, 'There should be 2 Order line items');
		System.assert( OrdGenerated.Bill_To_Address__c != null , 'This is NOT a valid Billing Address');
		System.assert( OrdGenerated.Ship_To_Address__c != null , 'This is NOT a valid Shipping Address');
		
		if (AddressList[0].Id == OrdGenerated.Bill_To_Address__c) {
			System.assert( AddressList[0].City__c == 'RAPPERSWIL' , 'This is NOT the correct City of Billing Address');	
		}
		
		if (AddressList[0].Id == OrdGenerated.Ship_To_Address__c) {
			System.assert( AddressList[0].City__c == 'NORTH PORT' , 'This is NOT the correct City of Shipping Address');
		}
		setupOrderSummary_SameCust();
		test.stopTest();
	}

		public static Order_Summary__c setupOrderSummary() {
		
		system.debug('setupOrderSummary()');
		Order_Summary__c OSRec1 = new Order_Summary__c();
		OSRec1.Allowance_Charge__c = 'A004888888800040690000495';
		OSRec1.Comment__c = 'C004888888800040enjoy your gifts bro';
		OSRec1.Detail__c = 'D004888888800030547900002000119900000000000000009990|#|D004888888800040276700001000089900000000000000009991';
		OSRec1.Done__c = '';
		OSRec1.Header__c = 'H0048888888000100000000000TIPPMSB V+++++++++++++++++0513MRSANDREA      FUST           HERRENBERG                    39                            RAPPERSWIL             FO000000000000000ARYThis is the reason for suspe  WEB SITE  S00000000000000000000                          00132                              0041555340227';
		OSRec1.Misc_Charge__c = 'M004888888800050800003201';
		OSRec1.Payment__c = 'P00488888880001139a6e574-5613-4a9d-8c72-bc5a8f367412042225                                  515310DBF8682FA1801828F9131D46EE266E53C30                                       0000156932013-03-27T11:31:39';
		OSRec1.Ship_To__c = 'S004888888800020MRSBONITA      GOLDMAN                                      PO BOX 7042                   NORTH PORT             FL34290ALIVEINTHEVI@HOTMAIL.COM                          495004    00031Control Room 119001           2222yabcdefghijklmnopqrs';
		OSRec1.Webstack_ID__c = '1';
		OSRec1.Webstack_Order_ID__c = '48888888';
		insert OSRec1;
		system.debug('Order_Summary__c: '+ OSRec1);
		return OSRec1;
	}
	
	public static Order_Summary__c setupOrderSummary_SameCust() {
		system.debug('setupOrderSummary()');
		Order_Summary__c OSRec1 = new Order_Summary__c();
		OSRec1.Allowance_Charge__c = 'A004888888900040690000495';
		OSRec1.Comment__c = 'C004888888900040enjoy your gifts bro';
		OSRec1.Detail__c = 'D004888888900030547900002000119900000000000000009990|#|D004888888900040276700001000089900000000000000009991';
		OSRec1.Done__c = '';
		OSRec1.Header__c = 'H0048888889000100000000000TIPPMSB V+++++++++++++++++0513MRSANDREA      FUST           HERRENBERG                    39                            RAPPERSWIL             FO000000000000000ARYThis is the reason for suspe  WEB SITE  S00000000000000000000                          00132                              0041555340227';
		OSRec1.Misc_Charge__c = 'M004888888900050800003201';
		OSRec1.Payment__c = 'P00488888890001139a6e574-5613-4a9d-8c72-bc5a8f367412042225                                  515310DBF8682FA1801828F9131D46EE266E53C30                                       0000156932013-03-27T11:31:39';
		OSRec1.Ship_To__c = 'S004888888900020MRSBONITA      GOLDMAN                                      PO BOX 7042                   NORTH PORT             FL34290ALIVEINTHEVI@HOTMAIL.COM                          495004    00031Control Room 119001           2222yabcdefghijklmnopqrs';
		OSRec1.Webstack_ID__c = '1';
		OSRec1.Webstack_Order_ID__c = '48888889';
		insert OSRec1;
		system.debug('Order_Summary__c: '+ OSRec1);
		return OSRec1;
	}
	
	public static Order_Summary__c setupOrderSummary_KeyboardTranslation(){
		
		system.debug('setupOrderSummary()');
		Order_Summary__c OSRec1 = new Order_Summary__c();

		OSRec1.Detail__c = 'D006007060600030547900002000119900000000000000009990|#|D006007060600040276700001000089900000000000000009991';
		OSRec1.Done__c = '';
		OSRec1.Header__c = 'H0060070606000100000000000131520C V+++++++++++++++++0316MR OPAS        JINTAKAWEEWAT  1780 FLOOR 8 GUARDFIRE        THB BUILDING BANGNATRAD RD.   BANGKOK                FO000000000000000A N                              WEB SITE  S00000000000000000000                10260     00135                              6627467030          6627467031';
		OSRec1.Payment__c = 'P00600706060001139a6e574-5613-4a9d-8c72-bc5a8f367412042225                                  515310DBF8682FA1801828F9131D46EE266E53C30                                       0000156932013-03-27T11:31:39';
		OSRec1.Ship_To__c = 'S006007060600020MR OPAS        JINTAKAWEEWAT  1780 FLOOR 8 GUARDFIRE        THB BUILDING BANGNATRAD RD.   BANGKOK                FO00000Opas.jin@gmail.com                                10260     00135';
		OSRec1.Webstack_ID__c = '1';
		OSRec1.Webstack_Order_ID__c = '60070606';
		insert OSRec1;
		system.debug('Order_Summary__c: '+ OSRec1);
		return OSRec1;
	}
	
	
	public static void setupInboundOrderMapping(){
		system.debug('setupInboundOrderMapping()');
		
		StaticResource sibOmapping = [Select  s.Name, s.Id, s.Body From StaticResource s where s.Name = 'inboundOrdersMapping'];

		
		Map<String, Inbound_Order_Mapping__c> iomMap = new Map <String, Inbound_Order_Mapping__c>();

		blob tempA = sibOmapping.Body;
		String messageString = tempA.toString();
		system.debug(messageString);
		
		
		String[] filelinesMessages = messageString.split('\n');
		//split up the rows
		//clear the wrapper list
		List<Inbound_Order_Mapping__c> defaultioms = new List<Inbound_Order_Mapping__c>();
		for (Integer i=1;i<filelinesMessages.size();i++){
			Inbound_Order_Mapping__c temp = new Inbound_Order_Mapping__c();
			String[] inputvalues = filelinesMessages[i].split(',');
			//split the rows by commas and populated the fields
			temp.Name = inputvalues[0];

			temp.Data_Type__c=inputValues[1];
			temp.End_Position__c=decimal.valueOf(inputValues[2]);
			temp.object_name__c=inputValues[3];
			temp.record_type__c = inputValues[4];
			temp.start_position__c = decimal.valueOf(inputValues[5]);
			temp.field_name__c = inputValues[6];
			
			
			defaultioms.add(temp);
		}
		
		system.debug('Size of InboundOrderMappings :' + defaultioms.size());
		if (!defaultioms.isEmpty()){
			try{
				insert defaultioms;
			}catch(Exception ex){	system.debug(' defaultioms: exeption: ' + ex.getMessage());	}
		}
		system.debug('Query of defaultioms: '+ [select name from Inbound_Order_Mapping__c]);
	
	}
	public static void setupWebStoresData(){
		system.debug('setupWebStoresData()');
		
		StaticResource webStoresData = [Select  s.Name, s.Id, s.Body From StaticResource s where s.Name = 'webStoresSettings'];

		
		Map<String, WebStoresData__c> webStoresMap = new Map <String, WebStoresData__c>();

		blob tempA = webStoresData.Body;
		String messageString = tempA.toString();
		system.debug(messageString);
		
		
		String[] filelinesMessages = messageString.split('\n');
		//split up the rows
		//clear the wrapper list
		List<WebStoresData__c> defaultwsData = new List<WebStoresData__c>();
		for (Integer i=1;i<filelinesMessages.size();i++){
			WebStoresData__c temp = new WebStoresData__c();
			String[] inputvalues = filelinesMessages[i].split(',');
			//split the rows by commas and populated the fields
			temp.Name = inputvalues[0];

			temp.Currency_Code__c=inputValues[2];
			temp.Description__c=inputValues[3];
			temp.record_type_Name__c = inputValues[4];
			temp.Product_Suffix__c=inputValues[5];
			
			defaultwsData.add(temp);
		}
		
		system.debug('Size of defaultwsData :' + defaultwsData.size());
		if (!defaultwsData.isEmpty()){
			try{
				insert defaultwsData;
			}catch(Exception ex){	system.debug(' defaultwsData: exeption: ' + ex.getMessage());	}
		}
		system.debug('Query of defaultioms: '+ [select name from WebStoresData__c ]);
	
	}
}