src/objects/Adverse_Event_Review__c.object
<CustomObject>
    <fields>
        <fullName>AER_Related_Case__c</fullName>
        <label>AER Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Adverse Event Reviews</relationshipLabel>
        <relationshipName>Adverse_Event_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Adverse Event Review</label>
    <nameField>
        <label>AER Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adverse Event Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Affected_Item__c.object
<CustomObject>
    <description>Child object for the case complaint object</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lot_Number_Sequence__c</fullName>
        <label>Lot Number Sequence</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NBTY_Lot__c</fullName>
        <label>NBTY Lot#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Bulk_Number__c</fullName>
        <label>Oracle Bulk Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Affected Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Affected Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affected Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CT_Category__c</fullName>
        <label>Category Complaint Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CT_Subcategory__c</fullName>
        <label>Subcategory Complaint Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complaint_Type__c</fullName>
        <label>Complaint Type</label>
        <picklist>
            <picklistValues>
                <fullName>Inquiry</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Class I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class II Non-Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class II Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class III</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Same_as_Reporter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same as Reporter?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Follow_Up</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all general follow-up cases.</description>
        <label>Follow-Up</label>
    </recordTypes>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/objects/CaseCategoryMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Category__c</fullName>
        <externalId>true</externalId>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complaint_Type__c</fullName>
        <label>Complaint Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Case Category Mapping</label>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Nutrition_Review__c.object
<CustomObject>
    <fields>
        <fullName>NR_Associated_Case__c</fullName>
        <label>NR Associated Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Nutrition Reviews</relationshipLabel>
        <relationshipName>Nutrition_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Nutrition Review</label>
    <nameField>
        <label>NR Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nutrition Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Other_Medications_OTC__c.object
<CustomObject>
    <fields>
        <fullName>OTC_Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OTC Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Other Medications/OTCs</relationshipLabel>
        <relationshipName>Other_Medications_OTCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Other Medications/OTC</label>
    <nameField>
        <label>Other Medications/OTC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Medications/OTCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Case_ICMTest.cls
@isTest
public class Case_ICMTest {
	public static Case c;
	
	public static void setupData()
	{
		c = new Case(customer__c =TestDataSetupUtil.acct.id );
		string selectedRecordType = 'Product_Complaint';
			RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
		c.RecordTypeId = rt.id;
		CaseTriggerHelper.isFromChild=true;
		c.Category__c = 'Class I Packaging;';
		c.CT_Category__c = 'Class I;';
		c.Subcategory__c = 'Class I Packaging|Broken desiccant;';
		c.CT_Subcategory__c = 'Class I;';
		insert c;
		CaseTriggerHelper.isFromChild=false;
		
		CaseCategoryMapping__c caseMapping1 = new CaseCategoryMapping__c();
		caseMapping1.Name = '1';
		caseMapping1.Complaint_Type__c = 'Class II Illness';
		caseMapping1.Category__c = 'Illness';
		caseMapping1.Subcategory__c = 'Eye Disorders';
		insert caseMapping1;
		
		CaseCategoryMapping__c caseMapping2 = new CaseCategoryMapping__c();
		caseMapping2.Name = '2';
		caseMapping2.Complaint_Type__c = 'Class I';
		caseMapping2.Category__c = 'Class I Packaging';
		caseMapping2.Subcategory__c = 'Broken desiccant';
		insert caseMapping2;
		
		CaseCategoryMapping__c caseMapping3 = new CaseCategoryMapping__c();
		caseMapping3.Name = '3';
		caseMapping3.Complaint_Type__c = 'Class II Non-Illness';
		caseMapping3.Category__c = 'Choking';
		caseMapping3.Subcategory__c = 'Choking';
		insert caseMapping3;
		
		Adverse_Event_Review__c anAdverseEventReview = new Adverse_Event_Review__c();
		anAdverseEventReview.AER_Related_Case__c = c.Id;
		insert anAdverseEventReview;
		
		Nutrition_Review__c aNutritionReview = new Nutrition_Review__c();
		aNutritionReview.NR_Associated_Case__c = c.Id;
		insert aNutritionReview;
		
		Affected_Item__c anAffectedItem = new Affected_Item__c();
		anAffectedItem.Item__c = testDataSetupUtil.itemList[0].id;
		anAffectedItem.Case__c = c.Id;
		insert anAffectedItem;
		
		Other_Medications_OTC__c anOTC = new Other_Medications_OTC__c();
		anOTC.OTC_Related_Case__c = c.Id;
		insert anOTC; 
	}
	
	public static void setupFollowUpCase()
	{
		c = new Case(customer__c =TestDataSetupUtil.acct.id );
		string selectedRecordType = 'Follow_Up';
			RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
		c.RecordTypeId = rt.id;
		insert c;
	}
/*	
	public static void initCatch()
	{
		c = new Case(customer__c =TestDataSetupUtil.acct.id );
		string selectedRecordType = 'Follow_Up';
			RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
		c.RecordTypeId = rt.id;
	}
	
	public static void initCatchElse()
	{
		c = new Case(customer__c =TestDataSetupUtil.acct.id );
		string selectedRecordType = 'Product_Complaint';
			RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
		c.RecordTypeId = rt.id;
	}
	
	static testMethod void testInitCatch()
	{
		TestDataSetupUtil.SetupCoreData(2);
		initCatch();
		ApexPages.StandardController controller = new ApexPages.StandardController(c);
		PageReference pageRef = Page.Case_ICM;
		Test.setCurrentPage(pageRef);
		 	test.startTest();
		Case_ICM icmController = new Case_ICM(controller);
		test.stopTest();
	}
	
	static testMethod void testInitElse()
	{
		TestDataSetupUtil.SetupCoreData(2);
		initCatchElse();
		ApexPages.StandardController controller = new ApexPages.StandardController(c);
		PageReference pageRef = Page.Case_ICM;
		Test.setCurrentPage(pageRef);
		 	test.startTest();
		Case_ICM icmController = new Case_ICM(controller);
		test.stopTest();
	}
*/
		static testMethod void testICMController() 
		{
	
		TestDataSetupUtil.SetupCoreData(2);
		setupData();
		ApexPages.StandardController controller = new ApexPages.StandardController(c);
		PageReference pageRef = Page.Case_ICM;
		Test.setCurrentPage(pageRef);
		test.startTest();
		Case_ICM icmController = new Case_ICM(controller);
		
			icmController.c.Complaint_Type__c = 'Inquiry';
		icmController.displayPage();
		icmController.getCorrectComplaintTypes(icmController.c.Complaint_Type__c);
		Case_ICM.getCategories(icmController.c.Complaint_Type__c);
		
		icmController.c.Complaint_Type__c = 'Class I';
		icmController.displayPage();
		icmController.getCorrectComplaintTypes(icmController.c.Complaint_Type__c);
		Case_ICM.getCategories(icmController.c.Complaint_Type__c);
		
		icmController.c.Complaint_Type__c = 'Class II Non-Illness';
		icmController.displayPage();
		icmController.getCorrectComplaintTypes(icmController.c.Complaint_Type__c);
		Case_ICM.getCategories(icmController.c.Complaint_Type__c);
		
		icmController.c.Complaint_Type__c = 'Class II Illness';
		icmController.displayPage();
		icmController.getCorrectComplaintTypes(icmController.c.Complaint_Type__c);
		Case_ICM.getCategories(icmController.c.Complaint_Type__c);
		
		icmController.c.Complaint_Type__c = 'Class III';
		icmController.displayPage();
		icmController.getCorrectComplaintTypes(icmController.c.Complaint_Type__c);
		Case_ICM.getCategories(icmController.c.Complaint_Type__c);
		
		ApexPages.currentPage().getParameters().put('category' , 'Illness');
		icmcontroller.compileSelectedCategory();
		
		Case_ICM.getSubcategories(icmController.selectedCategoryList);
		
		ApexPages.currentPage().getParameters().put('subcategory' , 'Eye Disorders');
		ApexPages.currentPage().getParameters().put('complaintType' , 'Class II Illness');
		icmController.compileSelectedSubcategory();
			
		icmController.c.Same_as_Reporter__c = true;
		icmController.getAbove();
		icmController.c.Same_as_Reporter__c = false;
		icmController.getAbove();
		
		icmController.saveICM();
		
		ApexPages.currentPage().getParameters().put('removeSubcategory' , 'Eye Disorders');
		icmController.removeSubcategory();
		
		ApexPages.currentPage().getParameters().put('removeCategory' , 'Illness');
		icmController.removeCategory();
		
		test.stopTest();
		}
	
	static testMethod void testLotNumberquery(){
		Test.setMock(WebServiceMock.class, new MockResponse_LotNumberQuery());
		TestDataSetupUtil.SetupCoreData(2);
		setupData();
		ApexPages.StandardController controller = new ApexPages.StandardController(c);
		PageReference pageRef = Page.Case_ICM;
		Test.setCurrentPage(pageRef);
		test.startTest();
		Case_ICM icmController = new Case_ICM(controller);
		icmController.affectedItemsList[0].prdDetail.item__c = testDataSetupUtil.itemList[0].id;
		icmController.affectedItemsList[0].prdDetail.NBTY_Lot__c = '12345';
		icmController.affectedItemsList[0].prdDetail.Lot_Number_Sequence__c = '12345';
		ApexPages.currentPage().getParameters().put('affectedItemIndex','0');
		icmController.lotDetail();
		system.assert(icmController.affectedItemsList[0].prdDetail.oracle_bulk_number__c!=null);
		test.stopTest();
	}
}