src/objects/Adverse_Event_Review__c.object
<CustomObject>
    <fields>
        <fullName>AER_Related_Case__c</fullName>
        <label>AER Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Adverse Event Reviews</relationshipLabel>
        <relationshipName>Adverse_Event_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Assessment_List__c</fullName>
        <label>Assessment</label>
        <picklist>
            <picklistValues>
                <fullName>Serious</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potentially Serious</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Serious</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Synced_With_PQM__c</fullName>
        <label>Synced With PQM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Adverse Event Review</label>
    <nameField>
        <label>AER Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adverse Event Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Agile_Status__c</fullName>
        <description>Response code from PQM/Agile Case Update service</description>
        <label>Agile Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>International_Complaint__c</fullName>
        <defaultValue>false</defaultValue>
        <label>International Complaint</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/classes/AERTriggerHelperTest.cls
@isTest	
public class AERTriggerHelperTest {
	
	public static Adverse_Event_Review__c aer;
	public static Case c;
	public static List<Adverse_Event_Review__c> pqmUpdate;
	
	public static void setupData()
	{
		c = new Case();
    	string selectedRecordType = 'Product_Complaint';
       	RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
    	c.RecordTypeId = rt.id;
    	c.International_Complaint__c = false;
    	CaseTriggerHelper.isFromChild=true;
		insert c;
		
		aer = new Adverse_Event_Review__c();
		aer.AER_Related_Case__c = c.Id;
		pqmUpdate = new List<Adverse_Event_Review__c>();
		pqmUpdate.add(aer);
		insert aer;
	}

	static testMethod void AERTriggerHelperTest()
	{
		
		test.startTest();
		setupData();
		aer.Synced_With_PQM__c = 'No';
		update aer;
		//delete aer;
		test.stopTest();
	}
	
	// Test the new before update seriousness items.
	static testMethod void beforeUpdate_Test(){
		test.startTest();
		setupData();
		aer.Assessment_List__c = 'Serious';
		aer.Synced_With_PQM__c = 'No';
		update aer;
		aer.Assessment_List__c = 'Potentially Serious';
		aer.Synced_With_PQM__c = 'No';
		update aer;
		aer.Assessment_List__c = 'Non-Serious';
		aer.Synced_With_PQM__c = 'No';
		update aer;
		aer.Assessment_List__c = 'N/A';
		aer.Synced_With_PQM__c = 'No';
		update aer;
		aer.Assessment_List__c = null;
		aer.Synced_With_PQM__c = 'No';
		update aer;
		test.stopTest();
	}
	
	static testMethod void beforeDelete_Test(){
		test.startTest();
		setupData();
		try {
			c.Agile_Status__c = '0';
		update c;
		} catch (NBTYException e) {
			System.debug(e);
		}
		try {
			aer.Synced_With_PQM__c = 'Yes';
			update aer;
		} catch (NBTYException e) {
			System.debug(e);
		}
		delete aer;
		test.stopTest();
	}
}