src/objects/Adverse_Event_Review__c.object
<CustomObject>
    <fields>
        <fullName>AER_Comments__c</fullName>
        <label>AER Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AER_Related_Case__c</fullName>
        <label>AER Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Adverse Event Reviews</relationshipLabel>
        <relationshipName>Adverse_Event_Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Adverse Event Review</label>
    <nameField>
        <label>AER Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adverse Event Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Affected_Item__c.object
<CustomObject>
    <description>Child object for the case complaint object</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Affected Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Affected Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affected Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CT_Category__c</fullName>
        <label>Category Complaint Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CT_Subcategory__c</fullName>
        <label>Subcategory Complaint Type</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complaint_Type__c</fullName>
        <label>Complaint Type</label>
        <picklist>
            <picklistValues>
                <fullName>Inquiry</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Class I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class II Non-Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class II Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class III</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consumer_Apt__c</fullName>
        <label>Consumer Apt</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_City__c</fullName>
        <label>Consumer City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Country__c</fullName>
        <label>Consumer Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Email__c</fullName>
        <label>Consumer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Consumer_Name__c</fullName>
        <label>Consumer Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Phone__c</fullName>
        <label>Consumer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Consumer_Response_Required__c</fullName>
        <label>Consumer Response Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consumer_Sample_Location__c</fullName>
        <label>Consumer Sample Location</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Sample_Requested__c</fullName>
        <label>Consumer Sample Requested?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consumer_Satisfied__c</fullName>
        <label>Is Consumer Satisfied?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consumer_Species__c</fullName>
        <label>Consumer Species</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_State_Picklist__c</fullName>
        <label>Consumer State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consumer_Street__c</fullName>
        <label>Consumer Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_Zip_Code__c</fullName>
        <label>Consumer Zip Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer__c</fullName>
        <label>Consumer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Apt__c</fullName>
        <label>Reporter Apt</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_City__c</fullName>
        <label>Reporter City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Country__c</fullName>
        <label>Reporter Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Email__c</fullName>
        <label>Reporter Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Reporter_Name_del__c</fullName>
        <label>Reporter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Phone__c</fullName>
        <label>Reporter Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Reporter_Relationship_to_Consumer__c</fullName>
        <description>What is the Reporter&apos;s relationship to the Consumer?</description>
        <inlineHelpText>What is the Reporter&apos;s relationship to the Consumer?</inlineHelpText>
        <label>Reporter Relationship to Consumer</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pet Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reporter_State_Picklist__c</fullName>
        <label>Reporter State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reporter_Street__c</fullName>
        <label>Reporter Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Zip_Code__c</fullName>
        <label>Reporter Zip Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter__c</fullName>
        <label>Reporter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/classes/CaseClone.cls
public with sharing class CaseClone {
	
	public Case c {get;set;}
	public Case cloneCase {get;set;}
	public Adverse_Event_Review__c cloneEventReview;
	public List<Adverse_Event_Review__c> eventReview;
	public Nutrition_Review__c cloneNutritionReview;
	public List<Nutrition_Review__c> nutritionReview;
	public Affected_Item__c cloneAffectedItem;
	public List<Affected_Item__c> affectedItems;
	public List<Affected_Item__c> cloneAffectedItemsList;
	
	public CaseClone(ApexPages.StandardController controller) 
	{
		String cId = controller.getId();
		system.debug('---------------' + cId);
		c = [Select Reporter__c, Reporter_Zip_Code__c, Reporter_Street__c, Reporter_State_Picklist__c, 
			Reporter_Relationship_to_Consumer__c, Reporter_Phone__c, Reporter_Name_del__c, Reporter_Email__c, Reporter_Country__c, Reporter_City__c, Reporter_Apt__c, 
			Consumer__c, Consumer_Zip_Code__c, Consumer_Street__c, Consumer_State_Picklist__c, Consumer_Species__c, Consumer_Satisfied__c, Consumer_Sample_Requested__c, Consumer_Sample_Location__c, Consumer_Response_Required__c, 
			Consumer_Phone__c, Consumer_Name__c, Consumer_Email__c, Consumer_Country__c, Consumer_City__c, Consumer_Apt__c, Category__c, Subcategory__c, RecordTypeId, 
			RecordType.DeveloperName, Complaint_Type__c, CT_Category__c, CT_Subcategory__c  From Case c WHERE Id = :cId];
			
		system.debug('---------------' + c);
	}

	public PageReference init()
	{
		cloneCase = c.clone(false, true, false, false);
		insert cloneCase;
		
		/*eventReview = [SELECT AER_Comments__c, AER_Related_Case__c, AER_Status__c, Assesment__c, Medwatch__c, Prosar_Case__c, Reviewer__c 
			FROM Adverse_Event_Review__c WHERE AER_Related_Case__c =: c.Id LIMIT 1];
			
		if(eventReview.size() == 0){
			eventReview = new List<Adverse_Event_Review__c>();
		}else{
			for(Adverse_Event_Review__c aReview : eventReview){
				cloneEventReview = aReview.clone(false, true, false, false);
			}	
			cloneEventReview.AER_Related_Case__c = cloneCase.Id;
			insert cloneEventReview;		
		}	
		
		nutritionReview = [SELECT NR_Associated_Case__c, NR_Comments__c, NR_Number__c, NR_Reviewer__c, NR_Status__c, NR_Summary__c 
			FROM Nutrition_Review__c WHERE NR_Associated_Case__c =: c.Id LIMIT 1];
		
		if(nutritionReview.size() == 0){
			nutritionReview = new List<Nutrition_Review__c>();
		}else{
			for(Nutrition_Review__c aReview : nutritionReview){
				cloneNutritionReview = aReview.clone(false, true, false, false);
			}
			cloneNutritionReview.NR_Associated_Case__c = cloneCase.Id;
			insert cloneNutritionReview;			
		}
		
		
		affectedItems = [SELECT Brand__c, Case__c, Expiration_Date__c, Formula_Revision__c, Item_Number__c, Label_Revision_Code__c, Manufacturing_Site__c, NBTY_Lot__c,
			Oracle_Bulk_Number__c, Oracle_Product_Number__c, Packaging_Site__c, Vendor_Lot__c FROM Affected_Item__c WHERE Case__c =: c.Id];
		
		if(affectedItems.size() == 0){
			affectedItems = new List<Affected_Item__c>();
		}else{
			for(Affected_Item__c anAffectedItem : affectedItems){
				cloneAffectedItem = anAffectedItem.clone(false, true, false, false);
				cloneAffectedItem.Case__c = cloneCase.Id;
				cloneAffectedItemsList.add(cloneAffectedItem);
			}
			insert cloneAffectedItemsList;			
		}*/

		string redirectStr;
		if(c.RecordType.DeveloperName == 'Product_Complaint'){
			redirectStr = '/apex/Case_ICM?retURL=%2F' + cloneCase.Id + '&id=' + cloneCase.Id;
		}else{
			redirectStr = '/'+cloneCase.id + '/e?retURL=%2F' + cloneCase.id + '&nooverride=1';
		}
		PageReference pageRef = new PageReference(redirectStr);
		pageRef.setRedirect(true);
		return pageRef;
	}
}