src/objects/Affected_Item__c.object
<CustomObject>
    <description>Child object for the case complaint object</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Synced_With_PQM__c</fullName>
        <label>Synced With PQM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Affected Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Affected Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affected Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Agile_Status__c</fullName>
        <description>Response code from PQM/Agile Case Update service</description>
        <label>Agile Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/AffectedItemTriggerHelper.cls
public with sharing class AffectedItemTriggerHelper {
	
	public static void BeforeDelete(List<Affected_Item__c> triggerNew)
	{
	
		List<String> affectedItemsRelatedCases = New List<String>();
		
		system.debug('+++++++++++' + triggerNew);
		for(Affected_Item__c aRelatedId : triggerNew)
		{
			affectedItemsRelatedCases.add(aRelatedId.Case__c);
		}
		
		List<Case> parentCases = [SELECT Id, Agile_Status__c FROM Case WHERE Id IN :affectedItemsRelatedCases];
		
		for(Case aParent : parentCases)
		{
			if(aParent.Agile_Status__c == '0')
			{
				aParent.addError('The Nutrition Review attched to the parent case ' + aParent.Id + ' is unable to be deleted because the record was already synced with PQM');
			}
		}
		
		for(Affected_Item__c aReview : triggerNew)
		{
			if(aReview.Synced_With_PQM__c == 'Yes')
			{
				aReview.addError('The Nutrition Review ' + aReview.Name + ' is synced with PQM and cannot be deleted.');
			}
		}
	}

}