src/objects/Affected_Item__c.object
<CustomObject>
    <description>Child object for the case complaint object</description>
    <fields>
        <fullName>Bulk_Description__c</fullName>
        <label>Bulk Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bulk_Number__c</fullName>
        <label>Bulk Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formula_Revision__c</fullName>
        <label>Formula Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Label_Number__c</fullName>
        <description>Label # from Lot Query Response</description>
        <label>Label Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label_Revision_Code__c</fullName>
        <label>Label Revision Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lot_Number_Sequence__c</fullName>
        <label>Lot Number Sequence</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Site__c</fullName>
        <label>Manufacturing Site</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NBTY_Lot__c</fullName>
        <label>NBTY Lot#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Bulk_Number__c</fullName>
        <label>Oracle Bulk Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Product_Number__c</fullName>
        <label>Oracle Product Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packaging_Site__c</fullName>
        <label>Packaging Site</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Suffix__c</fullName>
        <label>Product Suffix</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Lot__c</fullName>
        <label>Vendor Lot#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sku__c</fullName>
        <label>sku</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Affected Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Affected Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affected Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Bulk_Number__c</fullName>
        <label>Bulk Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Item Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Suffix__c</fullName>
        <description>0011 - PP 0070 VB</description>
        <label>Item Suffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ws_Soa_LotNumberQueryUtils.cls
public with sharing class ws_Soa_LotNumberQueryUtils {
	
	public static ws_Soa_LotNumberQuery.LotNumberQueryRequest_element initRequest( Case_ICM.AffectedItem ai)
	{
		ws_Soa_LotNumberQuery.LotNumberQueryRequest_element lnRequest = new ws_Soa_LotNumberQuery.LotNumberQueryRequest_element();
	
		Item__c selectedProduct;
		try {
			selectedProduct = [select product_suffix__c, product_number__c, id from Item__c where id =:ai.prdDetail.Item__c];
		}
		
		catch (exception e){
		/*		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a valid product.'));
				return null;*/
		}
		lnRequest.LotNumber = ai.prdDetail.NBTY_Lot__c;
		lnRequest.LotNumberSequence = ai.prdDetail.Lot_Number_Sequence__c;
		if (selectedProduct!=null){
			if (selectedProduct.Product_Suffix__c!=null){
				lnRequest.ProductSuffix =  selectedProduct.Product_Suffix__c;
			} 
			lnRequest.SKU =  selectedProduct.Product_Number__c.startsWith('0')? selectedProduct.Product_Number__c.replaceFirst('^0+(?!$)', '') :selectedProduct.Product_Number__c;//remove leading zeros
		}
		system.debug('+++++++++++ ' + lnRequest.LotNumber); 
		system.debug('+++++++++++ ' + lnRequest.LotNumberSequence);
		system.debug('+++++++++++ ' + lnRequest.ProductSuffix);
		system.debug('+++++++++++ ' + lnRequest.SKU);
		//system.debug('+++++++++++ ' + lnRequest.SKU);
		return lnRequest;
	}
	
	public static Affected_Item__c parseResponse (Affected_Item__c prdDetail, ws_Soa_LotNumberQuery.LotNumberQueryResponse_element lnResponse){
		if(lnResponse.LotNumberQuerySuccess != null)
		{
			prdDetail.NBTY_Lot__c = lnResponse.LotNumberQuerySuccess.lotNumber;
			prdDetail.Lot_Number_Sequence__c = lnResponse.LotNumberQuerySuccess.lotNumberSequence;
			prdDetail.Product_Suffix__c = lnResponse.LotNumberQuerySuccess.productSuffix;
			prdDetail.sku__c = lnResponse.LotNumberQuerySuccess.sku;
			prdDetail.Packaging_Site__c = lnResponse.LotNumberQuerySuccess.pkgSiteDescription;
			prdDetail.Manufacturing_Site__c = lnResponse.LotNumberQuerySuccess.mfgSiteDescription;
			prdDetail.Vendor_Lot__c = lnResponse.LotNumberQuerySuccess.vendorLotNumber;
			prdDetail.Formula_Revision__c = lnResponse.LotNumberQuerySuccess.formulaRevision;
			prdDetail.Bulk_Number__c = lnResponse.LotNumberQuerySuccess.AS400BulkNumber;
			prdDetail.Bulk_Description__c = lnResponse.LotNumberQuerySuccess.bulkDescription;
			prdDetail.oracle_bulk_number__c = lnResponse.LotNumberQuerySuccess.OracleBulkNumber;
			prdDetail.oracle_product_number__c =  lnResponse.LotNumberQuerySuccess.OracleProductNumber;
			prdDetail.Expiration_Date__c = lnResponse.LotNumberQuerySuccess.ExpirationDate; 
			prdDetail.Label_Revision_Code__c = lnResponse.LotNumberQuerySuccess.LabelRevision;
			prdDetail.Label_Number__c = lnResponse.LotNumberQuerySuccess.LabelNumber;
			
		}
		return prdDetail;
	}

}