src/objects/Affected_Item__c.object
<CustomObject>
    <description>Child object for the case complaint object</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bulk_Description__c</fullName>
        <label>Bulk Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bulk_Number__c</fullName>
        <label>Bulk Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formula_Revision__c</fullName>
        <label>Formula Revision</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <label>Item Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Label_Number__c</fullName>
        <description>Label # from Lot Query Response</description>
        <label>Label Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label_Revision_Code__c</fullName>
        <label>Label Revision Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lot_Number_Sequence__c</fullName>
        <label>Lot Number Sequence</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturing_Site__c</fullName>
        <label>Manufacturing Site</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NBTY_Lot__c</fullName>
        <label>NBTY Lot#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Bulk_Number__c</fullName>
        <label>Oracle Bulk Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Oracle_Product_Number__c</fullName>
        <label>Oracle Product Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packaging_Site__c</fullName>
        <label>Packaging Site</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Suffix__c</fullName>
        <label>Product Suffix</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Affected Items</relationshipLabel>
        <relationshipName>Affected_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Synced_With_PQM__c</fullName>
        <label>Synced With PQM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Lot__c</fullName>
        <label>Vendor Lot#</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sku__c</fullName>
        <label>sku</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Affected Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Affected Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affected Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>International_Complaint__c</fullName>
        <defaultValue>false</defaultValue>
        <label>International Complaint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>CASE( Product_Suffix__c ,
&quot;0011&quot;,&quot;Puritan&apos;s Pride&quot;,
&quot;0070&quot;,&quot;Vitamin World&quot;,
&quot;0021&quot;,&quot;Perfectly Pure&quot;,
NULL)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bulk_Number__c</fullName>
        <label>Bulk Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <label>Item ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Item Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Suffix__c</fullName>
        <description>0011 - PP 0070 VB</description>
        <label>Item Suffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AffectedItemTriggerHelperTest.cls
@isTest
public class AffectedItemTriggerHelperTest {
	
	public static Case c;
	public static Affected_Item__c AI;
	public static List<Affected_Item__c> AiList;
	public static List<Item__c> newItem;
	
	public static void setupData()
	{
		c = new Case();
		AI = new Affected_Item__c();
		newItem = new List<Item__c>();
    	string selectedRecordType = 'Product_Complaint';
       	RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
    	c.RecordTypeId = rt.id;
    	c.International_Complaint__c = false;
    	CaseTriggerHelper.isFromChild=true;
		insert c;
		newItem = testDataSetupUtil.setupItems(1);
		AI.Item__c = newItem[0].Id;
		AI.Case__c = c.Id;
		AI.Product__c = newItem[0].Product_ID__c;
		AI.Brand__c = 'Putitans Pride';
		AI.Bulk_Description__c = 'Test';
		AI.Bulk_Number__c = '1231242243';
		AI.Expiration_Date__c = '11/08/2020';
		AI.Formula_Revision__c = 'Test';
		AI.Item_Number__c = newItem[0].Product_Number__c;
		AI.Label_Number__c = '2387461827';
		AI.Label_Revision_Code__c = 'wiurg2r';
		AI.Lot_Number_Sequence__c = '14241431';
		AI.Manufacturing_Site__c = 'Orlando';
		AI.NBTY_Lot__c = '234234342634';
		AI.Oracle_Bulk_Number__c = '345464113';
		AI.Oracle_Product_Number__c = '6784323577';
		AI.Packaging_Site__c = 'Orlando';
		AI.Product_Suffix__c = '12ojty5';
		AI.sku__c = '2343251';
		AI.Synced_With_PQM__c = 'No';
		AI.Vendor_Lot__c = '343452';
		AiList = new List<Affected_Item__c>();
		AiList.add(AI);
		insert AI;
	}
	
	static testMethod void beforeDeleteHelperTest()
	{
		setupData();
		test.startTest();
		AffectedItemTriggerHelper.BeforeDelete(AiList);
		test.stopTest();
	}
	
	static testMethod void beforeDeleteTriggerTest()
	{
		setupData();
		test.startTest();
		delete AI;
		test.stopTest();
	}
}