src/objects/Bundle__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field should be checked if the is bundle active.</description>
        <inlineHelpText>This field should be checked if the is bundle active.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Bundles</relationshipLabel>
        <relationshipName>Bundles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Configuration_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Stores values for configurable static values</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Configuration Setting</label>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BundleTriggerHelperTest.cls
@isTest
public  class BundleTriggerHelperTest {
	static testMethod void testBundles(){
		testDataSetupUtil.SetupCoreData(3);
		Configuration_Setting__c cs = new Configuration_Setting__c(Name='Active_Bundle_Limit', Value__c='2');
		insert cs;
		Bundle__c bund = new Bundle__c(Item__c = testDataSetupUtil.itemList[0].id, Active__c = true, Start_date__c=system.today().addDays(-1), end_Date__c = system.today().addDays(1));
		insert bund;
		Bundle__c bund2 = bund.clone(false);
		bund2.item__c= testDataSetupUtil.itemList[1].id;
		insert bund2;
		Bundle__c bund3 = bund.clone(false);
		bund3.item__c= testDataSetupUtil.itemList[2].id;
		boolean bFail = false;
		test.startTest();
		try {
			insert bund3;
		}
		catch (exception e){
			bFail=true;//It fails here because trying to insert an active when there is already 2 active
		}
		system.assert(bFail);
		bund3.active__c=false;
		insert bund3;
		bund3.active__c=true;
		 bFail = false;
		try {
			update bund3;
		}
		catch (exception e){
			bFail=true;//It fails here because trying to update to active when there is already 2 active
		}
		test.stopTest();
				system.assert(bFail);
	}
}