src/objects/Bundle__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field should be checked if the is bundle active.</description>
        <inlineHelpText>This field should be checked if the is bundle active.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Bundle</label>
    <nameField>
        <label>Bundle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bundles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Configuration_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Stores values for configurable static values</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Configuration Setting</label>
</CustomObject>

src/classes/BundleTriggerHelper.cls
public  class BundleTriggerHelper {
	public static void validateMaxActiveBundles(List <Bundle__c> newList, Map<Id, Bundle__c> oldMap){
		integer currentBundleCount = NBTYWSUtil.getActiveBundles('-1').size();
		integer MAX_BUNDLE_COUNT = Integer.valueOf(Configuration_Setting__c.getValues('Active_Bundle_Limit').value__c);
		String 	  validationErrorMessage ='There are already'+ MAX_BUNDLE_COUNT+'active bundles; please deactivate at least 1 bundle before additional activation.';
		for (Bundle__c b: newList){ 
			if (oldMap==null){
				if (b.Active__c && b.End_Date__c >=system.today()){
					if (currentBundleCount==MAX_BUNDLE_COUNT) b.addError (validationErrorMessage);
					else currentBundleCount++; 
				}
			} 
			else{
				if (!oldMap.get(b.id).active__c&&b.Active__c && b.End_Date__c >=system.today()){
					if (currentBundleCount==MAX_BUNDLE_COUNT) b.addError (validationErrorMessage);
					else currentBundleCount++;
				}
			} 
		}
	} 
}