src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CTI_Search__c</fullName>
        <label>CTI Search</label>
        <type>Phone</type>
    </fields>
</CustomObject>

src/classes/TestCILController.cls
/* 
	TestCILController
	Test Class for CIL 
	------------------------------------------------------------------
	Author			|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey   	|	4/16/2013	|	Created

*/

@isTest
private class TestCILController {

	static testMethod void myUnitTest() {
		TestDataSetupUtil.SetupCoreData(2);
		
		ApexPages.StandardController controller = new ApexPages.StandardController(TestDataSetupUtil.vwAcct);
		PageReference pageRef = Page.CIL_v2;		
		Test.setCurrentPage(pageRef);
		CILController ext = new CILController(controller);
		ext.selectedRecId = TestDataSetupUtil.order1.Id;
		Account a = [Select Id, Name, (Select Id, Name From Contacts), (Select Id, CaseNumber From Cases) From Account WHERE Id = :TestDataSetupUtil.vwAcct.Id];
		Case c = new Case();
		c.CTI_Search__c = '4195715968';
		c.Brand__c = 'Vitamin World';
		c.AccountId = a.Id;
		insert c;
		ext.getNowStr();
		ext.setRecId();
		ext.whoID = a.Contacts[0].Id;
		ext.whatID = TestDataSetupUtil.order1.Id;
		ext.callBothWhoWhat();
		ext.selectedRecId = TestDataSetupUtil.vwAcct.Id;
		ext.setRecId();
		ext.whoID = a.Contacts[0].Id;
		ext.whatID = TestDataSetupUtil.order1.Id;
		ext.selectedRecId = c.Id;
		ext.setRecId();
		ext.whoID = a.Contacts[0].Id;
		ext.whatID = c.Id;
		ext.save();
	}
}