src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Agile_Status__c</fullName>
        <description>Response code from PQM/Agile Case Update service</description>
        <label>Agile Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Other_Medications_OTC__c.object
<CustomObject>
    <fields>
        <fullName>OTC_Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OTC Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Other Medications/OTCs</relationshipLabel>
        <relationshipName>Other_Medications_OTCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Synced_With_PQM__c</fullName>
        <label>Synced With PQM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Other Medications/OTC</label>
    <nameField>
        <label>Other Medications/OTC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Medications/OTCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OTCTriggerHelper.cls
public with sharing class OTCTriggerHelper {
	
	public static void BeforeDelete(List<Other_Medications_OTC__c> triggerNew)
	{
		List<String> otcRelatedCases = New List<String>();
		
		for(Other_Medications_OTC__c aRelatedId : triggerNew)
		{
			otcRelatedCases.add(aRelatedId.OTC_Related_Case__c);
		}
		
		List<Case> parentCases = [SELECT Id, Agile_Status__c FROM Case WHERE Id IN :otcRelatedCases];
		
		for(Case aParent : parentCases)
		{
			if(aParent.Agile_Status__c == '0')
			{
				aParent.addError('The Nutrition Review attched to the parent case ' + aParent.Id + ' is unable to be deleted because the record was already synced with PQM');
			}
		}
		
		for(Other_Medications_OTC__c aReview : triggerNew)
		{
			if(aReview.Synced_With_PQM__c == 'Yes')
			{
				aReview.addError('The Nutrition Review ' + aReview.Name + ' is synced with PQM and cannot be deleted.');
			}
		}
	}

}