src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Agile_Status_Description__c</fullName>
        <description>Response description from PQM/Agile Case Update service</description>
        <label>Agile Status Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agile_Status__c</fullName>
        <description>Response code from PQM/Agile Case Update service</description>
        <label>Agile Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consumer_State_Picklist__c</fullName>
        <label>Consumer State</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consumer_State__c</fullName>
        <label>Consumer State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <label>Escalated?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sent_to_PQM_Date__c</fullName>
        <description>Date/Time that case was first successfully sent to PQM</description>
        <label>Sent to PQM Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sent_to_PQM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sent to PQM</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/objects/PQM_Return_Code__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PQM Return Codes</label>
</CustomObject>

src/objects/State_Abbreviation_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>State Abbreviation Mappings</label>
</CustomObject>

src/classes/CaseTriggerHelper.cls
/********************************************************************************
 ********************************************************************************    
 *  Class            : Case Trigger Helper
 *  Author           : Acumen Solutions: Mitch Malleo
 *  Version History  : 
 *  Creation         : 09/13/13
 *  Description      : Trigger helper for the case object
 *                      
 ********************************************************************************
 ********************************************************************************/

public with sharing class CaseTriggerHelper {
	
	public static boolean isFromChild = false;
	public static boolean alreadyFired = false;
	
	public static Map <Id, RecordType> rtMap ;
	
	public static Map <Id, RecordType> getRtMap(){
		if (rtMap==null){
			rtMap = new Map <Id, RecordType>();
			for (RecordType rt: [select id, developername, name from RecordType where sObjectType='Case' ]){
				rtMap.put(rt.id,rt);
			}
		}
		return rtMap;
	}
	
	public static void beforeInsert(List<Case> triggerNew){
		syncAccountLookups(triggerNew, null);
		for (Case c: triggerNew){
			// DE854 -- State not maping correctly. If the state field is not blank and is only 2 characters assume good
			if (!String.isBlank(c.Consumer_State__c)){
				if (c.Consumer_State__c.length() == 2){
					c.Consumer_State_PickList__c = c.Consumer_State__c;
				}
			}
			// DE854 -- If the state pick list is filled in, copy it over to state field as long as it's blank
			// otherwise, use the state field to look up the abbreviation, assuming they put in full state name.
			if (!String.isBlank(c.Consumer_State_Picklist__c) && String.isBlank(c.Consumer_State__c)){
				c.Consumer_State__c = c.Consumer_State_Picklist__c;
			} else if (!String.isBlank(c.Consumer_State__c) && String.isBlank(c.Consumer_State_Picklist__c)){
				c.Consumer_State_Picklist__c = String.valueOf(State_Abbreviation_Mapping__c.getValues(c.Consumer_State__c.toLowerCase().Capitalize()).Abbreviation__c);
			}
		}
	}
	
	public static void beforeUpdate(List<Case> triggerNew, Map <Id, Case> triggerOld){
		syncAccountLookups(triggerNew, triggerOld);
		isEscalatedStandardFieldUpdate(triggerNew);
		if (!isFromChild&!alreadyFired) checkForPqmCaseUpdates(triggerNew);
		if(triggerNew != null && triggerOld != null)
		{
			setAgileStatusDetail(triggerNew,triggerOld);
		}
		
		for (Case c: triggerNew){
			if (!String.isBlank(c.Consumer_State_Picklist__c)&&String.isBlank(c.Consumer_State__c)){
				
			}
		}
	}
	
	// DE857 -- added triggerOld param; using the Id, Case to verify old vs new to allow deleting
	public static void syncAccountLookups(List<Case> triggerNew, Map<Id, Case> triggerOld){
		for(Case c : triggerNew){
			// DE857 -- If the new case has a blank AccountId/Customer__c while the old one did not
			// then it was deleted and we should allow it. Also, make them both blank.
			if (c.Id != null && ((String.isBlank(c.AccountId) && !String.isBlank(triggerOld.get(c.Id).AccountId)) ||
			    (String.isBlank(c.Customer__c) && !String.isBlank(triggerOld.get(c.Id).Customer__c)))){
				c.Customer__c = null;
				c.AccountId = null;
			} else {
				if(c.AccountId == null && c.Customer__c != null){//second case = only Customer__c has a value: record this to accountId field
					c.AccountId = c.Customer__c;
				}else if(c.AccountId != null && c.Customer__c == null){//third case = only accountId has a value: record this to the Customer__c field
					c.Customer__c = c.AccountId;
				}
			}
		}
	}
	
	public static void checkForPqmCaseUpdates(List <Case> triggerNew){
		alreadyFired = true;
		for (Case c: triggerNew){
			if (getRtMap().get(c.RecordTypeId).developerName =='Product_Complaint'&&C.Status!='Closed'){
				c.Agile_Status__c=null;
				c.Agile_Status_Description__c=null;
				//soa_WebservicesClientUtil.sendCaseToPQM(c.id); not needed; called by batch every 5 minutes
			}
		}
	}
	
	public static void setAgileStatusDetail(List <Case> triggerNew, Map<Id, Case> triggerOld){
		
		for (Case c: triggerNew){
			boolean bContinue = true;
			if (triggerOld !=null) {
				if (c.Agile_Status__c==triggerOld.get(c.id).agile_status__c){
					bContinue=false;
				}
			}
			if (bContinue){
				system.debug(c);
				PQM_Return_Code__c codeDetail = PQM_Return_Code__c.getInstance(c.agile_status__c);
				if (codeDetail!=null)			c.agile_status_description__c = codeDetail.description__c;
				if (c.Agile_Status__c != null && c.Agile_Status__c != '-99' && c.Agile_Status__c != '-98' && !triggerOld.get(c.id).Sent_to_PQM__c){
					c.Sent_to_PQM__c=true;
					c.Sent_to_PQM_date__c = system.now();
				}
				system.debug(c.agile_status_description__c);
			}
		}
	}
	
	@Future(callout=true) 
	public static void sendCaseToPqm(Id caseId){
		soa_WebservicesClientUtil.sendCaseToPQM(caseId);
	}
	
	public static void isEscalatedStandardFieldUpdate(List<Case> triggerNew)
	{
		for(Case c : triggerNew)
		{
			if(c.Escalated__c == 'Yes')
			{
				c.IsEscalated = true;
			} 
			else
			{
				c.IsEscalated = false;
			}
		}
	}
}