src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Order_Adjustment__c.object
<CustomObject>
    <description>Use an Order Adjustment to process refunds on an order or add an additional miscellaneous charge to a customer order.</description>
    <fields>
        <fullName>Credit_Card_Expiration_Date__c</fullName>
        <label>Credit Card Expiration Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Name on Card</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <description>Encrypted Credit Card Number for re-authorization.</description>
        <label>Credit Card Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Token__c</fullName>
        <label>Credit Card Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JCB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PayPal_Reference_ID__c</fullName>
        <inlineHelpText>System reference only</inlineHelpText>
        <label>PayPal Reference ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_Type__c</fullName>
        <description>A Full Refund totals the value of all Order Line Items to calculate the total refund amount. A Partial Refund totals the value only of the Order Line Items that the user selects.</description>
        <label>Refund Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_or_Misc_Amount__c</fullName>
        <description>Stores Amount that needed to be refund or any Miscellaneous charges.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_Order_Paypal_Transaction_ID__c</fullName>
        <label>Related Order Paypal Transaction ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Order that this Order Adjustment affects.</description>
        <label>Related Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Reference_Number__c</fullName>
        <label>Transaction Reference Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Order Adjustment</label>
    <nameField>
        <displayFormat>OA-{000000}</displayFormat>
        <label>Order Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Misc_Charge</fullName>
        <active>true</active>
        <description>Use this record type to add charges to a customer&apos;s credit card to complete payment for an existing order</description>
        <label>Misc. Charge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WS_OrderAdjustment_Utils_Test.cls
@isTest
public with sharing class WS_OrderAdjustment_Utils_Test {

	public static Case testCase;

	public static void setupData(){
		testDataSetupUtil.SetupCoreData(2);
		Case c = new Case (accountId=testDataSetupUtil.acct.id, status='New', related_order__c=testDataSetupUtil.order1.id);
		insert c;
		testCase=c;
	}

	public static testMethod void test_OA_Refund_Failure(){
		setupData();
		testDataSetupUtil.order1.Order_Submitted__c=true;
		testDataSetupUtil.order1.Order_Status__c='Submitted';
		testDataSetupUtil.order1.Payment_Type__c='Credit Card';
		testDataSetupUtil.order1.Credit_Card_Type__c = 'MasterCard';
		testDataSetupUtil.order1.Credit_Card_Token__c='@Y8VFTY@WM3-4113';
		testDataSetupUtil.order1.Payment_Transaction_Reference_Number__c='53066D458FD0195E40B3DF0690BAE4624B77545F';
		update  testDataSetupUtil.order1;
			Order_Adjustment__c oa = new Order_Adjustment__c(related_order__c=testDataSetupUtil.order1.id, customer__c=testDataSetupUtil.acct.id);
		RecordType rt = [select id from RecordType where developerName='Refund' and sobjectType='Order_Adjustment__c'];

		oa.recordTypeId=rt.id;
		oa.Refund_Type__c='Full Refund';
		oa.Payment_Method__c='Credit Card';
		oa.Credit_Card_Type__c = 'MasterCard';
		oa.Refund_or_Misc_Amount__c=0;
		insert oa;
		testDataSetupUtil.oa=oa;
		test.startTest();
		Test.setMock(WebServiceMock.class, new MockResponse_OrderAdjustmentService ());
		WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp =WS_OrderAdjustmentUtils.doCallout(oa);
		test.stopTest();
		system.assert(WS_OrderAdjustmentUtils.refundRequest.refundType=='K');
		system.assert([select status__c from Order_Adjustment__c where id=:oa.id].status__c=='Error');
	}


	public static testMethod void test_OA_Refund_Credit(){
		setupData();
		testDataSetupUtil.order1.Order_Submitted__c=true;
		testDataSetupUtil.order1.Order_Status__c='Submitted';
		testDataSetupUtil.order1.Payment_Type__c='Credit Card';
		testDataSetupUtil.order1.Credit_Card_Token__c='@Y8VFTY@WM3-4113';
		testDataSetupUtil.order1.Credit_Card_Type__c = 'MasterCard';
		testDataSetupUtil.order1.Payment_Transaction_Reference_Number__c='53066D458FD0195E40B3DF0690BAE4624B77545F';
		update  testDataSetupUtil.order1;
			Order_Adjustment__c oa = new Order_Adjustment__c(related_order__c=testDataSetupUtil.order1.id, customer__c=testDataSetupUtil.acct.id);
		RecordType rt = [select id from RecordType where developerName='Refund' and sobjectType='Order_Adjustment__c'];
		Test.setMock(WebServiceMock.class, new MockResponse_OrderAdjustmentService ());
		oa.recordTypeId=rt.id;
		oa.Refund_Type__c='Full Refund';
		oa.Payment_Method__c='Credit Card';
		oa.Refund_or_Misc_Amount__c=10;
		oa.Credit_Card_Type__c = 'MasterCard';
		insert oa;
		testDataSetupUtil.oa=oa;
		test.startTest();
		WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp = WS_OrderAdjustmentUtils.doCallout(oa);
		test.stopTest();
		system.assert(WS_OrderAdjustmentUtils.refundRequest.refundType=='K');
		//system.assert(WS_OrderAdjustmentUtils.refundRequest.creditDetail.transactionReferenceNumber=='XXX123');
		//system.assert(WS_OrderAdjustmentUtils.refundRequest.creditDetail.TokenNumber=='@Y8VFTY@WM3-4113');
		//system.assert([select status__c from Order_Adjustment__c where id=:oa.id].status__c=='Processed');
		//system.assert([select Transaction_Reference_Number__c from Order_Adjustment__c where id=:oa.id].Transaction_Reference_Number__c=='XXX123');
	}

	public static testMethod void test_OA_Refund_Paypal(){
		setupData();
		testDataSetupUtil.order1.Order_Submitted__c=true;
		testDataSetupUtil.order1.Order_Status__c='Submitted';
		testDataSetupUtil.order1.Payment_Type__c='Paypal';
		testDataSetupUtil.order1.Paypal_Authorization_Code__c='ZZZ123';
		update  testDataSetupUtil.order1;
			Order_Adjustment__c oa = new Order_Adjustment__c(related_order__c=testDataSetupUtil.order1.id, customer__c=testDataSetupUtil.acct.id);
		RecordType rt = [select id from RecordType where developerName='Refund' and sobjectType='Order_Adjustment__c'];

		oa.recordTypeId=rt.id;
		oa.Refund_Type__c='Full Refund';
		oa.Payment_Method__c='Paypal';
		oa.Refund_or_Misc_Amount__c=10;
		oa.Related_Order_Paypal_Transaction_ID__c='ZZZ123';
		insert oa;
		testDataSetupUtil.oa=oa;
		test.startTest();
		Test.setMock(WebServiceMock.class, new MockResponse_OrderAdjustmentService ());
		WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp =WS_OrderAdjustmentUtils.doCallout(oa);
		test.stopTest();
		//system.assert(WS_OrderAdjustmentUtils.refundRequest.paypalDetail.transactionID=='ZZZ123');
		system.assert(WS_OrderAdjustmentUtils.refundRequest.refundType=='Y');
		system.assert([select status__c from Order_Adjustment__c where id=:oa.id].status__c=='Processed');
		system.assert([select PayPal_Reference_ID__c from Order_Adjustment__c where id=:oa.id].PayPal_Reference_ID__c=='ZZZ987');
		
	}

	public static testMethod void test_OA_Refund_Check(){
		setupData();
		testDataSetupUtil.order1.Order_Submitted__c=true;
		testDataSetupUtil.order1.Order_Status__c='Submitted';
		testDataSetupUtil.order1.Payment_Type__c='Check';
		update  testDataSetupUtil.order1;
			Order_Adjustment__c oa = new Order_Adjustment__c(related_order__c=testDataSetupUtil.order1.id, customer__c=testDataSetupUtil.acct.id);
		RecordType rt = [select id from RecordType where developerName='Refund' and sobjectType='Order_Adjustment__c'];

		oa.recordTypeId=rt.id;
		oa.Refund_Type__c='Full Refund';
		oa.Payment_Method__c='Check';
		oa.Refund_or_Misc_Amount__c=10;
		insert oa;
		testDataSetupUtil.oa=oa;
		test.startTest();
		Test.setMock(WebServiceMock.class, new MockResponse_OrderAdjustmentService ());
		WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp =WS_OrderAdjustmentUtils.doCallout(oa);
		test.stopTest();
		system.assert(WS_OrderAdjustmentUtils.refundRequest.refundType=='C');
		system.assert([select status__c from Order_Adjustment__c where id=:oa.id].status__c=='Processed');
	}

	public static testMethod void test_OA_Debit_Existing(){
		setupData();
			Order_Adjustment__c oa = new Order_Adjustment__c(related_order__c=testDataSetupUtil.order1.id, customer__c=testDataSetupUtil.acct.id);
		RecordType rt = [select id from RecordType where developerName='Misc_Charge' and sobjectType='Order_Adjustment__c'];
		oa.recordTypeId=rt.id;
		oa.Refund_Type__c='Full Refund';
		oa.Payment_Method__c='Existing Card';
		oa.Refund_or_Misc_Amount__c=10;
		oa.credit_card_token__c='@Y8VFTY@WM3-4113';
		insert oa;
		testDataSetupUtil.oa=oa;
		test.startTest();
		Test.setMock(WebServiceMock.class, new MockResponse_OrderAdjustmentService ());
		WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp =WS_OrderAdjustmentUtils.doCallout(oa);
		test.stopTest();
		system.assert(WS_OrderAdjustmentUtils.refundRequest==NULL);
		//system.assert([select status__c from Order_Adjustment__c where id=:oa.id].status__c=='Processed');
		
	}

	public static testMethod void test_OA_Debit_New(){
		setupData();
		Order_Adjustment__c oa = new Order_Adjustment__c(related_order__c=testDataSetupUtil.order1.id, customer__c=testDataSetupUtil.acct.id);
		RecordType rt = [select id from RecordType where developerName='Misc_Charge' and sobjectType='Order_Adjustment__c'];
		oa.recordTypeId=rt.id;
		oa.Refund_Type__c='Full Refund';
		oa.Payment_Method__c='Credit Card';
		oa.Refund_or_Misc_Amount__c=10;
		oa.Credit_Card_Expiration_Date__c='201504';
		oa.Credit_Card_Type__c='Visa';
		oa.Credit_Card_Name__c='Bob Jones';
		oa.Credit_Card_Number__c='4112344112344113';
		insert oa;
		testDataSetupUtil.oa=oa;
		test.startTest();
		
		Test.setMock(WebServiceMock.class, new MockResponse_OrderAdjustmentService ());
		WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp =WS_OrderAdjustmentUtils.doCallout(oa);
		test.stopTest();
		system.assert(WS_OrderAdjustmentUtils.refundRequest==NULL);
		//system.assert([select Transaction_Reference_Number__c from Order_Adjustment__c where id=:oa.id].Transaction_Reference_Number__c=='XXX123');
		
	}

}