src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>International_Complaint__c</fullName>
        <defaultValue>false</defaultValue>
        <label>International Complaint</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/objects/Other_Medications_OTC__c.object
<CustomObject>
    <fields>
        <fullName>OTC_Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OTC Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Other Medications/OTCs</relationshipLabel>
        <relationshipName>Other_Medications_OTCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Other Medications/OTC</label>
    <nameField>
        <label>Other Medications/OTC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Medications/OTCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OTCTriggerHelperTest.cls
@isTest
public class OTCTriggerHelperTest {

	public static Case c;
	public static Other_Medications_OTC__c newOTC;
	public static List<Other_Medications_OTC__c> OTCList;

	public static void setupData()
	{
		c = new Case();
		OTCList = new List<Other_Medications_OTC__c>();
		newOTC = new Other_Medications_OTC__c();
    	string selectedRecordType = 'Product_Complaint';
       	RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
    	c.RecordTypeId = rt.id;
    	c.International_Complaint__c = false;
    	CaseTriggerHelper.isFromChild=true;
		insert c;
		newOTC.OTC_Related_Case__c = c.Id;
		insert newOTC;
		OTCList.add(newOTC);
	}
	
	static testMethod void OTCTriggerHelperTest()
	{
		setupData();
		test.startTest();
		OTCTriggerHelper.BeforeDelete(OTCList);
		test.stopTest();
	}
	
	static testMethod void OTCTriggerTest()
	{
		setupData();
		test.startTest();
		delete newOTC;
		test.stopTest();
	}
}