src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rejected_Reason__c</fullName>
        <inlineHelpText>Why is this case being rejected?</inlineHelpText>
        <label>Rejected Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Spam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rejected?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SFDC_Case_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SFDC Case Assignment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Web_Form_Subject__c</fullName>
        <description>This is the &quot;Subject&quot; numerical value passed from the Web Form.</description>
        <label>Web Form Subject Num</label>
        <picklist>
            <controllingField>Origin</controllingField>
            <picklistValues>
                <fullName>Questions about our Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inquire about Current Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Difficulties Placing Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business/Affiliate Inquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comments about our Web Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broken Links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problems Finding a Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CaseAssignmentListViewController.cls
public class CaseAssignmentListViewController {
	public List<Case> cseList {get;set;}
	private Id userId;
	public Boolean showTable {get;set;}
	public String msg {get;set;}
	public List<Case_Wrapper> cseWrap {get;set;}
	
	public CaseAssignmentListViewController(){
		init();
	}
	
	public void init(){
		//get user Id
		userId = userInfo.getUserId();
		//Get list of new cases assigned to user
		cseList = [SELECT Id, CaseNumber, AccountId, Customer__c, Subject, Status, Origin, Brand__c, CreatedDate, Web_Form_Subject__c, 
					Rejected__c, Rejected_Reason__c 
					FROM Case WHERE OwnerId = :userId AND Status = 'New' AND SFDC_Case_Assignment__c = true ORDER BY CreatedDate ASC];
		//Determine if there are any cases present: yes=display table, no=display message
		if(cseList.size() > 0){
			showTable = true;
			cseWrap = new List<Case_Wrapper>();
			cseWrap = buildWrapper(cseList);
		}else{
			showTable = false;
			msg = 'You have no assigned cases.';
		}
	}
	
	public void refreshList(){
		init();
	}
	
	public void markAsSpam(){
		List<Case> cses = new List<Case>();
		for(Case_Wrapper cw: cseWrap){
			if(cw.isSpam == true){
				cw.cs.Rejected__c = true;
				cw.cs.Rejected_Reason__c = 'Spam';
				cw.cs.Status = 'Closed';
				cses.add(cw.cs);
			}
		}
		update cses;
		init();
	}
	
	public List<Case_Wrapper> buildWrapper(list<Case> cases){
		List<Case_Wrapper> cseWrapList = new List<Case_Wrapper>();
		for(Case cse : cases){
			cseWrapList.add(new Case_Wrapper(cse));
		}
		return cseWrapList;
	}
	
	public class Case_Wrapper {
		public Boolean isSpam {get;set;}
		public Case cs {get;set;}
		
		public Case_Wrapper(Case c){
			isSpam = false;
			cs = c;
		}
	}
}