src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Item Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Status_Detail__c.object
<CustomObject>
    <description>Child object of Order Line Items, contains status updates from AS400</description>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Item Status Details</relationshipLabel>
        <relationshipName>Order_Line_Item_Status_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order Line Item Status Detail</label>
    <nameField>
        <displayFormat>0{0000000000}</displayFormat>
        <label>Status Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item Status Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Final_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Final Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Name</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <formula>Product_Name__r.Product_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field refers to the quantity of the item being purchased.</description>
        <label>Item Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <formula>IF(Order__r.Customer__r.Associate_Customer__c,
Product_Name__r.Associate_Sale_Price__c,
Product_Name__r.Sale_Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Archive_Summary__c</fullName>
        <label>Archive Summary</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Task_Record__c</fullName>
        <label>Task Record</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/CILController.cls
/************************************* MODIFICATION LOG ********************************************************************************
*
* DESCRIPTION : CILController.cls has methods with RemoteAction annotation that provides support for JavaScript remoting used in CIL Visualforce Page. 
*
*---------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER						DATE				  REASON
*---------------------------------------------------------------------------------------------------------------------------------------
* Shivkant Vadlamani			04/10/2013			- Original Version
* Gary Alfrey					04/22/2013			- Refactored for NBTY
*	
*/

global with sharing class CILController {
	public Task task {get;set;}
	public String ANI {get;set;}	
	public List<SelectOption> whatList {get;set;}
	public Map<String, String> whatMap {get;set;}
	public List<SelectOption> whoList {get{system.debug(whoList);return whoList;}set;}
	public Map<String, String> whoMap {get;set;}
	public Map<String, String> discCaseMap {get;set;}
	public Map<String, String> discNumMap {get;set;}
	public Set<ID> recordIDSet {get;set;}
	public String whoID {get;set;}
	public String whatID {get;set;}
	public String whoobjID {get;set;}
	public String whatobjID {get;set;}
	public String discPrefix {get;set;}
	public List<SelectOption> wrapupOptionList {get;set;}
	public String OutboundCallObjID {get;set;}
	public Boolean isOutbound;
	public Boolean isCallend;
	public Boolean callDrop;
	public String selectedRecId {get;set;}
	public String callDriver {get;set;}
	public List<SelectOption> callDriverList {get;set;}
	public String jsonString {get;set;}
	public String statusMessage {get;set;}
	private User user {get;set;}
	private Account acct {get;set;}
	public List<Orders__c> orderHistory {get;set;}
	public Orders__c lastOrder {get;set;}
	public List<Order_Line_Items__c> lastOrderItems {get;set;}
	public boolean	bHasOrders {get;set;}
	public boolean isLastOrderCancellable {get;set;}
	public boolean showNone {get;set;}
	public List<Order_Line_Item_Status_Detail__c> ordStatusDetails {get;set;}
	public Order_Line_Item_Status_Detail__c olisd {get;set;}
	public Boolean showOrderStatusUpdates {get;set;}

	public CILController(ApexPages.StandardController controller){
		bHasOrders = true;
		String userId = userinfo.getUserId();
		user = [SELECT Id, Task_Record__c FROM User WHERE Id = :userId];
		try{
			task = [SELECT Id, Description, IVR_Case__c, IVR_Customer__c, IVR_Order__c, IVR_Status__c, Subject, CNX2__UniqueCallId__c FROM Task WHERE Id = :user.Task_Record__c];
		}catch(exception e){
			task = new Task();
			task.Subject = 'Call '+DateTime.now().format();
			task.CNX2__UniqueCallId__c = String.valueOf(Math.random()) + DateTime.now().gettime();
			task.ActivityDate = date.today();
		}
		jsonString = task.Description;
		task.Description = '';
		acct = (Account)controller.getRecord();
		
		orderHistory = [SELECT Id, Name, Order_Date__c, Order_Status__c,Archive_Summary__c , Order_Total__c FROM Orders__c WHERE Customer__c = :acct.Id AND Order_Submitted__c=true ORDER BY Order_Date__c DESC LIMIT 10];
		system.debug(orderHistory);
		if(orderHistory.size() > 0){
			lastOrder = orderHistory[0];
			isLastOrderCancellable = orderUtilities.statusSetToCancel(lastOrder.id);
			if(lastOrder.Order_Status__c != 'Shipped/Complete'){ 
				lastOrderItems = [SELECT Id, Product_Name__r.Product_Number__c, Product_Name__r.Name, Product_Quantity__c, Final_Price__c, Unit_Price__c FROM Order_Line_Items__c WHERE Order__c = :lastOrder.Id LIMIT 5];
			}else{
				lastOrderItems = OrderLineItemArchiveUtilities.restoreOlisFromArchive(lastOrder);
			}
		}else{
			bHasOrders=false;
		}
		
		init();				
		wrapupOptionList = new List<SelectOption>{new SelectOption('','-Select-')};			
	}

	public void init(){
		whatList = new List<SelectOption>();
		whoList = new List<SelectOption>();
		whatMap = new Map<String, String>();
		whoMap = new Map<String, String>();
		discCaseMap = new Map<String, String>();
		discNumMap = new Map<String, String>();
		recordIDSet = new Set<ID>();
		isOutbound = false;
		isCallend = false;
		callDrop = false;
		whoId = '';
		whatId = '';
		callDriver = '';
		callDriverList =  new List<SelectOption>();
	   
		for (Schema.PicklistEntry p : Schema.SObjectType.Task.fields.getMap().get('Call_Driver__c').getDescribe().getPicklistValues()){
			callDriverList.add(new SelectOption(p.getLabel(), p.getValue()));
		}
	}
	
	public String getNowStr(){
		return DateTime.now().format();
	}
	
	public void setRecId(){
		if(whoList.size() > 0){
			whoList.clear();
			whoId = '';	 
		}
		
		if(whatList.size() > 0){
			whatList.clear();
			whatId = ''; 
		}
		
		Schema.DescribeSObjectResult dsr = Orders__c.SObjectType.getDescribe();
		String orderPrefix = dsr.getKeyPrefix();
		system.debug('------------------------------' + dsr);
		system.debug('------------------------------' + orderPrefix);
		system.debug('------------------------------SELECTEDRECID ' + selectedRecId);
		
		if (selectedRecId.startsWith('500')){
		 	List<Case> caseList = [SELECT Id, ContactId, Contact.Name, CaseNumber, AccountId FROM Case WHERE Id = :selectedRecId];
		 	Set<Id> acctIds = new Set<Id>();
		 	for(Case c : caseList){
		 		acctIds.add(c.AccountId);
		 	}
		 	List<Account> acctList = [Select Id, Name, (Select Id, Name From Contacts) From Account WHERE Id IN :acctIds];
		 	Map<Id, List<Contact>> myMap = new Map<Id, List<Contact>>();
		 	for(Account a : acctList){
		 		myMap.put(a.Id, a.Contacts);
		 	}
			// Case. Return Case's contact.
			for(Case cs : [SELECT Id, ContactId, Contact.Name, CaseNumber, AccountId, Account.Id, Account.Name FROM Case WHERE Id = :selectedRecId]){
				if(cs.ContactId != null){
					whoList.add(new SelectOption(cs.ContactId, cs.Contact.Name));
				}
				
				whatList.add(new SelectOption(cs.Id, cs.CaseNumber));
				
				if(cs.AccountId != null){
					whatList.add(new SelectOption(cs.Account.Id, cs.Account.Name));
					List<Contact> con = myMap.get(cs.AccountId);
					for(Contact x : con){
						whoList.add(new SelectOption(x.Id, x.Name));
					}	
				}				
			}
			
		}else if (selectedRecId.startsWith('003')) {
		
			for(Contact con : [SELECT Id, Name, AccountId, Account.Name, (Select Id, CaseNumber From Cases) FROM Contact WHERE Id = :selectedRecId]){
				whoList.add(new SelectOption(con.Id, con.Name));
				whatList.add(new SelectOption(con.AccountId, con.Account.Name));
				
				for(Case cs : con.Cases){
					whatList.add(new SelectOption(cs.Id, cs.CaseNumber));
				}
			}
		}else if (selectedRecId.startsWith('001')) {
		 
			for(Account Acct : [Select Id, Name, (Select Id, Name From Contacts), (Select Id, CaseNumber From Cases) From Account WHERE Id = :selectedRecId ]){
				for(Contact con : Acct.Contacts){
					whoList.add(new SelectOption(con.Id, con.Name));
				}
				
				whatList.add(new SelectOption(Acct.Id, Acct.Name));
				
				for(Case cs : Acct.Cases){
					whatList.add(new SelectOption(cs.Id, cs.CaseNumber));
				}
			}
			
		}else if (selectedRecId.startsWith(orderPrefix)) {
			List<Orders__c> orderList = [SELECT Id, Name, Customer__r.Name, Customer__r.Id FROM Orders__c WHERE Id = :selectedRecId];
		 	Set<Id> acctIds = new Set<Id>();
		 	for(Orders__c o : orderList){
		 		acctIds.add(o.Customer__r.Id);
		 	}
		 	List<Account> acctList = [Select Id, Name, (Select Id, Name From Contacts) From Account WHERE Id IN :acctIds];
		 	Map<Id, List<Contact>> myMap = new Map<Id, List<Contact>>();
		 	for(Account a : acctList){
		 		myMap.put(a.Id, a.Contacts);
		 	}
			for(Orders__c ord : orderList){
				List<Contact> con = myMap.get(ord.Customer__r.Id);
				whatList.add(new SelectOption(ord.Id, ord.Name));
				for(Contact x : con){
					whoList.add(new SelectOption(x.Id, x.Name));
				}
			}
			
		}
		
	}
	
	public void callBothWhoWhat(){
		saveWhoWhatId();
	}
	
	public void saveWhoWhatId(){
		task.WhatId = whatId;
		task.WhoId = whoId;
		task.Status = 'In Progress';
		statusMessage = 'Last update on ' + DateTime.now().format();
		upsert task;
	}

	public void save(){
		task.WhatId = whatId;
		task.WhoId = whoId;
		task.CallType = isOutbound ? 'Outbound' : 'Inbound';
		task.Status = 'Completed';
		//task.CallDisposition = CallDisposition;
		//task.ActivityDate = system.today();
		task.Call_Driver__c = callDriver;
		upsert task;
		user.Task_Record__c = '';
		update user;
		statusMessage = 'Saved on ' + DateTime.now().format();
	}
	
	public void cancelOrder(){
		OrderUtilities.processOrderCancel(lastOrder.id,'Customer Cancelled');
	}
	
	public void dummyRefresh(){
		//do not remove, this is needed to refresh the page
	}
	
	
	
}