src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Complaint_Type__c</fullName>
        <label>Complaint Type</label>
        <picklist>
            <picklistValues>
                <fullName>Inquiry</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Class I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class II Non-Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class II Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class III</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/classes/CaseDetailTest.cls
@isTest
public class CaseDetailTest {
	
	public static Case c;

	public static void setupData()
	{
		c = new Case(customer__c =TestDataSetupUtil.acct.id );
    	string selectedRecordType = 'Product_Complaint';
       	RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = :selectedRecordType];
    	c.RecordTypeId = rt.id;
    	CaseTriggerHelper.isFromChild=true;
		insert c;
	}
	
	static testMethod void testingCaseDetail()
	{
		TestDataSetupUtil.SetupCoreData(2);
	    setupData();
	    ApexPages.StandardController controller = new ApexPages.StandardController(c);
	    PageReference pageRef = Page.CaseDetail;
	    Test.setCurrentPage(pageRef);
	    test.startTest();
	    CaseDetail caseDetailController = new CaseDetail(controller);
	    
	    caseDetailController.c.Complaint_Type__c = 'Class I';
	    caseDetailController.c.Category__c = 'Class I Packaging';
	    update c;
	    caseDetailController.init();
	    
	    caseDetailController.c.Complaint_Type__c = 'Class II Non-Illness';
	    caseDetailController.c.Category__c = 'Choking';
	    update c;
	    caseDetailController.init();
	    
	    caseDetailController.c.Complaint_Type__c = 'Class II Illness';
	    caseDetailController.c.Category__c = 'Eye Disorder';
	    update c;
	    caseDetailController.init();
	    
	    caseDetailController = new CaseDetail();
	    test.stopTest();
	}
	
	// Test case history functionality.
	static testMethod void getSomeObjectHistory_Test(){
		TestDataSetupUtil.SetupCoreData(2);
	    setupData();
	    ApexPages.StandardController controller = new ApexPages.StandardController(c);
	    PageReference pageRef = Page.CaseDetail;
	    Test.setCurrentPage(pageRef);
	    test.startTest();
	    CaseDetail caseDetailController = new CaseDetail(controller);
	    c.Category__c = 'Class I Packaging';
	    update c;
	    caseDetailController.getSomeObjectHistory(c.Id);
	    test.stopTest();
	}
	
	static testMethod void someObjectHistory_Test(){
		test.startTest();
		CaseDetail.SomeObjectHistory soh = new CaseDetail.SomeObjectHistory(new CaseHistory());
		String actionFormat = soh.ActionFormat;
		soh = new CaseDetail.SomeObjectHistory(new CaseHistory());
		test.stopTest();
	}
}