src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Order_Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This Case is the parent record for this Order Adjustment</description>
        <label>Related Order Adjustment</label>
        <referenceTo>Order_Adjustment__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Follow_Up</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all general follow-up cases.</description>
        <label>Follow-Up</label>
    </recordTypes>
</CustomObject>

src/objects/Order_Adjustment__c.object
<CustomObject>
    <description>Use an Order Adjustment to process refunds on an order or add an additional miscellaneous charge to a customer order.</description>
    <fields>
        <fullName>Credit_Card_Expiration_Date__c</fullName>
        <label>Credit Card Expiration Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <description>Encrypted Credit Card Number for re-authorization.</description>
        <label>Credit Card Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JCB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_Type__c</fullName>
        <description>A Full Refund totals the value of all Order Line Items to calculate the total refund amount. A Partial Refund totals the value only of the Order Line Items that the user selects.</description>
        <label>Refund Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_or_Misc_Amount__c</fullName>
        <description>Stores Amount that needed to be refund or any Miscellaneous charges.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Order Adjustment is related to this Case.</description>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Order_Payment_Type__c</fullName>
        <label>Related Order Payment Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Order that this Order Adjustment affects.</description>
        <label>Related Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Adjustment</label>
    <nameField>
        <displayFormat>OA-{000000}</displayFormat>
        <label>Order Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Misc_Charge</fullName>
        <active>true</active>
        <description>Use this record type to add charges to a customer&apos;s credit card to complete payment for an existing order</description>
        <label>Misc. Charge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Adjustment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Name__c</fullName>
        <label>Item Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Adjustment__c</fullName>
        <label>Order Adjustment</label>
        <referenceTo>Order_Adjustment__c</referenceTo>
        <relationshipLabel>Order Adjustment Line Items</relationshipLabel>
        <relationshipName>Order_Adjustment_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU_Number__c</fullName>
        <label>SKU Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isChecked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only Checked items are part of Refund.</description>
        <inlineHelpText>Only Checked items are part of Refund.</inlineHelpText>
        <label>Included in Refund</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Adjustment Line Item</label>
    <nameField>
        <label>Order Adjustment Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Adjustment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderAdjustmentControllerTest.cls
/*
 * Author       : Pavan Jasti, Acumen
 * Class        : OrderAdjustmentController 
 * Date         : 02/04/2014
 * Description  : Test class for OrderAdjustmentController.cls
*/
@isTest
public  class OrderAdjustmentControllerTest{
    
    static Case testCase;
    static Order_Adjustment__c testOrderAdjustment;
    
    public static void setupTestData(){
        // reusing TestDataSetupUtil
        TestDataSetupUtil.SetupCoreData(5);
       
        testCase = new Case();
        RecordType rt = [SELECT Id, DeveloperName FROM RecordType WHERE developerName = 'Follow_Up' and sObjectType = 'case'];
        testCase.customer__c =TestDataSetupUtil.acct.id ;
        testCase.Related_Order__c = TestDataSetupUtil.order1.id;
        insert testCase;
        
        testOrderAdjustment = TestDataSetupUtil.setupOrderAdjustment(testCase.Id,TestDataSetupUtil.order1.Id,TestDataSetupUtil.acct.Id);
    }
    
    public static void createAdjustmentLineItems(string adjId,integer recCount)
    {
    	list<Order_Adjustment_Line_Item__c>  adjlineItemsList = new list<Order_Adjustment_Line_Item__c>();
    	for(integer i=0; i < recCount;i++)
    	{
	    	Order_Adjustment_Line_Item__c oali = new Order_Adjustment_Line_Item__c();
		 	oali.Item_Name__c = 'Test Item';
		 	oali.Quantity__c = 1;
		 	oali.Amount__c = 10.00;
		 	oali.SKU_Number__c = '111'+i;
		 	oali.Order_Adjustment__c = adjId;
		 	adjlineItemsList.add(oali);
    	} 
    	insert adjlineItemsList;
    } 
    
    testMethod static void testCreateNewAndExistingMiscAdjustment(){
        setupTestData();
        RecordType miscRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Misc_Charge' AND sObjectType = 'Order_Adjustment__c' AND IsActive = true limit 1];

        Test.startTest();
	        Test.setCurrentPageReference(Page.OrderAdjustmentPage);
	        ApexPages.currentPage().getParameters().put('caseId',testCase.Id);
	        testOrderAdjustment.Id = null; //  //clearing Id of the adjustmnet to make it look like there is no Order adjustment. with help of case ID the order adjustment is created
	        ApexPages.StandardController sc = new ApexPages.StandardController(testOrderAdjustment);               
	        OrderAdjustmentController orderAdjController = new OrderAdjustmentController(sc);
	        // Testing all realted MISC charges related code
	        orderAdjController.orderAdj.Status__c = 'Draft' ;
	        orderAdjController.orderAdj.Refund_or_Misc_Amount__c = 25 ;
	        orderAdjController.orderAdj.RecordTypeId = miscRecType.Id ;
	        // getter methods
	        orderAdjController.getMiscChargeMethods();
	        orderAdjController.getMiscChargeStatus();
	        orderAdjController.renderComponents(); //SelectedRecType
	        orderAdjController.createOrderAdjustment(); //creates new order adjustment
	        // with different payment methods
	        orderAdjController.orderAdj.Payment_Method__c = 'Credit Card';
	        orderAdjController.orderAdj.Credit_Card_Number__c = '4112344112344113';
	        orderAdjController.orderAdj.Credit_Card_Type__c = 'Visa';
	        orderAdjController.orderAdj.Credit_Card_Expiration_Date__c = '201606';
	        orderAdjController.createOrderAdjustment();
	        orderAdjController.orderAdj.Payment_Method__c = 'Existing Card';
	        orderAdjController.createOrderAdjustment();
	        //with invalid card details and Token
	         orderAdjController.orderAdj.Payment_Method__c = 'Credit Card';
	        orderAdjController.orderAdj.Credit_Card_Number__c = '4112344112344113';
	        orderAdjController.orderAdj.Credit_Card_Type__c = 'Discover';
	        orderAdjController.orderAdj.Credit_Card_Expiration_Date__c = '201606';
	        orderAdjController.createOrderAdjustment();
	        orderAdjController.orderAdj.Payment_Method__c = 'Existing Card';
	        orderAdjController.createOrderAdjustment();
	        system.assert(orderAdjController.orderAdj.Id != null);
	        System.assertEquals(orderAdjController.orderAdj.Refund_or_Misc_Amount__c, 25);
	        system.debug('@@@testOrderAdjustment'+testOrderAdjustment);
	       
	        //testing Existing MISC order adjustment
	        testOrderAdjustment = TestDataSetupUtil.setupOrderAdjustment(testCase.Id,TestDataSetupUtil.order1.Id,TestDataSetupUtil.acct.Id);
	        ApexPages.StandardController sc1 = new ApexPages.StandardController(testOrderAdjustment);               
	        OrderAdjustmentController orderAdjController1 = new OrderAdjustmentController(sc1);
        Test.stopTest();
    }
    
    testMethod static void testExistingAdjustment(){
        setupTestData();
        RecordType refundRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Refund' AND sObjectType = 'Order_Adjustment__c' AND IsActive = true limit 1];
        // Updating Order adjustment details to work withoout case and related order
        testOrderAdjustment.Related_Order_Payment_Type__c = 'Cash';
        testOrderAdjustment.Related_Order__c = null;
        testOrderAdjustment.Related_Case__c = null;
        update testOrderAdjustment;
        createAdjustmentLineItems(testOrderAdjustment.Id,5);
        Test.startTest();
	        Test.setCurrentPageReference(Page.OrderAdjustmentPage);
	        ApexPages.StandardController sc = new ApexPages.StandardController(testOrderAdjustment);               
	        OrderAdjustmentController orderAdjController = new OrderAdjustmentController(sc);
	        orderAdjController.orderAdj.RecordTypeId = refundRecType.Id ;
	        List<SelectOption> ops = orderAdjController.getRefundMethods();
	        
	        //updating existing order adjustmnet along with line items
	        orderAdjController.orderAdj.Refund_or_Misc_Amount__c = 25 ;
	        orderAdjController.orderAdj.Refund_Type__c = 'Partial Refund';
	        orderAdjController.orderAdj.Payment_Method__c = 'Cash';
	        list<Order_Adjustment_Line_Item__c> adjolis = orderAdjController.adjlineItemsList;
	        adjolis.get(0).isChecked__c = true;
	        orderAdjController.renderComponents();
	        orderAdjController.createOrderAdjustment();
	        
	        // Full refund
	        orderAdjController.orderAdj.Refund_Type__c = 'Full Refund';
	        orderAdjController.renderComponents();
	        orderAdjController.createOrderAdjustment();
	        //if full refund is successful, all the line items should have Related_Order_Adjustment__c lookup
	        for(Order_Adjustment_Line_Item__c oaoli :[select Id,isChecked__c from Order_Adjustment_Line_Item__c where Id = : testOrderAdjustment.id] )
	        {
	            system.assert(oaoli.isChecked__c);    
	        }
	    Test.stopTest();
    }
    

}