src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Consumer_Email__c</fullName>
        <label>Consumer Email</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>Pre_Case</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for pre-cases.</description>
        <label>Pre-Case</label>
    </recordTypes>
</CustomObject>

src/objects/Email_Domain_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>All accepted domains for email to case</description>
    <label>Email Domain Map</label>
</CustomObject>

src/objects/EmailToCaseMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Map incoming emails to queue and brand</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NBTY_Email__c</fullName>
        <label>NBTY Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordType_Dev_Name__c</fullName>
        <label>RecordType Dev Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>EmailToCaseMapping</label>
</CustomObject>

src/classes/TestEmailToCase.cls
/* 
	TestEmailToCase
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey |	5/9/2013	|	Created

*/

@isTest
private class TestEmailToCase {
	
	static testMethod void myUnitTest() {
		TestDataSetupUtil.SetupCoreData(1);
		
		EmailToCaseMapping__c mc = new EmailToCaseMapping__c();
		mc.Brand__c = 'Puritan'+'s Pride';
		mc.Name = 'test1';
		mc.NBTY_Email__c = 'sfdc_dev@puritan.com';
		mc.Queue__c = 'BO_Puritain_s_Pride_E2C';
		mc.RecordType_Dev_Name__c = 'Puritans_Pride_Customer';
		insert mc;
		
		Email_Domain_Map__c edm = new Email_Domain_Map__c();
		edm.Name = 'puritan.com';
		insert edm;
		
		
		// create a new email and envelope object
		Messaging.InboundEmail email = new Messaging.InboundEmail() ;
		Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
		
		// setup the data for the email
		email.subject = 'Test Email ';
		email.fromname = 'FirstName LastName';
		email.plainTextBody = 'this is a test and only a test ';
		email.fromAddress = 'jDoe@test.com';
		List<String> mystr = new List<String>();
		mystr.add('nbty_inbound_service@3eyy0z337xlbau6703n07k4pj8ng0tgprm7xnr6zs1102of53.z-pan1maa.z.apex.sandbox.salesforce.com');
		myStr.add('sfdc_dev@puritan.com');
		email.toAddresses = mystr;
		
		// add an attachment
		Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
		attachment.body = blob.valueOf('my attachment text');
		attachment.fileName = 'textfile.txt';
		attachment.mimeTypeSubType = 'text/plain';
		
		email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
		
		// call the email service class and test it with the data in the testMethod
  		EmailToCaseProcessor emailProcess = new EmailToCaseProcessor();
		emailProcess.handleInboundEmail(email, env);
	}
	
	static testMethod void test2(){
		
		TestDataSetupUtil.SetupCoreData(1);
		
		EmailToCaseMapping__c mc = new EmailToCaseMapping__c();
		mc.Brand__c = 'Puritan'+'s Pride';
		mc.Name = 'test1';
		mc.NBTY_Email__c = 'sfdc_dev@puritan.com';
		mc.Queue__c = 'BO_Puritain_s_Pride_E2C';
		mc.RecordType_Dev_Name__c = 'Puritans_Pride_Customer';
		insert mc;
		
		Email_Domain_Map__c edm = new Email_Domain_Map__c();
		edm.Name = 'puritan.com';
		insert edm;
		
		RecordType rt3 = [SELECT Id FROM RecordType WHERE DeveloperName = 'Pre_Case' AND SobjectType = 'Case'];
		Case myCase = new Case();
		myCase.RecordTypeId = rt3.Id;
		myCase.Status = 'Waiting on Customer';
		myCase.Origin = 'Email';
		myCase.Type = 'Question';
		myCase.Consumer_Email__c = 'jdoe@test.com';
		myCase.AccountId = TestDataSetupUtil.acct.Id;
		insert myCase;
		
		// create a new email and envelope object
		Messaging.InboundEmail email = new Messaging.InboundEmail() ;
		Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
		
		// setup the data for the email
		email.subject = 'Test Email ';
		email.fromname = 'FirstName LastName';
		email.plainTextBody = 'this is a test and only a test ref:' + myCase.Id + ':ref';
		email.fromAddress = 'jDoe@test.com';
		List<String> mystr = new List<String>();
		mystr.add('nbty_inbound_service@3eyy0z337xlbau6703n07k4pj8ng0tgprm7xnr6zs1102of53.z-pan1maa.z.apex.sandbox.salesforce.com');
		myStr.add('sfdc_dev@puritan.com');
		email.toAddresses = mystr;
		
		// add an attachment
		Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
		attachment.body = blob.valueOf('my attachment text');
		attachment.fileName = 'textfile.txt';
		attachment.mimeTypeSubType = 'text/plain';
		
		email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
		
		// call the email service class and test it with the data in the testMethod
		EmailToCaseProcessor emailProcess = new EmailToCaseProcessor();
		emailProcess.handleInboundEmail(email, env);
	}
}