src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Amount__c</fullName>
        <label>Credit Amount</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_Notes__c</fullName>
        <label>Credit Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Credit_Reason__c</fullName>
        <label>Credit Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Discontinued/Backordered Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Tax Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Order/Promo/Price Discrepancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Satisfaction (ie: Make Good)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VW Bonus Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damaged/Undeliverable/ Post-ship Cancellation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Adjustment__c.object
<CustomObject>
    <description>Use an Order Adjustment to process refunds on an order or add an additional miscellaneous charge to a customer order.</description>
    <fields>
        <fullName>AS400_Order_Number__c</fullName>
        <description>AS400 Order Number</description>
        <label>AS400 Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Reason__c</fullName>
        <inlineHelpText>Error Reason for error-state orders sent from AS/400</inlineHelpText>
        <label>Error Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_Type__c</fullName>
        <description>A Full Refund totals the value of all Order Line Items to calculate the total refund amount. A Partial Refund totals the value only of the Order Line Items that the user selects.</description>
        <label>Refund Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_or_Misc_Amount__c</fullName>
        <description>Stores Amount that needed to be refund or any Miscellaneous charges.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Order Adjustment is related to this Case.</description>
        <label>Related Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Order that this Order Adjustment affects.</description>
        <label>Related Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Salesforce_Order_Number__c</fullName>
        <label>Salesforce Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Stores the record type, even when record is process and flipped to Read Only</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Misc. Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Order_Number__c</fullName>
        <description>Order Number from Web</description>
        <label>Web Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Order Adjustment</label>
    <nameField>
        <displayFormat>OA-{000000}</displayFormat>
        <label>Order Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Misc_Charge</fullName>
        <active>true</active>
        <description>Use this record type to add charges to a customer&apos;s credit card to complete payment for an existing order</description>
        <label>Misc. Charge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Read_Only</fullName>
        <active>true</active>
        <description>Read Only</description>
        <label>Read Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Adjustment_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>External_Key__c</fullName>
        <description>Order # - Line # Combination</description>
        <externalId>true</externalId>
        <label>External Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Adjustment__c</fullName>
        <label>Order Adjustment</label>
        <referenceTo>Order_Adjustment__c</referenceTo>
        <relationshipLabel>Order Adjustment Line Items</relationshipLabel>
        <relationshipName>Order_Adjustment_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isChecked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only Checked items are part of Refund.</description>
        <inlineHelpText>Only Checked items are part of Refund.</inlineHelpText>
        <label>Included in Refund</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Adjustment Line Item</label>
    <nameField>
        <label>Order Adjustment Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Adjustment Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>AS400_Order_Number__c</fullName>
        <label>AS400 Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Third_Party_Order_Number__c</fullName>
        <label>3rd Party Order Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_ID__c</fullName>
        <label>Webstack ID</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WebStoresData__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Block_Order_Adjustments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Block Order Adjustments</label>
        <type>Checkbox</type>
    </fields>
    <label>Web Stores Data</label>
</CustomObject>

src/classes/OrderAdjustmentTriggerHelper.cls
/* 
 *  Class           : OrderAdjustmentTriggerHelper 
 *  Author          : Pavan Jasthi - Acumen Solutions
 *  Creation         : 02/10/2014
 *  Description     : Helper class for OrderAdjustmentTrigger
 *                      
*/
public with sharing class OrderAdjustmentTriggerHelper {

	public static void isAfterInsert(List<Order_Adjustment__c> orderAdjList) {
		OrderAdjustmentTriggerHelper.UpdateOrderStatus(orderAdjList,null);
	}
	
	public static void isAfterUpdate(List<Order_Adjustment__c> orderAdjList, Map <Id, Order_Adjustment__c> oldMap) {
		OrderAdjustmentTriggerHelper.UpdateOrderStatus(orderAdjList,oldMap);
		createCredit(orderAdjList,oldMap);
		OrderAdjustmentTriggerHelper.autoCloseCases(orderAdjList);
		//updateRecordTypeOnProcessed(orderAdjList,oldMap);
	}
	
	public static void isBeforeUpdate(List<Order_Adjustment__c> orderAdjList,Map <Id, Order_Adjustment__c> oldMap) {
		preCheckDupRefund(orderAdjList, oldMap);
		updateRecordTypeToReadOnly(orderAdjList, oldMap);
	}
	
	public static void isBeforeInsert(List<Order_Adjustment__c> triggerNew) {
		OrderAdjustmentTriggerHelper.setTypeValue(triggerNew);
		OrderAdjustmentTriggerHelper.blockOrderAdjustments(triggerNew);
	}
	
	public static void setTypeValue(List <Order_Adjustment__c> ordAdjList){
		Map <Id, RecordType> oaRtMap= new Map <Id, RecordType>();
		for (RecordType rt: [select id, developerName, Name from RecordType where sObjectType='Order_Adjustment__c']){
			oaRtMap.put(rt.id, rt);
		}
		for (Order_Adjustment__c oa: ordAdjList){
			oa.Type__c=oaRtMap.get(oa.RecordTypeId).Name;
		}
	}
	
	
	public static void preCheckDupRefund(List <Order_Adjustment__c> ordAdjList, Map<Id, Order_Adjustment__c> oldMap){
			List <Order_Adjustment__c> checkOAList = new List <Order_Adjustment__c>();
			for (Order_Adjustment__c oa:ordAdjList){
				if ((oa.Status__c=='Approved')&&(oldMap.get(oa.id).status__c!='Approved')){
					checkOAList.add(oa);
				}
			}
			if (!checkOAList.isEmpty()){
				checkDupRefund(checkOAList);
			}
	}
	
	public static void checkDupRefund(List <Order_Adjustment__c> ordAdjList){
		/*Begin check on validation to prevent same orders/lines from being refunded*/
								/* check for full refund, block same order*/
				Set <String> ordAdjustmentsToCheck = new Set <String>();
				Map <String,Order_Adjustment__c> alreadyProcessedOrdNumMap = new Map <String,Order_Adjustment__c>();
				Set <Id> oaIds = new Set <Id>();
				for (Order_Adjustment__c oa: ordAdjList){
					ordAdjustmentsToCheck.add(oa.AS400_Order_Number__c);
					ordAdjustmentsToCheck.add(oa.Related_Order__c);
					ordAdjustmentsToCheck.add(oa.Salesforce_Order_Number__c);
					ordAdjustmentsToCheck.add(oa.Web_Order_Number__c);
					oaIds.add(oa.id);//needed for order line checking for partial refunds
				}
				for (Order_Adjustment__c tempoa : [select id, name , AS400_Order_Number__c, Salesforce_Order_Number__c
																		from Order_Adjustment__c 
																		where (AS400_Order_Number__c in :ordAdjustmentsToCheck
																		or Related_Order__c  in :ordAdjustmentsToCheck
																		or Salesforce_Order_Number__c  in :ordAdjustmentsToCheck
																		or Web_Order_Number__c  in :ordAdjustmentsToCheck)
																		and (Status__c ='Processed'
																		or 	Status__c ='Approved')
																		//and recordType.developerName = 'Read_Only'
																		and Refund_Type__c ='Full Refund'	 ]){
					if (tempoa.AS400_Order_Number__c!=null) alreadyProcessedOrdNumMap.put(tempoa.AS400_Order_Number__c, tempoa);
					if (tempoa.Salesforce_Order_Number__c!=null)  alreadyProcessedOrdNumMap.put(tempoa.Salesforce_Order_Number__c, tempoa);
				}
				/* check for partial refund, block lines*/
				Set <String> checkLineKeySet = new Set <String>();
				Map <Id, List <Order_Adjustment_Line_Item__c>> oalMap = new Map <Id, List <Order_Adjustment_Line_Item__c>>();
				for (Order_Adjustment_Line_Item__c oal: [select id, External_Key__c ,Order_Adjustment__c, Order_Adjustment__r.name
																							from Order_Adjustment_Line_Item__c 
																							where order_adjustment__c in:oaIds
																							and isChecked__c = true		 ]){
																								checkLineKeySet.add(oal.external_key__c);
																							if (oalMap.get(oal.Order_Adjustment__c)==null){
																								oalMap.put(oal.Order_Adjustment__c, new List <Order_Adjustment_Line_Item__c>{oal});
																							}
																							else {
																								oalMap.get(oal.Order_Adjustment__c).add(oal);
																							}
					}
				if (!checkLineKeySet.isEmpty()){
					for (Order_Adjustment_Line_Item__c oal : [select id, Order_Adjustment__c, order_adjustment__r.name, order_adjustment__r.AS400_Order_Number__c, order_adjustment__r.Salesforce_Order_Number__c, external_key__c
																			from Order_Adjustment_Line_Item__c 
																			where (  order_adjustment__r.Status__c ='Processed'
																			or order_adjustment__r.Status__c ='Approved')
																		//	and order_Adjustment__r.recordType.developerName = 'Read_Only'
																			and order_adjustment__r.Refund_Type__c ='Partial Refund'	 
																			and isChecked__c = true
																			and external_key__c in :checkLineKeySet]){
						alreadyProcessedOrdNumMap.put(oal.external_key__c, oal.order_adjustment__r);
					}
				}
				if (!alreadyProcessedOrdNumMap.isEmpty()){
					for (Order_Adjustment__c oa: ordAdjList){
						string checkNumber = oa.AS400_Order_Number__c!=null?  oa.AS400_Order_Number__c :oa.Salesforce_Order_Number__c ;
						if (alreadyProcessedOrdNumMap.keySet().contains(checkNumber)){
							oa.status__c = 'Rejected';
							oa.Error_Reason__c='Refund already processed through Order Adjustment: '+alreadyProcessedOrdNumMap.get(checkNumber).name;		
						}
					}
					for (Order_Adjustment__c oa: ordAdjList){
						if (oalMap.get(oa.id)!=null){
							for (Order_Adjustment_Line_Item__c oal: oalMap.get(oa.id)){
								if (alreadyProcessedOrdNumMap.keySet().contains(oal.External_Key__c)){
									oa.status__c = 'Rejected';
									oa.Error_Reason__c='Refund already processed through Order Adjustment: '+alreadyProcessedOrdNumMap.get(oal.External_Key__c).name;		
								}													
							}
						}
					}
				}
	}
	
	public static void updateRecordTypeToReadOnly (List<Order_Adjustment__c> orderAdjList,Map <Id, Order_Adjustment__c> oldMap) {
		RecordType roRecType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE sObjectType = 'Order_Adjustment__c' and DeveloperName = 'Read_Only' limit 1];
		for(Order_Adjustment__c oa : orderAdjList) {
			if ((oa.Status__c=='Processed'||oa.Status__c=='Customer Paid')&&(oldMap.get(oa.id).status__c!='Processed'&&oldMap.get(oa.id).status__c!='Customer Paid')){
				oa.RecordTypeId=roRecType.id;
			}
		}
	}
	
	public static void UpdateOrderStatus(List <Order_Adjustment__c> orderAdjList, Map <Id, Order_Adjustment__c> oldMap) {
		system.debug('-------------------------------------------------------------------START');
		set<string> orderIds = new set<string>();
		RecordType miscRecType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE sObjectType = 'Order_Adjustment__c' and DeveloperName = 'Misc_Charge' limit 1];
		for(Order_Adjustment__c oa : orderAdjList) {
			if (oa.Related_Order__c!=null) orderIds.add(oa.Related_order__c); 
		}
		if (!orderIds.isEmpty()){
			system.debug('-------------------------------------------------------------------orderIds: ' + orderIds);
			map<Id, orders__c> ordersMap = new map<Id, orders__c>([SELECT Id, Order_Status__c, Order_Submitted__c, CreatedById, OwnerId FROM Orders__c WHERE Id IN :orderIds]);
			system.debug('-------------------------------------------------------------------ordersMap: ' + ordersMap);
			//update trigger
			List<Orders__c> ordersToUpdate = new List<Orders__c>();
			if (oldMap != null && !oldMap.isEmpty()) {
				for(Order_Adjustment__c odj : orderAdjList) {
					system.debug('-------------------------------------------------------------------odj1: ' + odj);
					//if(odj.RecordTypeId == miscRecType.Id) {
						//Only when either status fields change for misc charges
						system.debug('-------------------------------------------------------------------oldMap.get(odj.Id).status__c: ' + oldMap.get(odj.Id).status__c);
						if((oldMap.get(odj.Id).status__c != 'Processed' && odj.status__c =='Processed') || (oldMap.get(odj.Id).Status__c != 'Customer Paid' && odj.Status__c =='Customer Paid')) {
							//"Customer paid" through cash or check , "Processed" when paid through credit card
							if((odj.Status__c == 'Customer Paid' && (odj.Payment_Method__c == 'Cash' || odj.Payment_Method__c =='Check')) || (odj.status__c =='Processed' && (odj.Payment_Method__c == 'Credit Card' || odj.Payment_Method__c =='Existing Card'))) {
								//If its not already sumbitted for order fullfilment to AS400 then change to Pending Submission
								orders__c ord = ordersMap.get(odj.Related_Order__c);
								if(!ord.order_submitted__c && ord.Order_Status__c != 'Pending Submission')
									ord.Order_Status__c = 'Pending Submission';
									ord.OwnerId = ord.CreatedById;
									ordersToUpdate.add(ord);
							}
						}
					//}
				}	
			} else {//insert trigger
				for(Order_Adjustment__c odj : orderAdjList) {
					system.debug('-------------------------------------------------------------------odj2: ' + odj);
					//if(odj.RecordTypeId == miscRecType.Id) {
						//"Customer paid" through cash or check , "Processed" when paid through credit card
						if((odj.Status__c == 'Customer Paid' && (odj.Payment_Method__c == 'Cash' || odj.Payment_Method__c =='Check')) || (odj.status__c =='Processed' && (odj.Payment_Method__c == 'Credit Card' || odj.Payment_Method__c =='Existing Card'))) {
							//If its not already sumbitted for order fullfilment to AS400 then change to Pending Submission
							orders__c ord = ordersMap.get(odj.Related_Order__c);
							if(!ord.order_submitted__c && ord.Order_Status__c != 'Pending Submission')
								ord.Order_Status__c = 'Pending Submission';
								ordersToUpdate.add(ord);
						}
					//}
				}
			}
			update ordersToUpdate;
			//update ordersMap.values();
		}
	}
	
	public static void createCredit(List <Order_Adjustment__c> orderAdjList, Map <Id, Order_Adjustment__c> oldMap) {
		list<Credit__c> credits = new list<Credit__c>();
		Set<string> tempAdjIds = new Set<string>();
		Set<Id> caseIds = new Set<Id>();
		List <Order_Adjustment__c> tempOdjList = new List <Order_Adjustment__c>();
		for(Order_Adjustment__c odj : orderAdjList) {
			if(odj.Payment_method__c == 'Customer Credit' && odj.status__c == 'Approved' && oldmap.get(odj.Id).status__c != 'Approved') {
				
				credit__c newCredit = new Credit__c();
				newCredit.Account__c = odj.Customer__c;
				newCredit.Credit_Amount__c = odj.Refund_or_Misc_Amount__c; 
				newCredit.Credit_Notes__c = 'Refund for OA #'+odj.Name;
				newCredit.Credit_Reason__c = 'Refund';
				tempAdjIds.add(odj.Id);
				credits.add(newCredit);
				if (odj.Related_Case__c != null) {
					caseIds.add(odj.Related_Case__c);
				}
			}
		}
		if(credits.size() > 0)
			insert credits;
		//Flipping Orderadjustments status to processed once customer credit is created
		if(tempAdjIds.size() > 0) {
			for(Order_Adjustment__c odj : [select Id,Status__c from Order_Adjustment__c where Id IN:tempAdjIds ]) {
				odj.Status__c = 'Processed'; // flipping to processed
				tempOdjList.add(odj);
			}
			if(tempOdjList.size() > 0) {
				update tempOdjList;
			}
			//closeCaseForProcessed(caseIds);
		}
	}
	
	public static void autoCloseCases(List<Order_Adjustment__c> triggerNew) {
		Set<Id> cseIds = new Set<Id>();
		for (Order_Adjustment__c a : triggerNew) {
			if (a.Status__c == 'Processed') {
				cseIds.add(a.Related_Case__c);
			}
		}
		RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Product_Complaint' LIMIT 1];
		Map<Id, Case> caseMap = new Map<Id, Case>([SELECT Id, Status FROM Case WHERE Id IN :cseIds AND RecordTypeId != :rt.Id]);
		List<Case> cseList = new List<Case>();
		for (Order_Adjustment__c oa : triggerNew) {
			if (oa.Status__c == 'Processed') {
				Case cse = caseMap.get(oa.Related_Case__c);
				if (cse != null) {
					cse.Status = 'Closed';
					cseList.add(cse);
				}
			}
		}
		update cseList;
	}
	
	public static void blockOrderAdjustments(List<Order_Adjustment__c> triggerNew) {
		system.debug('-----------------------------------------Start blockOrderAdjustments');
		Set<String> oaSet = new Set<String>();
		for (Order_Adjustment__c oa1 : triggerNew) {
			oaSet.add(oa1.Related_Order__c);
			system.debug('-----------------------------------------oa1: ' + oa1);
		}
		system.debug('-----------------------------------------oaSet: ' + oaSet);
		Map<Id, Orders__c> wsidMap = new Map<Id, Orders__c>([SELECT Id, Webstack_ID__c, Third_Party_Order_Number__c FROM Orders__c WHERE Id IN :oaSet]);
		system.debug('-----------------------------------------wsidMap: ' + wsidMap);
		
		for (Order_Adjustment__c oa3 : triggerNew) {
			Orders__c oa = wsidMap.get(oa3.Related_Order__c);
			system.debug('-----------------------------------------oa: ' + oa);
			if (oa != null) {
				String wsid = oa.Webstack_ID__c;
				system.debug('-----------------------------------------wsid: ' + wsid);
				if (!String.isBlank(wsId)) {
					WebStoresData__c wsd = WebStoresData__c.getValues(wsid);
					system.debug('-----------------------------------------wsd: ' + wsd);
					if (wsd != null) {
						if (wsd.Block_Order_Adjustments__c) {
							oa3.addError('Cannot create Order Adjustments for Web Stack Id: ' + wsid);
						} else if (wsid == '1' && !String.isBlank(oa.Third_Party_Order_Number__c)) {
							oa3.addError('Cannot create Order Adjustments for Order Groove orders.');
						}
					}
				}
			}
		}
	}
	
	
	
	
}