src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Pre_Case</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for pre-cases.</description>
        <label>Pre-Case</label>
    </recordTypes>
</CustomObject>

src/objects/Case_Assignment_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <label>Assignment Rule</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Case Assignment Rule</label>
</CustomObject>

src/classes/CaseRouting_Test.cls
@isTest
private class CaseRouting_Test {
	
	public static Case_Assignment_Rule__c car;
	public static List<Case> cseList;
		
	
	public static void setupTestData(){
		//Create Assignment Rules
		car = new Case_Assignment_Rule__c();
		car.Name = 'CAR-0001';
		car.Queue_Name__c = 'E Support Backlog';
		car.Assignment_Rule__c = 'Test Rule 1';
		insert car;
		
		//Create Cases
		RecordType recType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE DeveloperName = 'Pre_Case' LIMIT 1];
		cseList = new List<Case>();
		Case cse1 = new Case();
		cse1.RecordTypeId = recType.Id;
		cse1.Status = 'New';
		cse1.Brand__c = 'Vitamin World';
		cse1.Origin = 'Web to Case';
		cseList.add(cse1);
		
		Case cse2 = new Case();
		cse2.RecordTypeId = recType.Id;
		cse2.Status = 'New';
		cse2.Brand__c = 'Vitamin World';
		cse2.Origin = 'Web to Case';
		cseList.add(cse2);
		insert cseList;
		
	}

	static testMethod void testCaseRoutingController() {
		setuptestData();
		test.startTest();
		CaseRoutingController crc = new CaseRoutingController();
		crc.getQueueSelect();
		crc.getCaseQuantitySelect();
		crc.selectedQuantity = '2';
		crc.selectedQueue = 'E Support Backlog';
		crc.assignCases();
		CaseAssignmentListViewController calvc = new CaseAssignmentListViewController();
		calvc.refreshList();
		calvc.cseWrap = new List<CaseAssignmentListViewController.Case_Wrapper>();
		calvc.cseWrap = calvc.buildWrapper(cseList);
		calvc.cseWrap[0].isSpam = true;
		calvc.markAsSpam();
		test.stopTest();
	}
	
	static testMethod void testCaseAssignmentListViewcontroller(){
		CaseAssignmentListViewController calvc = new CaseAssignmentListViewController();
		calvc.refreshList();
	}
	
}