src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PQM_Consumer_Country__c</fullName>
        <label>PQM Consumer Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reporter_City__c</fullName>
        <label>Reporter City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Country__c</fullName>
        <label>Reporter Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Email__c</fullName>
        <label>Reporter Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Reporter_Name_del__c</fullName>
        <label>Reporter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Phone__c</fullName>
        <label>Reporter Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Reporter_State__c</fullName>
        <label>Reporter State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Street__c</fullName>
        <label>Reporter Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporter_Zip_Code__c</fullName>
        <label>Reporter Zip Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Follow_Up</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all general follow-up cases.</description>
        <label>Follow-Up</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pre_Case</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for pre-cases.</description>
        <label>Pre-Case</label>
    </recordTypes>
    <recordTypes>
        <fullName>Product_Complaint</fullName>
        <active>true</active>
        <businessProcess>General Support Process</businessProcess>
        <description>This record type will be used for all product related inquiries or complaints.</description>
        <label>Product Information</label>
    </recordTypes>
</CustomObject>

src/objects/Country_Code_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PQM_Country__c</fullName>
        <label>PQM Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Country Code Mapping</label>
</CustomObject>

src/objects/Customer_Rec_Type_Brand_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Picklist_Brand__c</fullName>
        <description>Needed for Inbound Call Controller</description>
        <label>Picklist Brand</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Customer Rec Type Brand Mapping</label>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting for all Web Service Integration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value Associated for the Name</description>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>WS_Integration</label>
</CustomObject>

src/classes/NewCaseController.cls
/* 
	NewCaseController
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey |	5/20/2013	|	Created
	Gary Alfrey |	10/30/13	|	Completely Refactored

*/

public with sharing class NewCaseController {
	
	public Case newCase {get;set;}
	private Case editCase {get;set;}
	private String caseId;
	private String editRedirectStr;
	public String newCaseId {get;set;}
	private String accountId;
	private String orderId;
	public String selectedRecType {get;set;}
	private Map<String, String> recMap;
	public	boolean closeTab {get;set;}
	
	
	public NewCaseController(ApexPages.StandardController controller){
		caseId = controller.getId();
		newCase = new Case();
		closeTab = false;
	}
	
	public void setupRTMap(){
		Set<String> mySet = new Set<String>{'Pre_Case','Follow_Up','Product_Complaint'};
		List<RecordType> recList = [SELECT Id, Name, DeveloperName FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName IN: mySet];
		recMap = new Map<String, String>();
		for(RecordType a : recList){
			
			recMap.put(a.Id, a.DeveloperName);
			recMap.put(string.valueOf(a.Id).substring(0,15), a.DeveloperName);
		}
	}
	
	public List<SelectOption> getRecTypes(){
			setupRtMap();
			Set<String> mySet = new Set<String>{'Pre_Case','Follow_Up','Product_Complaint'};
			List<RecordType> recList = [SELECT Id, Name, DeveloperName FROM RecordType WHERE sObjectType = 'Case' AND DeveloperName IN: mySet];
		List<SelectOption> options = new List<SelectOption>();
		for(RecordType a : recList){
			options.add(new SelectOption(a.Id,a.Name));
		}
	
		return options;
	}
	
	public PageReference init(){
		accountId = ApexPages.currentPage().getParameters().get('def_account_id');
		system.debug('-----------------------------------------------------------accountId: ' + accountId);
		system.debug('-----------------------------------------------------------retURL: ' + ApexPages.currentPage().getParameters().get('retURL'));
		//orderId = ApexPages.currentPage().getParameters().get('retURL').substring(22,37);
		String retURL = ApexPages.currentPage().getParameters().get('retURL');
		if (retURL != null) {
			if (retURL.length()>=37){
				orderId = retURL.substring(22,37);
			}
			system.debug('-----------------------------------------------------------orderId: ' + orderId);
		} else {
			orderId = '';
		}
		
		setupRTMap();
		string rtId = ApexPages.currentPage().getParameters().get('RecordType');
		string recordTypeName ;
		if (rtId!=null){
			recordTypeName = recMap.get(rtId);
		}
		if(caseId != null && caseId != ''){  //edit  change record type or clone scenario
			if (recordTypeName==null){
				recordTypeName = [select recordType.DeveloperName from Case where id =:caseId].recordType.developerName;
			}
			if(recordTypeName == 'Product_Complaint'){
				editRedirectStr = '/apex/Case_ICM?id=' + caseId + '&retURL=%2F' + caseId;
			}else{
				if(rtId != null){
					editRedirectStr = '/' + caseId + '/e?retURL=%2F' + caseId + '&nooverride=1' + '&RecordType='+rtId;
				}else{
					editRedirectStr = '/' + caseId + '/e?retURL=%2F' + caseId + '&nooverride=1';
				}
			}
			PageReference ref = new PageReference(editRedirectStr);
			ref.setRedirect(true);
			return ref;
		}
		else {// clone or new scenario
			Schema.DescribeSObjectResult caseDescribe = Case.SObjectType.getDescribe();
			system.debug('1-2-2-2-2' + ApexPages.currentPage().getParameters().get('RecordType'));
			//string rtId = ApexPages.currentPage().getParameters().get('RecordType');
			Account acct;
			Orders__c ord;
			Customer_Rec_Type_Brand_Mapping__c crtbm;
			if (accountId!=null){
				acct=[select id, recordType.DeveloperName from Account where id =:accountId];
				crtbm = NBTYUtils.getRecordTypeBrandMappingMap().get(acct.recordType.developerName);
			}
			if (orderId!=null){
				if (orderId.startsWith('a07')) {//this means the substring contains an order Id
					ord = [SELECT Id, Customer__c, Customer__r.RecordType.DeveloperName, Name FROM Orders__c WHERE Id = :orderId];
					crtbm = NBTYUtils.getRecordTypeBrandMappingMap().get(ord.Customer__r.RecordType.DeveloperName);
					AccountId = ord.Customer__c;
					orderId = ord.Id;
				}
			}

			if (rtId != null){
				newCase.RecordTypeId = rtId;
				system.debug('-------------------' + newCase.RecordTypeId);
				if (recMap.get(rtId)=='Product_Complaint') {
					editRedirectStr = '/apex/Case_ICM' + '?RecordType='+rtId;
					if (AccountId!=null) {
						editRedirectStr+='&AccountId='+AccountId;
					}
				} else {
					editRedirectStr = '/' + caseDescribe.getKeyPrefix() + '/e?retURL=%2F' + AccountId + '&RecordType='+rtId+'&nooverride=1';
					if (AccountId!=null) {
						editRedirectStr+='&def_account_id='+AccountId+'&'+WS_Integration__c.getInstance('CaseBrandID').value__c+'='+crtbm.Picklist_Brand__c;
					}
					if (orderId != null && ord != null) {
						editRedirectStr += '&' + WS_Integration__c.getInstance('CaseOrderNameId').value__c + '=' + ord.Name + '&' + WS_Integration__c.getInstance('CaseOrderlkId').value__c + '=' + ord.Id;
					}
					system.debug('-----------------------------------------------------------editRedirectStr: ' + editRedirectStr);
				}
				
			 	PageReference ref = new PageReference(editRedirectStr);
				ref.setRedirect(true);
				return ref;
			//return null;
			}
			else return null;
		}
		//return null;
	}
	
	public PageReference createNewCase(){
		
		/*
		system.debug('--------------------------------AccountId1: ' + accountId);
		if (accountId != null && accountId != ''){
			accountId = String.escapeSingleQuotes(accountId);
			Account acct = [SELECT Id, RecordTypeId, Phone, FirstName, LastName, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, 
							RecordType.Name, RecordType.DeveloperName, PersonEmail, PersonHomePhone FROM Account WHERE Id = :accountId];
			newCase.Reporter_Name_del__c = acct.FirstName + ' ' + acct.LastName;
			newCase.Reporter_Street__c = acct.BillingStreet;
			newCase.Reporter_City__c = acct.BillingCity;
			newCase.Reporter_State__c = acct.BillingState;
			newCase.Reporter_Zip_Code__c = acct.BillingPostalCode;
			newCase.Reporter_Country__c = acct.BillingCountry;
			newCase.Reporter_Email__c = acct.PersonEmail;
			newCase.Reporter_Phone__c = acct.PersonHomePhone;
			Country_Code_Mapping__c ccm = NBTYUtils.getcountryCodeToCCMMap().get(newCase.Reporter_Country__c);
			if (ccm!=null) {
				Country_Code_Mapping__c ccm2 = Country_Code_Mapping__c.getValues(ccm.Name__c);
				if (ccm2!=null){
					newCase.PQM_Consumer_Country__c = ccm2.PQM_Country__c;
				}
			}
			Customer_Rec_Type_Brand_Mapping__c rtbm = NBTYUtils.getRecordTypeBrandMappingMap().get(acct.recordType.developerName);
			newCase.Brand__c = rtbm.Picklist_Brand__c;
			newCase.RecordTypeId = selectedRecType;
			newCase.AccountId = accountId;
			newCase.Origin = 'Phone';
			
			
		} else {
			newCase.RecordTypeId = selectedRecType;
			newCase.Origin = 'Phone';
		}
		*/
		
		system.debug('-------------------' + newCase.RecordTypeId);
		newCase.RecordTypeId = recMap.get(selectedRecType);
		insert newCase;
		string recTypeName = recMap.get(selectedRecType);
		string redirectStr;
		if(recTypeName == 'Product_Complaint'){
			redirectStr = '/apex/Case_ICM?id=' + newCase.Id + '&retURL=%2F' + newCase.Id;
		}else{
			redirectStr = '/'+newCase.id + '/e?retURL=%2F' + newCase.id + '&nooverride=1';
		}
		
		PageReference ref = new PageReference(redirectStr);
		ref.setRedirect(true);
		return ref;
	}
	
	public void cancelCase(){
		closeTab = true;
	}
	
}