src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>Puritan&apos;s Pride</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vitamin World</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfectly Pure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Air Shield</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albertson&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Mart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bio-Engineered Supplements &amp; Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Fortress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carb Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctor&apos;s Trust</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duane Reade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Earthly Elements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equaline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ester-C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Everclen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finest Nutrition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flexamin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Giant Eagle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good N&apos; Natural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GPC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases as Customer</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFDC_CA_Time__c</fullName>
        <label>SFDC CA Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SFDC_Case_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SFDC Case Assignment</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Case_Assignment_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <label>Assignment Rule</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Case Assignment Rule</label>
</CustomObject>

src/classes/CaseRoutingController.cls
public class CaseRoutingController {
	
	public String selectedQueue {get;set;}
	public String selectedQuantity {get;set;}
	private Id userId;
	public String redirectStr {get;set;}
	public List<Case> cseList {get;set;}
	public String userName {get;set;}
	private String msg;
	
	public CaseRoutingController(){
		userId = userInfo.getUserId();
		userName = userInfo.getName();
		//redirectStr = '/apex/CaseAssignmentListView';
	}
	
	public List<SelectOption> getQueueSelect(){
		//Get a list of groups the user belongs to
		List<GroupMember> usersGroups = [SELECT Id, GroupId, Group.Name FROM GroupMember WHERE UserOrGroupId = :userId AND Group.Type != 'Queue'];
		Set<String> groupIds = new Set<String>();
		for(GroupMember c : usersGroups){
			system.debug('---------------------------------------------------------------userGroups: ' + c.Id + ' ' + c.Group.Name);
			groupIds.add(c.GroupId);
		}
		groupIds.add(userId);
		//Use groups to find queues a users group belongs to
		List<GroupMember> gmList = [SELECT Id, GroupId, Group.Name FROM GroupMember WHERE UserOrGroupId IN :groupIds AND Group.Type = 'Queue'];
		Set<String> gmSet = new Set<String>();
		Set<String> gmNameSet = new Set<String>();
		for(GroupMember x : gmList){
			gmSet.add(x.GroupId);
			gmNameSet.add(x.Group.Name);
			system.debug('---------------------------------------------------------------userGroups: ' + x.GroupId);
		}
		//Create a select list from available queues
		List<Case_Assignment_Rule__c> carList = [SELECT Id, Queue_Name__c, Assignment_Rule__c FROM Case_Assignment_Rule__c 
													WHERE Queue_Name__c IN :gmNameSet];
		Set<String> qNameSet = new Set<String>();
		List<SelectOption> queueOptions = new List<SelectOption>();
		for(Case_Assignment_Rule__c car : carList){
			if(!qNameSet.contains(car.Assignment_Rule__c)){
				qNameSet.add(car.Assignment_Rule__c);
				queueOptions.add(new SelectOption(car.Assignment_Rule__c, car.Assignment_Rule__c));
			}
		}
		
		return queueOptions;
	}
	
	public List<SelectOption> getCaseQuantitySelect(){
		List<SelectOption> caseQuantity = new List<SelectOption>();
		caseQuantity.add(new SelectOption('1','1'));
		caseQuantity.add(new SelectOption('3','3'));
		caseQuantity.add(new SelectOption('5','5'));
		caseQuantity.add(new SelectOption('7','7'));
		caseQuantity.add(new SelectOption('10','10'));
		return caseQuantity;
	}
	
	public void assignCases(){
		List<Case_Assignment_Rule__c> carList = Case_Assignment_Rule__c.getAll().values();
		Set<String> qSet = new Set<String>();
		for(Case_Assignment_Rule__c car : carList){
			if(car.Assignment_Rule__c == selectedQueue){
				qSet.add(car.Queue_Name__c);
			}
		}
		//Query Cases where the owner = the selected queue
		//cases assigned FIFO
		cseList = new List<Case>();
		if(selectedQueue != null && selectedQuantity != null){
			Integer i = Integer.valueOf(selectedQuantity);
			cseList = [SELECT Id, OwnerId FROM Case WHERE Owner.Name IN :qSet AND Status = 'New' ORDER BY CreatedDate ASC LIMIT :i];
			for(Case cse : cseList){
				cse.OwnerId = userId;
				cse.SFDC_CA_Time__c = datetime.now();
				cse.SFDC_Case_Assignment__c = true;
			}
			
			update cseList;
			
			List<Case> cseList2 = [SELECT Id, CaseNumber, AccountId, Customer__c, Subject, Status, Origin, Brand__c, CreatedDate 
					FROM Case WHERE OwnerId = :userId AND Status = 'New' AND SFDC_Case_Assignment__c = true ORDER BY CreatedDate ASC];
					
			if(i == 1 && cseList.size() > 0 && cseList2.size() == 1){
				redirectStr = '/' + cseList[0].Id;
				setPageMessage(msg = 'Success. ' + string.valueOf(cseList.size()) + ' cases assigned.');
			}else if(i > 1 && cseList.size() > 0 && cseList2.size() > 1){
				redirectStr = '/apex/CaseAssignmentListView';
				setPageMessage(msg = 'Success. ' + string.valueOf(cseList.size()) + ' cases assigned.');
			}else if(i == 1 && cseList.size() > 0 && cseList2.size() >= 1){
				redirectStr = '/apex/CaseAssignmentListView';
				setPageMessage(msg = 'Success. ' + string.valueOf(cseList.size()) + ' cases assigned.');
			}else{
				redirectStr = '/apex/CaseAssignmentListView';
				setPageMessage(msg = 'There are no available cases in assignment rule ' + selectedQueue);
			}
		}else {
			//user didn't select something
		}
	}
	
	public static void setPageMessage(String msg){
		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, msg);
		ApexPages.addMessage(myMsg);
	}
	
}