src/objects/Credit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credits</relationshipLabel>
        <relationshipName>Credits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Adjustment__c.object
<CustomObject>
    <description>Use an Order Adjustment to process refunds on an order or add an additional miscellaneous charge to a customer order.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_or_Misc_Amount__c</fullName>
        <description>Stores Amount that needed to be refund or any Miscellaneous charges.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Adjustment</label>
    <nameField>
        <displayFormat>OA-{000000}</displayFormat>
        <label>Order Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Misc_Charge</fullName>
        <active>true</active>
        <description>Use this record type to add charges to a customer&apos;s credit card to complete payment for an existing order</description>
        <label>Misc. Charge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderAdjustmentTriggerHelperTest.cls
/*
 * Author       : Pavan Jasti, Acumen
 * Class        : OrderAdjustmentController 
 * Date         : 02/04/2014
 * Description  : Test class for OrderAdjustmentTriggerHelper.cls
*/
@isTest
public with sharing class OrderAdjustmentTriggerHelperTest {
	 
	 static Order_Adjustment__c testOA;
	 static Orders__c testorder;
	 
	 public static void setupTestData(){
        TestDataSetupUtil.SetupCoreData(1);
        testOA = TestDataSetupUtil.setupOrderAdjustment(null,TestDataSetupUtil.order1.Id,TestDataSetupUtil.acct.Id);
        testorder = TestDataSetupUtil.order1;
     } 
      
     testMethod static void testOrderStatusupdates(){
        setupTestData();
        RecordType miscRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Misc_Charge' AND sObjectType = 'Order_Adjustment__c' AND IsActive = true limit 1];
        Test.startTest();
            testOA.RecordTypeId = miscRecType.Id ;
        	testOA.status__c = 'Processed';
        	testOA.Payment_Method__c = 'Credit Card';
        	update testOA;
        	testOA.status__c = 'Customer Paid';
        	testOA.Payment_Method__c = 'Cash';
        	update testOA;
        	testorder = [Select Id,Order_status__c from orders__c where Id=:testorder.id];
        	System.assertEquals(testorder.Order_Status__c, 'Pending Submission');
        	
        Test.stopTest();
     }
     
     testMethod static void testRelatedOARecords(){
        setupTestData();
        // Credit creation
        Test.startTest();
            testOA.Refund_or_Misc_Amount__c = 10.00;
            testOA.Payment_Method__c = 'Customer Credit';
            testOA.status__c = 'Approved';
        	update testOA;
            system.assertequals([select count() from Credit__c where Account__c =:testOA.Customer__c], 1);     	
        Test.stopTest();
     }
      
}