src/objects/Credit_Refund_Detail__c.object
<CustomObject>
    <description>Stores multiple transaction reference numbers related to Credit Refunds</description>
    <fields>
        <fullName>Credit_Card_Token__c</fullName>
        <label>Credit Card Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Adjustment__c</fullName>
        <label>Order Adjustment</label>
        <referenceTo>Order_Adjustment__c</referenceTo>
        <relationshipName>Credit_Refund_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Amount__c</fullName>
        <label>Original Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Bank_Response_DateTime__c</fullName>
        <label>Original Bank Response DateTime</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Order_Total__c</fullName>
        <label>Original Order Total</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Transaction_Reference_Number__c</fullName>
        <description>Transaction Reference Number for Original Settle Transaction</description>
        <label>Original Transaction Reference Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Credit Refund Request</description>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>OA ID + Original Transaction Reference Number</description>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Credit Transaction Detail</label>
    <nameField>
        <displayFormat>CRD-{00000}</displayFormat>
        <label>Credit Refund Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Refund Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Order_Adjustment__c.object
<CustomObject>
    <description>Use an Order Adjustment to process refunds on an order or add an additional miscellaneous charge to a customer order.</description>
    <fields>
        <fullName>Credit_Card_Token__c</fullName>
        <label>Credit Card Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JCB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Adjustment</label>
    <nameField>
        <displayFormat>OA-{000000}</displayFormat>
        <label>Order Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderAdjustment_CreditRefundDetails.cls
public with sharing class OrderAdjustment_CreditRefundDetails {

	public static Id OrderAdjustmentId;
	
	
	public static List <Credit_Refund_Detail__c> populateCrdList( ws_Soa_OrderHistoryService.orders ord){
		system.debug('------------------------------------------------start populateCrdList');
		List <Credit_Refund_Detail__c> crdList = new List <Credit_Refund_Detail__c>();
		if (ord.payments != null && ord.payments.payment != null) {
			//List <ws_Soa_OrderHistoryService.payment> paymentList =ord.payments.payment;
			for (ws_Soa_OrderHistoryService.payment pay: ord.payments.payment) {
				Credit_Refund_Detail__c crd = new Credit_Refund_Detail__c(Order_Adjustment__c=OrderAdjustmentId);
				crd.Original_Amount__c=decimal.valueOf(pay.authorizationAmount);
				crd.Original_Transaction_Reference_Number__c = pay.transactionReferenceNumber;
				crd.Unique_Key__c= OrderAdjustmentId+'-'+pay.transactionReferenceNumber+'-'+pay.transactionType;
				crd.Original_Order_Total__c = decimal.valueOf(ord.orderHeader.totalNetPurchaseAmount);
				crd.Credit_Card_Token__c = pay.tokenNumber;
				crd.Credit_Card_Type__c = NBTYUtils.getCCTypeMappings('AS400').get( ord.orderHeader.creditCardType)!=null ? NBTYUtils.getCCTypeMappings('AS400').get( ord.orderHeader.creditCardType).Name: null;
				crd.Status__c = pay.transactionType;
				CRD.Original_Bank_Response_DateTime__c = pay.bankResponseDateTime;
				crdList.add(crd);
			}
		}
		return crdList;
	}
}