src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Product_ID__c</fullName>
        <label>Item ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Item Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order_Line_Item_Status_Detail__c.object
<CustomObject>
    <description>Child object of Order Line Items, contains status updates from AS400</description>
    <fields>
        <fullName>Credit_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Rejected?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Current Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Line Item Status Details (Current Item)</relationshipLabel>
        <relationshipName>Order_Line_Item_Status_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Quantity__c</fullName>
        <description>Current Quantity</description>
        <label>Current Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Sku__c</fullName>
        <label>Current Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Status_Code__c</fullName>
        <description>2 Digit AS400 status code</description>
        <inlineHelpText>2 Digit AS400 status code</inlineHelpText>
        <label>Current Status Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Status__c</fullName>
        <description>SFDC Status Value</description>
        <label>Current Status</label>
        <picklist>
            <picklistValues>
                <fullName>IN PROGRESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING MERCHANT ACTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SHIPPED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Disposition_Number__c</fullName>
        <label>Disposition Number</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Free_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Free Item?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLineSplit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Signifies if the update was part of a line split.</description>
        <inlineHelpText>Signifies if the update was part of a line split.</inlineHelpText>
        <label>Is Line Split</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Line Item</label>
        <referenceTo>Order_Line_Items__c</referenceTo>
        <relationshipLabel>Order Line Item Status Details</relationshipLabel>
        <relationshipName>Order_Line_Item_Status_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Status_Code__c</fullName>
        <label>Order Status Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status_Description__c</fullName>
        <label>Order Status Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Item Status Details</relationshipLabel>
        <relationshipName>Order_Line_Item_Status_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Line Item Status Details</relationshipLabel>
        <relationshipName>Order_Line_Item_Status_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Quantity__c</fullName>
        <label>Previous Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Sku__c</fullName>
        <label>Previous Sku</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipper__c</fullName>
        <description>Name of Shipping carrier</description>
        <inlineHelpText>Name of Shipping carrier</inlineHelpText>
        <label>Shipper</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Stamp__c</fullName>
        <description>Records Time Stamp for each update transaction</description>
        <inlineHelpText>Records Time Stamp for each update transaction</inlineHelpText>
        <label>Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tracking_Link__c</fullName>
        <label>Tracking Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item Status Detail</label>
    <nameField>
        <displayFormat>0{0000000000}</displayFormat>
        <label>Status Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item Status Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Rejected?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Status_Code__c</fullName>
        <description>A/S 400 Status Code</description>
        <label>Item Status Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <formula>Product_Name__r.Product_ID__c</formula>
        <label>Item ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item Name</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <formula>Product_Name__r.Product_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field refers to the quantity of the item being purchased.</description>
        <label>Item Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Shipped__c</fullName>
        <label>Quantity Shipped</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment_Tracking_Number__c</fullName>
        <description>Used to capture the tracking number associated with the shipment of the product.</description>
        <label>Shipment Tracking Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipped_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field, specifies when a line Item has been shipped.</description>
        <label>Shipped Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shipper__c</fullName>
        <description>Used to capture the shipping information from the order fulfillment system.</description>
        <label>Shipper</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Quantity__c</fullName>
        <description>ONLY for use with Order status update web service - Do not touch or alter!</description>
        <label>Update Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Credit_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Rejected?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Status_Code__c</fullName>
        <description>Stores AS400 order status code (PB,PA,SA, etc.)</description>
        <label>Order Status Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status_Description__c</fullName>
        <description>Long description of order status</description>
        <label>Order Status Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Webstack_Order_ID__c</fullName>
        <label>Webstack Order ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderStatusMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>SFDC_Order_Line_Status__c</fullName>
        <label>SFDC Order Line Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_Order_Status__c</fullName>
        <label>SFDC Order Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Status Map</label>
</CustomObject>

src/objects/WS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting for all Web Service Integration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value Associated for the Name</description>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>WS_Integration</label>
</CustomObject>

src/classes/WS_OrderStatusQueryUtils.cls
/*
	WS_OrderStatusQueryUtils
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey |	10/21/13	|	Created

*/

public class WS_OrderStatusQueryUtils {
	
	public static Map<Id, String> suffixMap;
	
	public static WS_OrderStatusQuery.OrderStatusQueryResponse_element doCallout(Id orderId){
		try{
			system.debug('-------------------------------------------OrderId: ' + orderId);
			Orders__c ord = getOrders(orderId);
			WS_OrderStatusQuery.OrderStatusQueryResponse_element response_Element = getResponse(ord);
			system.debug('--------------------------------------Response_Element: ' + response_Element);
			return response_Element;
		}catch(Exception e){
			system.debug('------------------------------------------------------Exception: ' + e);
			logError(e);
			//here I should create a new fault response manually and return that - only way to display failed callouts
			WS_OrderStatusQuery.OrderStatusQueryResponse_element err = new WS_OrderStatusQuery.OrderStatusQueryResponse_element();
			WS_OrderStatusQuery.OrderStatusFault f = new WS_OrderStatusQuery.OrderStatusFault();
			f.FaultMessage = e.getMessage();
			f.FaultCode = e.getTypeName();
			err.OrderStatusFault = f;
			return err;
		}
	}

	public static Orders__c getOrders(Id orderId){
		Orders__c currOrder = [SELECT Id, Name, Webstack_Order_ID__c FROM Orders__c WHERE Id = :orderId];
		return currOrder;
	}  
	
	public static WS_OrderStatusQuery.OrderStatusQueryResponse_element getResponse(Orders__c ord){
		WS_OrderStatusQuery.OrderQueryPort statusQuery = new WS_OrderStatusQuery.OrderQueryPort();
		String padOrdNum = orderUtilities.zeroLPAD(ord.name, 10);
		// DE866 -- Adding padding for webstack order id; Peter R reports it's not searching bad one's correctly;
		// Mindtree stated it was because of the lack of padding.
		// DE885 -- send null when null not zeros
		String padWebNum = String.IsBlank(ord.Webstack_Order_ID__c) ? null : orderUtilities.zeroLPAD(ord.Webstack_Order_ID__c, 10);
		return statusQuery.OrderStatusQuery(padWebNum, padOrdNum);
	}
	
	public static List<Order_Line_Item_Status_Detail__c> processSuccess(WS_OrderStatusQuery.OrderStatusSuccess resp){
		try{
			//Parse response and create Status Detail records
			List<Order_Line_Item_Status_Detail__c> olisd = new List<Order_Line_Item_Status_Detail__c>();
			Datetime dt = Datetime.now();
			Orders__c ord = queryOrder(resp.SFOrderNumber);
			Map<String, OrderStatusMap__c> osmMap = getOsmMap();
			if (resp.LineItemList.LineItem != null) {
				Map<String, Item__c> itemMap = getItemMap(resp.LineItemList);
				system.debug('----------------------------------------------itemMap: ' + itemMap);
				Set<String> pNums = getProdNums(resp.LineItemList);
				Map<String, Order_Line_Items__c> prodNumToOliMap = getMapPNumsToOli(ord, pNums);
				
				for(WS_OrderStatusQuery.LineItem li : resp.LineItemList.LineItem){
					String x1 = padItemNumbers(li.OriginalSkuId);
					String x2 = padItemNumbers(li.NewSkuId);
					system.debug('----------------------------------------------Original Padded: ' + x1);
					system.debug('----------------------------------------------New Padded: ' + x2);
					Order_Line_Items__c oli = prodNumToOliMap.get(padItemNumbers(li.OriginalSkuId));
					system.debug('-----------------------------------------------------------------------oli: ' + oli);
					if(oli != null){
						system.debug('--------------------------------------------------------Existing Line Item');
						olisd.add(newOlisd(oli, ord, li, osmMap, dt, itemMap, resp));
					}else{//Logic for free items
						system.debug('--------------------------------------------------------Possible Free Item');
						string prodKey = NBTYUtils.getRecordTypeBrandMappingMap().get(ord.Customer__r.RecordType.DeveloperName).Product_Suffix_c__c + '-' + padItemNumbers(li.OriginalSkuId);
						system.debug('-------------------------------------------------ProdKey: ' + prodKey);
						Item__c item = itemMap.get(prodKey); //must get item by suffix
						if (item != null) {
							olisd.add(newOlisd(null, ord, li, osmMap, dt, itemMap, resp));
						}//else this item doesn't exist.
					}
				}
			} else {//this is probably a bad order or error screen response in header only
				system.debug('---------------------------------------------------------Error File / BO File');
				Order_Line_Item_Status_Detail__c sd = new Order_Line_Item_Status_Detail__c();
				sd.Time_Stamp__c = dt;
				sd.Order__c = ord.Id;
				sd.Order_Status_Code__c = resp.OrderStatus;
				sd.Order_Status_Description__c = resp.OrderStatusDetail;
				OrderStatusMap__c osm4 = osmMap.get(resp.OrderStatus);
				if (osm4 != null) {
					sd.Order_Status__c = osm4.SFDC_Order_Status__c;
				}
				olisd.add(sd);
			}
			
			system.debug('----------------------------------------------------------------------olisd: ' + olisd);
			if(olisd.size() > 0){
				insert olisd;
			}
			Set<Id> olisdIds = new Set<Id>();
			for(Order_Line_Item_Status_Detail__c q : olisd){
				olisdIds.add(q.Id);
			}
			List<Order_Line_Item_Status_Detail__c> ordStatusDetails = [SELECT Id, Order__r.Name, Order_Status__c, Order_Line_Item__r.Name, 
								Current_Sku__c, Current_Quantity__c, Order_Status_Description__c, 
								Order_Line_Item__r.Line_Number__c, Current_Status__c, Name, Current_Item__c, Previous_Item__c, Previous_Sku__c, 
								Disposition_Number__c, Free_Item__c, IsLineSplit__c, Credit_Rejected__c, Tracking_Number__c, Shipper__c, 
								Previous_Quantity__c, Current_Status_Code__c, Order_Status_Code__c, Tracking_Link__c 
								FROM Order_Line_Item_Status_Detail__c WHERE Id IN: olisdIds];
			return ordStatusDetails;
		}catch(Exception e){
			return null;
		}
	}
	
	public static List<Order_Line_Item_Status_Detail__c> getCurrentOlisds(Id orderId){
		return [SELECT Id, Name, Current_Quantity__c, Current_Status_Code__c, Current_Status__c, Credit_Rejected__c, Order_Status_Description__c, 
													Disposition_Number__c, Previous_Quantity__c, Shipper__c, Tracking_Number__c, Order__c, Order_Status_Code__c, 
													Order_Status__c, Order_Line_Item__c, Current_Sku__c, current_item__c, Previous_Sku__c, IsLineSplit__c 
													FROM Order_Line_Item_Status_Detail__c WHERE Order__c = :orderId];
	}
	
	public static String processFault(WS_OrderStatusQuery.OrderStatusFault resp){
		//Parse response and create error log
		String fault = resp.FaultCode + ': ' + resp.FaultMessage;
		return fault;
	}
	
	public static Order_Line_Item_Status_Detail__c newOlisd(Order_Line_Items__c oli, Orders__c ord, WS_OrderStatusQuery.LineItem lineItem, Map<String, OrderStatusMap__c> osmMap, Datetime dt, Map<String, Item__c> itemMap, WS_OrderStatusQuery.OrderStatusSuccess resp){
		system.debug('----------------------------------------------------------------------starting order line item status details');
		Order_Line_Item_Status_Detail__c sd = new Order_Line_Item_Status_Detail__c();
		sd.Time_Stamp__c = dt;
	
		if(lineItem.ShippingDetail.NewQuantity != null && lineItem.ShippingDetail.NewQuantity != ''){
			sd.Current_Quantity__c = Integer.valueOf(lineItem.ShippingDetail.NewQuantity);
		}else {
			sd.Current_Quantity__c = Integer.valueOf(lineItem.ShippingDetail.OriginalQuantity);
		}
		
		OrderStatusMap__c osm2 = osmMap.get(lineItem.NewItemStatus);
		OrderStatusMap__c osm4 = osmMap.get(resp.orderStatus);
		
		if(lineItem.NewItemStatus != null && lineItem.NewItemStatus != ''){
			sd.Current_Status_Code__c = lineItem.NewItemStatus;
			sd.Current_Status__c = osm2 != null? osm2.SFDC_Order_Line_Status__c :null;
		}
		
		if(lineItem.CreditReject == 'Y' || lineItem.CreditReject == 'YES'){
			sd.Credit_Rejected__c = true;
		}else {
			sd.Credit_Rejected__c = false;
		}
		sd.Disposition_Number__c = lineItem.DispositionNumber;
		sd.Previous_Quantity__c = Integer.valueOf(lineItem.ShippingDetail.OriginalQuantity);
		sd.Shipper__c = lineItem.ShippingDetail.Shipper;
		sd.Tracking_Number__c = lineItem.ShippingDetail.TrackingNumber;
		sd.Tracking_Link__c = trackingLinkURL(sd.Shipper__c, sd.Tracking_Number__c);
		sd.Order__c = ord.Id;
		sd.Order_Status_Code__c = resp.orderStatus;
		sd.Order_Status_Description__c = resp.OrderStatusDetail;
		if(osm4 != null){
			sd.Order_Status__c = osm4.SFDC_Order_Status__c;
		}
		
		if(oli != null){
			sd.Order_Line_Item__c = oli.Id;
		}else {
			sd.Free_Item__c = true;
		}
		
		if(lineItem.NewSkuId != null && lineItem.NewSkuId != ''){
			sd.Current_Sku__c = lineItem.NewSkuId;
		}else {
			sd.Current_Sku__c = lineItem.OriginalSkuId;
		}
		string suffix = NBTYUtils.getRecordTypeBrandMappingMap().get(ord.Customer__r.RecordType.DeveloperName).Product_Suffix_c__c;
		system.debug('----------------------------------------------------------------------suffix: ' + suffix);
		string currentProdKey = suffix + '-' + sd.Current_Sku__c;
		system.debug('----------------------------------------------------------------------currentProdKey: ' + currentProdKey);
		sd.current_item__c = itemMap.get(currentProdKey).id;
		system.debug('----------------------------------------------------------------------sd.current_item__c: ' + sd.current_item__c);
		
		if(lineItem.OriginalSkuId != null && lineItem.OriginalSkuId != ''){
			sd.Previous_Sku__c = lineItem.OriginalSkuId;
			string prevProdKey = NBTYUtils.getRecordTypeBrandMappingMap().get(ord.Customer__r.RecordType.DeveloperName).product_suffix_c__c + '-' + sd.Previous_Sku__c;
			sd.Previous_item__c = itemMap.get(prevProdKey).id;
		}
		if(lineItem.ShippingDetail.NewQuantity != null && lineItem.ShippingDetail.NewQuantity != '' && (lineItem.NewSkuId == null || lineItem.NewSkuId == '')){
			sd.IsLineSplit__c = true;
		}
		system.debug('----------------------------------------------------------------------sd: ' + sd);
		return sd;
	}
	
	public static String trackingLinkURL(String shipper, String trackingNum) {
		system.debug('-------------------------------------------------Shipper: ' + shipper);
		system.debug('-------------------------------------------------trackingNum: ' + trackingNum);
		String url = '';
		String baseURL = '';
		if (shipper != null && trackingNum != null) {
			if (shipper.contains('UPS')) {
				url = WS_Integration__c.getValues('UPS_Tracking').value__c + trackingNum;
			} else if (shipper.contains('Parcel Post') || shipper.contains('Fedex')) {
				url = WS_Integration__c.getValues('USPS_Fedex_Tracking').value__c + trackingNum;
			}
		}
		
		return url;
	}
	
	public static List<Order_Line_Item_Status_Detail__c> getCurrentOLISD(){
		return null;
	}
	
	public static Map<String, Order_Line_Items__c> getMapPNumsToOli(Orders__c ord, Set<String> prodNums){
		List<Order_Line_Items__c> oliList = [SELECT Order__r.Customer__r.RecordType.DeveloperName, Id, Product_Number__c, Product_ID__c, Product_Quantity__c, 
											Quantity_Shipped__c, Shipper__c, Shipment_Tracking_Number__c, Shipped_Complete__c, Product_Name__c, Item_Status_Code__c, 
											Update_Quantity__c 
											FROM Order_Line_Items__c WHERE Order__c = :ord.Id AND Shipped_Complete__c != true 
											AND Product_Number__c IN: prodNums];
			
		Map<String, Order_Line_Items__c> prodNumToOliMap = new Map<String, Order_Line_Items__c>();
		for(Order_Line_Items__c oli1 : oliList){
			prodNumToOliMap.put(oli1.Product_Number__c, oli1);
		}
		return prodNumToOliMap;
	}
	
	public static Orders__c queryOrder(String ordNum){
		while (ordNum.startsWith('0')){
			ordNum = ordNum.removeStart('0');
		}
		Orders__c ord = [SELECT Id, Customer__r.RecordType.DeveloperName, Order_Status__c, Sequence_Number__c, Order_Status_Description__c, Order_Status_Code__c  
							FROM Orders__c WHERE Name = :ordNum];
		return ord;
	} 
	
	public static Map<String, OrderStatusMap__c> getOsmMap(){
		List<OrderStatusMap__c> osmList = OrderStatusMap__c.getall().values();
		system.debug('-------------------------------------------------------osmList: ' + osmList);
		Map<String, OrderStatusMap__c> osmMap1 = new Map<String, OrderStatusMap__c>();
		for(OrderStatusMap__c osm : osmList){
			osmMap1.put(osm.Name, osm);
		}
		return osmMap1;
	}
	
	public static Map<String, Item__c> getItemMap(WS_OrderStatusQuery.LineItemList lil){
		Set<String> prodNums = getProdNums(lil);
		system.debug('---------------------------------------------------------------------------------checking item numbers: ' + prodNums);
		
		List<Item__c> itemList = [SELECT Id, Product_Number__c, Product_Suffix__c 
		 							FROM Item__c WHERE Product_Number__c IN: prodNums];
		system.debug('---------------------------------------------------------------------------------itemList: ' + itemList);
		Map<String, Item__c> itemMap1 = new Map<String, Item__c>();
			
		if(itemList != null){
			for(Item__c c : itemList){
				string prodKey = c.product_suffix__c + '-' + c.product_number__c;
				itemMap1.put(prodKey, c);
			}
		}
		return itemMap1;
	}
	
	public static Set<String> getProdNums(WS_OrderStatusQuery.LineItemList lil){
		Set<String> prodNums1 = new Set<String>();
		for(WS_OrderStatusQuery.LineItem a : lil.LineItem){
			prodNums1.add(a.OriginalSkuId);
			prodNums1.add(a.NewSkuId);
		}
		Set<String> pNums = new Set<String>();
			for(String p : prodNums1){
				String itNum = padItemNumbers(p);
				pNums.add(itNum);
			}
		return pNums;
	}
	
	public static String padItemNumbers(String itemNum){
		String x = '';
		if(itemNum.length() == 1){
			x = '00000' + itemNum;
		}else if(itemNum.length() == 2){
			x = '0000' + itemNum;
		}else if(itemNum.length() == 3){
			x = '000' + itemNum;
		}else if(itemNum.length() == 4){
			itemNum = '00' + itemNum;
		}else if(itemNum.length() == 5){
			x = '0' + itemNum;
		}else if(itemNum.length() == 6){
			x = itemNum;
		}
		return x;		
	}
	
	public static String logError(Exception e){
		Error_Log__c err = new Error_Log__c();
		err.Error_Line_Number__c = e.getLineNumber();
		err.Error_Message__c = e.getMessage();
		err.Error_Stack_Trace__c = e.getStackTraceString();
		err.Error_Type__c = e.getTypeName();
		insert err;
		return err.Id;
	}
	
	
	
}