src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Available_Inventory__c</fullName>
        <label>Available Inventory</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Backorder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked if available quantity is less than zero</description>
        <label>Backorder?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <label>Item Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Suffix__c</fullName>
        <description>0011 - PP 0070 VB</description>
        <label>Item Suffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Substitute_Item_Number__c</fullName>
        <label>Substitute Item Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Substitute_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Substitute Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Items Substituted For</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ItemTriggerTest.cls
@isTest
public with sharing class ItemTriggerTest {

	static testMethod void testItem(){
		TestDataSetupUtil.SetupCoreData(2);
		Item__c[] itemList = [select product_suffix__c, product_number__c, id from Item__c];
		system.assertEquals(2, itemlist.size());
		itemList[0].substitute_item_number__c = '009991';
		update itemList;
		system.assertEquals([select id from Item__c where product_number__c =:itemList[0].substitute_item_number__c].id, 
													[select substitute_item__c from Item__c where id =:itemList[0].id].substitute_item__c);
	} 
	
	static testMethod void testBackOrderUpdate(){
		TestDataSetupUtil.SetupCoreData(2);
		Item__c[] itemList = [select available_inventory__c, product_suffix__c, product_number__c, id from Item__c];
		itemList[0].Available_Inventory__c='-999';
		test.startTest();
		update itemList[0];
		test.stopTest();
		Item__c[] itemList2 = [select backorder__c, product_suffix__c, product_number__c, id from Item__c];
		system.assert(itemList2[0].backorder__c);
	}
}