src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>External_Key__c</fullName>
        <externalId>true</externalId>
        <label>External Key</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item_Restriction__c.object
<CustomObject>
    <fields>
        <fullName>External_Key__c</fullName>
        <externalId>true</externalId>
        <label>External Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <label>Item Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Item Restrictions</relationshipLabel>
        <relationshipName>Item_Restrictions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <label>Suffix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Item Restriction</label>
    <nameField>
        <displayFormat>IR-{00000}</displayFormat>
        <label>Item Restriction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Item Restrictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ItemRestrictionHelper.cls
public with sharing class ItemRestrictionHelper {

	public static void setItemOnRestriction(List <Item_Restriction__c> irList){
		Set <String> itemKeys = new Set <String>();
		Map <String, Item__c> itemMap = new Map <String, Item__c>();
		for(Item_Restriction__c ir:irList){
			if (ir.Item__c==null){
				string iKey = ir.suffix__c+ir.item_number__c;
				itemKeys.add(iKey);
			}
		}
		if (!itemKeys.isEmpty()){
			for (Item__c i: [select external_key__c, id from Item__c where external_key__c in:itemKeys]){
				itemMap.put(i.external_key__c, i);
			}
			for(Item_Restriction__c ir:irList){
				string iKey = ir.suffix__c+ir.item_number__c;
				ir.Item__c=itemMap.get(iKey).id;
			}
		}
	}
}