src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Status_Code__c</fullName>
        <description>A/S 400 Status Code</description>
        <label>Item Status Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Status__c</fullName>
        <description>ATG Status equivalent to A/S 400 status code.</description>
        <label>Item Status</label>
        <picklist>
            <picklistValues>
                <fullName>INPROGRESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING MERCHANT ACTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SHIPPED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Item_Suffix__c</fullName>
        <formula>Product_Name__r.Product_Suffix__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Suffix</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>If a line item is split or if a product is substituted this field will record the original quantity before the change.</description>
        <label>Original Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Number__c</fullName>
        <formula>Product_Name__r.Product_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field refers to the quantity of the item being purchased.</description>
        <label>Item Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled_Reason__c</fullName>
        <inlineHelpText>Why is the Order Status set to &quot;Cancelled&quot;?</inlineHelpText>
        <label>Cancelled Reason</label>
        <picklist>
            <controllingField>Order_Status__c</controllingField>
            <picklistValues>
                <fullName>Orphan Order Clean-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back Order Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS400 Error Exception Clean Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possible Credit Card Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Order</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Order_ID__c</fullName>
        <formula>IF(ISBLANK(Webstack_Order_ID__c), Name, Webstack_Order_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Web Order ID</label>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderStatusMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Line_Item_cancel__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Line Item for this status can be cancelled</description>
        <label>Line Item Cancel</label>
        <type>Checkbox</type>
    </fields>
    <label>Order Status Map</label>
</CustomObject>

src/classes/OrderLineItemCancelController.cls
public with sharing class OrderLineItemCancelController {
  
  public Order_Line_Items__c OrderlineItem            {get;set;}
  
  public string OrderId         {get;set;}
  public string orderName {get;set;}
  public boolean showCancelOrderBtn {get;set;}
  public boolean showCancelOrderReason {get;set;}
  public string selectedCancelReason {get;set;}
  public List<SelectOption> cancelReasonList {get;set;}
  public list<Order_Line_Items__c> lstOrderLineItem{get;set;}
  private static string PROGRAM_ID = '2';
  
  
            
 
  public  OrderLineItemCancelController(ApexPages.StandardController stdController)
      {        
         OrderId = stdController.getId();
         list<id> lstOrderLineItemid = new list<id>();
         OrderlineItem = [Select Name,Product_Number__c, Original_Quantity__c, Item_Status_Code__c,Item_Status__c, Order__r.Web_Order_ID__c,Order__r.Order_Status__c, Order__r.Name, Order__c, Item_Suffix__c,Product_Quantity__c From Order_Line_Items__c where Id =:OrderId];
      	 orderName = OrderlineItem.name;
      	 showCancelOrderBtn = false;
      	 showCancelOrderReason = false;
      	 if(renderCancel())
      	 {
      	 	showCancelOrderBtn = true;
      	 	cancelReasonList = new List <SelectOption>();
      	 	cancelReasonList.add(new SelectOption ('None', '--- Select Reason ---'));
    		for (Schema.PicklistEntry p : Schema.SObjectType.Orders__c.fields.getMap().get('Cancelled_Reason__c').getDescribe().getPicklistValues())
			{
				cancelReasonList.add(new SelectOption(p.getLabel(), p.getValue()));
			}
			      	 		
      	 }
      	 
    	
      }

public void showOrderCancelPanel()
{
	showCancelOrderReason = true;
	showCancelOrderBtn = false;
}

  public void processOrderCancelBtn(){
    
    if(selectedCancelReason == 'None')
    {
    	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please select reason for cancellation.'));    	 
    	return;                
    }
    
    try{
    	
    	WS_OrderLineItemCancellation.OrderCancellationResponse_element cancelResponse = new WS_OrderLineItemCancellation.OrderCancellationResponse_element();
    	// pass Salesforce order IDstring SFDCOrderNumber = string.isNotBlank(OrderlineItem.Order__r.Web_Order_ID__c) ? OrderlineItem.Order__r.Web_Order_ID__c : OrderlineItem.Order__r.Name ;
    	string SFDCOrderNumber = orderutilities.zeroLPAD(OrderlineItem.Order__r.Name, 10);
    	
    	cancelResponse = soa_WebservicesClientUtil.CancelOrderbyLineId(PROGRAM_ID,SFDCOrderNumber,OrderlineItem.Product_Number__c, OrderlineItem.Item_Suffix__c,string.valueof(OrderlineItem.Product_Quantity__c),selectedCancelReason);
    	//process response
    	if(cancelResponse.Status != 'Success')
    	{
    	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error Cancelling order: ' + cancelResponse.StatusCode + '-'+ cancelResponse.StatusMessage ));
    	
    	return;	
    	}
    	else
    	{
    	//Update orderlineitem status
    	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO, 'Line Item Cancelled successfully.'));
    	OrderlineItem.Item_Status__c = 'CANCELLED';
    	OrderlineItem.Cancel_Reason__c = selectedCancelReason;
    	showCancelOrderBtn = false;
    /*	WS_OrderStatusQuery.OrderStatusQueryResponse_element response_Element = new WS_OrderStatusQuery.OrderStatusQueryResponse_element();
		response_Element = WS_OrderStatusQueryUtils.doCallout(OrderlineItem.Order__c);
    	
    	//Get order status update for header level
    	
		string orderResponse = '';
		if(response_Element.OrderStatusSuccess != null){
		orderResponse = response_Element.OrderStatusSuccess.OrderStatusDetail;
		}
		else
		{
			orderResponse = 'Unknown';
		}
		OrderlineItem.Order__r.Order_Status__c = orderResponse; */
		update OrderlineItem;
		
		
    	}
    }
    catch(exception e)
    {
    	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Error invoking cancellation web service'));
    	system.debug('--------Error invoking cancellation Web Service' + e.getmessage());
    	
    }
    
        
  }
  
  private boolean renderCancel()
  {
  	// Logic to validate if this line item can be cancelled.
  	boolean toRender = false;
  	string currentStatus = '';
  		try{
  			string CurrentItemStatus = OrderlineItem.Item_Status__c ;
  			if(CurrentItemStatus != 'CANCELLED')
  			{ 
  			currentStatus = OrderlineItem.Item_Status_Code__c;
  			toRender = OrderStatusMap__c.getValues(currentStatus).Line_Item_cancel__c;
  			system.debug('$$$ ' + toRender + ' ' + currentStatus);
  			} 
  			
  		}
  		catch(exception e)
  		{ 
  			// Cannot cancel 
  			system.debug('$$$: Cannot retrieve status code' +  currentStatus);
  		}
  		
  		
  	
  	
  	return toRender;
  }
  
     
      
      
}