src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Replay_Existing_CC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only for use within code to determine if an existing cc token or a new cc will be used for authorization.</description>
        <label>Replay Existing CC</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting for all Web Service Integration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value Associated for the Name</description>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>WS_Integration</label>
</CustomObject>

src/classes/AuthDownTimeTest.cls
/* 
	AuthDownTimeTest
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Your Name   |	??/??/???	|	Created

*/

@isTest
public class AuthDownTimeTest {
	public static WS_soa_AuthorizePaymentService.PaymentInfo testpayinfo;
	
	public static void setupPaymentsResponse(){
		testpayinfo = new WS_soa_AuthorizePaymentService.PaymentInfo();
		testpayinfo.orderId = '123456789';
		testpayinfo.amount = 100.00;
		testpayinfo.creditCardNumber = '341134113411347';
		testpayinfo.creditCardType =WS_soa_AuthorizePaymentService.getCreditCardTypeId('American Express');
		testpayinfo.expiryYYYYMM = '201512';
		testpayinfo.nameOnCard = 'Test Test';
		testpayinfo.addressLine1 = '123 Main Street';
		testpayinfo.addressLine2 = 'Test Block';
		testpayinfo.city = 'Test City';
		testpayinfo.state = 'TS';
		testpayinfo.countryCode = 'USA';
	}
	
	static testMethod void testAuthDownTimeUtils(){
		testDataSetupUtil.SetupCoreData(2);
		setupPaymentsResponse();
		
		PageReference  p = Page.OrderWizard;
		Test.setCurrentPage(p);
		Test.setMock(WebserviceMock.class, new MockControllerCallout());
		test.startTest();
		ApexPages.currentPage().getParameters().put('Id', testDataSetupUtil.order1.id);
		ApexPages.StandardController sc = new ApexPages.StandardController(testDataSetupUtil.order1);
		OrderWizard_NewOrder orderController = new OrderWizard_NewOrder(sc);
		orderController.Checkout();
		orderController.wrap.selectedpaymentType = 'Credit Card';
		orderController.wrap.paymentInfo=testpayinfo;
		orderController.wrap.selectedccType='American Express';
		orderController.wrap.paymentInfo.creditCardNumber='123';
		orderController.wrap.newOrder.Replay_Existing_CC__c = false;
		WS_Integration__c authService = new WS_Integration__c();
		authService.Value__c = 'False';
		authService.Name = 'AuthServiceAvailable';
		insert authService;
		AuthDownTimeUtils.setOrderReAuth(orderController.wrap, '');
		
	}
	
	static testMethod void testAuthDownTimeUtils2(){
		testDataSetupUtil.SetupCoreData(2);
		Orders__c si = AuthDownTimeUtils.queryOrder(testDataSetupUtil.order1.id);
	}
	
	static testMethod void testManualDownTime(){
		testDataSetupUtil.SetupCoreData(2);
		testDataSetupUtil.order1.Order_Status__c = 'Awaiting Authorization';
		update testDataSetupUtil.order1;
		WS_Integration__c wsi = new WS_Integration__c();
		wsi.Name = 'AuthServiceAvailable';
		wsi.Value__c = 'True';
		insert wsi;
		test.startTest();
		ManualDownTimeController mdtc = new ManualDownTimeController();
		mdtc.refresh();
		mdtc.downTimeStart = Datetime.now().addDays(1);
		mdtc.downTimeEnd = Datetime.now().addDays(2);
		mdtc.replayStart = Datetime.now().addDays(3);
		mdtc.changeStatus();
		mdtc.changeStatus();
		mdtc.setDownTime();
		mdtc.scheduleSysDownTime();
		mdtc.doCancel();
		mdtc.setReplay();
		mdtc.scheduleReplay();
		test.stopTest();
	}
	
	static testMethod void testReplayBatch(){
		
	}
	
	
	
	
	
	
	
}