src/objects/Order_Adjustment__c.object
<CustomObject>
    <description>Use an Order Adjustment to process refunds on an order or add an additional miscellaneous charge to a customer order.</description>
    <fields>
        <fullName>Credit_Card_CVV__c</fullName>
        <label>CVV</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Expiration_Date__c</fullName>
        <label>Credit Card Expiration Date</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Name__c</fullName>
        <label>Name on Card</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <description>Encrypted Credit Card Number for re-authorization.</description>
        <label>Credit Card Number</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JCB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Reason__c</fullName>
        <inlineHelpText>Error Reason for error-state orders sent from AS/400</inlineHelpText>
        <label>Error Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PayPal_Reference_ID__c</fullName>
        <inlineHelpText>System reference only</inlineHelpText>
        <label>PayPal Reference ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_or_Misc_Amount__c</fullName>
        <description>Stores Amount that needed to be refund or any Miscellaneous charges.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Related_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Select the Order that this Order Adjustment affects.</description>
        <label>Related Order</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Adjustments</relationshipLabel>
        <relationshipName>Order_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting to Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Paid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Reference_Number__c</fullName>
        <label>Transaction Reference Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Order Adjustment</label>
    <nameField>
        <displayFormat>OA-{000000}</displayFormat>
        <label>Order Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderAdjustmentstBatch.cls
/*
	OrderAdjustmentstBatch
	DESCRIPTION
	Process Order adjustments Batch Creation.
	------------------------------------------------------------------
	Author			|		Date		|	Description
	------------------------------------------------------------------
	Pavan Jasthi	|	2/10/2014		|	Created

*/

global class OrderAdjustmentstBatch implements Database.Batchable<sobject>,Database.AllowsCallouts {
	
	public Set<string> ordAdjustStatuses;
	public String errorReason;
	public String oaQuery;
	
	//constructor
	global OrderAdjustmentstBatch() {
		
	}
	
	global OrderAdjustmentstBatch(Boolean isErrorRun) {
		if (isErrorRun) {
			ordAdjustStatuses = new Set<String>{'Error'};
			errorReason = 'Order is not in AS400';
		} else {
			 ordAdjustStatuses = new Set<String>{'Approved', 'Waiting for Processing'};
		}
		oaQuery = 'SELECT Id, Related_Order__c, Customer__c,Refund_or_Misc_Amount__c, RecordType.DeveloperName, Status__c,Payment_Method__c, ';
		oaQuery += 'PayPal_Reference_ID__c,Transaction_Reference_Number__c,Credit_Card_Number__c,Credit_Card_Expiration_Date__c,Credit_Card_Type__c,Credit_Card_Name__c,Credit_Card_CVV__c ';
		oaQuery += 'FROM Order_Adjustment__c WHERE Status__c IN :ordAdjustStatuses ';
		if (isErrorRun) {
			oaQuery += 'AND Error_Reason__c = :errorReason';
		}
		system.debug('@@@@ batch query'+oaQuery);
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(oaQuery);
	}
	
	global void execute(Database.BatchableContext BC, sobject[] scope) {
		try {
			List<Order_Adjustment__c> ordAdjList = new List<Order_Adjustment__c>();
			ordAdjList = (List<Order_Adjustment__c>) scope;
			for (Order_Adjustment__c oa : ordAdjList) {
				WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp=WS_OrderAdjustmentUtils.doCallout(oa);
			}	
			
		}
		catch(Exception ex){
			System.debug('Error Processing Order Adjustments batch : '+ex.getMessage());
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		system.debug('@@In Finish Method');
		BatchUtilities.batchEmailSuccess(BC, 'OrderAdjustmentstBatch');
	
	}
}