src/objects/Order_Summary__c.object
<CustomObject>
    <label>Order Summary</label>
    <nameField>
        <displayFormat>OS-{000000}</displayFormat>
        <label>Order Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderSummaryTriggerUtilitiesTest.cls
/************************************* MODIFICATION LOG ********************************************************************************
*
* DESCRIPTION : OrderSummaryTriggerUtilitiesTest is a test class for OrderSummaryTriggerUtilities
*
*---------------------------------------------------------------------------------------------------------------------------------------
* DEVELOPER                     DATE                  REASON
*---------------------------------------------------------------------------------------------------------------------------------------
* Shivkant Vadlamani            04/15/2013          - Origininal Version
*
*                                                    
*/

@isTest
global class OrderSummaryTriggerUtilitiesTest 
{
    static testMethod void testGenerateObjects()
    {
    	testDataSetupUtil.SetupCoreData(2);
		OrderSummaryTriggerHelperTest.setupInboundOrderMapping();
		OrderSummaryTriggerHelperTest.setupWebStoresData();
    	Order_Summary__c OSRec = OrderSummaryTriggerHelperTest.setupOrderSummary();
    	
    	OrderSummaryTriggerHelper.processInboundOrderValues();    	
    	
        Account CustomerRec = (Account)OrderSummaryTriggerUtilities.GenerateObjects(OSRec, OrderSummaryTriggerHelper.InboundOrderValuesMap, 'Customer');
        
        System.assertEquals('ANDREA', CustomerRec.FirstName, 'Customer First Name should be ANDREA');
        System.assertEquals('FUST', CustomerRec.LastName, 'Customer First Name should be FUST');
        
        Orders__c OrderRec = (Orders__c)OrderSummaryTriggerUtilities.GenerateObjects(OSRec, OrderSummaryTriggerHelper.InboundOrderValuesMap, 'Order');
        System.assertEquals('0048888888', OrderRec.Sequence_Number__c, 'Order Sequence Number should be 0048888888');        
    }
    
    static testMethod void testMatchCodeDefinition(){
    	testDataSetupUtil.SetupCoreData(2);
    	
    	OrderSummaryTriggerUtilities.matchCodeDefinition(TestDataSetupUtil.acct);
    	OrderSummaryTriggerUtilities.matchCodeDefinition(TestDataSetupUtil.vwAcct);
    }
}