src/objects/Order_Adjustment__c.object
<CustomObject>
    <description>Use an Order Adjustment to process refunds on an order or add an additional miscellaneous charge to a customer order.</description>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Credit Card</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_or_Misc_Amount__c</fullName>
        <description>Stores Amount that needed to be refund or any Miscellaneous charges.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Adjustment</label>
    <nameField>
        <displayFormat>OA-{000000}</displayFormat>
        <label>Order Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MockResponse_OrderAdjustmentService.cls
@isTest
global class MockResponse_OrderAdjustmentService  implements WebServiceMock {
	
	global void doInvoke(Object stub,Object request,Map<String, Object> response,String endpoint,String soapAction,
							String requestName,String responseNS,String responseName,String responseType) {
		
		WS_soa_OrderAdjustmentService.OrderAdjustmentResponse resp;
		Order_Adjustment__c testOA = [select id,name,  Refund_or_Misc_Amount__c,Payment_Method__c, recordType.developerName from Order_Adjustment__c where id =:testDataSetupUtil.oa.id];
		if (testOA.Refund_or_Misc_Amount__c!=0) {
			resp = new WS_soa_OrderAdjustmentService.OrderAdjustmentResponse ();
			resp.OrderAdjustmentSuccess  = new WS_soa_OrderAdjustmentService.OrderAdjustmentSuccess ();
			if (testOA.recordType.developerName == 'Refund' && testOA.Payment_Method__c != 'Credit Card') {
				if (testOA.Payment_Method__c=='Check') { 
					WS_soa_OrderAdjustmentService.CheckSuccess checkSuccess = new WS_soa_OrderAdjustmentService.CheckSuccess();
					checkSuccess.status='Success';
					resp.OrderAdjustmentSuccess.checkSuccess=checkSuccess;
				} else if (testOA.Payment_Method__c == 'Paypal') {
					WS_soa_OrderAdjustmentService.PaypalSuccess ppSuccess = new WS_soa_OrderAdjustmentService.PaypalSuccess();
					ppSuccess.status='Success';
					ppSuccess.refundID='ZZZ987';
					resp.OrderAdjustmentSuccess.PaypalSuccess=ppSuccess;
				}
			} else {
				WS_soa_OrderAdjustmentService.CreditSuccess creditSuccess= new WS_soa_OrderAdjustmentService.CreditSuccess();
				creditSuccess.tokenNumber='@Y8VFTY@WM3-4113';
				creditSuccess.orderID=testOA.name;
				creditSuccess.transactionReferenceNumber='XXX123';
				creditSuccess.transactionReferenceIndex='2';
				creditSuccess.respDateTime='2014-02-20T16:01:57';
				creditSuccess.status='@Y8VFTY@WM3-4113';
				creditSuccess.message='@Y8VFTY@WM3-4113';				
				resp.OrderAdjustmentSuccess.creditSuccess=creditSuccess;
			}
		}
		response.put('response_x', resp);
	}
}