src/objects/Order_Line_Item_Status_Detail__c.object
<CustomObject>
    <description>Child object of Order Line Items, contains status updates from AS400</description>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Order Line Item Status Detail</label>
    <nameField>
        <displayFormat>0{0000000000}</displayFormat>
        <label>Status Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item Status Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Submitted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderStatusQueryBatch.cls
/*
	OrderStatusQueryBatch
	DESCRIPTION
	------------------------------------------------------------------
	Author		|	Date		|	Description
	------------------------------------------------------------------
	Gary Alfrey |	10/14/13	|	Created

*/


global class OrderStatusQueryBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
	
	public Set<String> orderNumbers;
	public date filterDate;
	public Set<String> statuses;
	public String query;
	public datetime minDateTime;
	public datetime maxDateTime;
	public datetime dt;
	public boolean isNight;
	
	global OrderStatusQueryBatch(Boolean isNightly){
		statuses = new Set <String>{'Cancelled','Shipped/Complete'};
		isNight = isNightly;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC){
		system.debug('----------------------------------------------------orderNumbers: ' + orderNumbers);
		if (isNight) {
			if(orderNumbers != null){
				query = 'SELECT Id, Name FROM Orders__c WHERE Name IN :orderNumbers';
			}else{
				query = 'SELECT Id, Name FROM Orders__c WHERE Order_Submitted__c = true AND Order_Status__c NOT IN :statuses';
			}
			if(filterDate != null){
				query += ' AND Order_Date__c > :filterDate ';
			}else if(minDateTime != null && maxDateTime != null){
				query += ' AND Order_Date__c > :minDateTime AND Order_Date__c < :maxDateTime ';
			}
		} else {
			//set to hourly query
			//query details: only query orders that have been submitted in the last hour.
			dt = DateTime.now().addHours(-6);
			statuses = new Set <String>{'Submitted','Bad Order','Error Screen'};
			query = 'SELECT Id, Name FROM Orders__c WHERE Order_Submitted__c = true AND Order_Date__c >= :dt AND Order_Status__c IN :statuses';
		}
		system.debug('-----------------------------------------------QUERY: ' + query);
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope){
		List<Orders__c> orderList = (List<Orders__c>) scope;
		WS_OrderStatusQuery.OrderStatusQueryResponse_element response_Element;
		
		for(Orders__c ord : orderList){
			response_Element = new WS_OrderStatusQuery.OrderStatusQueryResponse_element();
			response_Element = WS_OrderStatusQueryUtils.doCallout(ord.Id);
			if(response_Element.OrderStatusSuccess != null){
				List<Order_Line_Item_Status_Detail__c> ordStatusDetails = WS_OrderStatusQueryUtils.processSuccess(response_Element.OrderStatusSuccess);
				if(ordStatusDetails != null){
					OrderStatusQueryUtils.processItemSubtitution(ordStatusDetails);
				}
			}else if(response_Element.OrderStatusFault != null){
				system.debug('---------------------------------------------------------Failure');
				WS_OrderStatusQuery.OrderStatusSuccess oss = new WS_OrderStatusQuery.OrderStatusSuccess();
				oss.OrderStatus = response_Element.OrderStatusFault.FaultCode;
				oss.OrderStatusDetail = response_Element.OrderStatusFault.FaultMessage;
				oss.SFOrderNumber = ord.Name;
				List<WS_OrderStatusQuery.LineItem> aList = null;
				WS_OrderStatusQuery.LineItemList lineItemList = new WS_OrderStatusQuery.LineItemList();
				lineItemList.LineItem = aList;
				oss.LineItemList = lineItemList;
				List<Order_Line_Item_Status_Detail__c> xp = WS_OrderStatusQueryUtils.processSuccess(oss);
				system.debug('---------------------------------------------------------xp: ' + xp);
				if(xp != null){
					Set<String> olisdIds = new Set<String>();
					for(Order_Line_Item_Status_Detail__c a : xp){
						olisdIds.add(a.Id);
					}
					OrderStatusQueryUtils.processItemSubtitution(xp);
				}
			}
		}
	}

	global void finish(Database.BatchableContext BC){
		
	}
}