src/objects/Order_Line_Items__c.object
<CustomObject>
    <fields>
        <fullName>Final_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Final Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Number</label>
        <referenceTo>Orders__c</referenceTo>
        <relationshipLabel>Order Line Items</relationshipLabel>
        <relationshipName>Order_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderLineItemArchiveTest.cls
@isTest
private class OrderLineItemArchiveTest {

             
                
        static testMethod void testArchiveSummary(){
         	testDataSetupUtil.SetupCoreData(2);
         	//OrderLineItemArchiveUtilities.archiveLineItems(new Set <Id>{testDataSetupUtil.order1.id});
         	
         	testDataSetupUtil.order1.Order_Status__c = 'Shipped/Complete';
         	update testDataSetupUtil.order1;
         	OrderLineItemArchiveUtilities.archiveLineItems(new Set <Id>{testDataSetupUtil.order1.id});
         	system.assertEquals(0, [select count() from Order_Line_Items__c where order__c =:testDataSetupUtil.order1.id ]);
         	PageReference pref = Page.OrderLineItemArchiveSnippet;
        	Test.setCurrentPage(pref);
        	test.startTest();
        	ApexPages.StandardController con = new ApexPages.StandardController(testDataSetupUtil.order1);
            OrderLineItemArchiveSnippet controller = new OrderLineItemArchiveSnippet(con);
        	
        	
        	test.stopTest();
        	system.assert(controller.oliList[0].final_price__c==10.00);
         }
}