src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Authorization_Amount__c</fullName>
        <label>Authorization Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Date__c</fullName>
        <label>Order Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>Customer&apos;s method of payment</description>
        <label>Payment Type</label>
        <picklist>
            <controllingField>Sales_Channel__c</controllingField>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderStatusMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>SFDC_Order_Status__c</fullName>
        <label>SFDC Order Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Order Status Map</label>
</CustomObject>

src/classes/OrderLookup_Wrapper.cls
public with sharing class OrderLookup_Wrapper {
	public List<Wrapper_Line> wrapperLineList {get;set;}
	public OrderLookup_Wrapper() {
		
	}
	public boolean isHisOrder {get;set;}
	
	public orders__c orderRec {
		get {
			if(orderRec == null) orderRec = new orders__c();
				return orderRec;
		}
		set {orderRec = value;} 
	} 
	
	public ws_Soa_OrderHistoryService.orders hisOrder {
		get {
			if(hisOrder == null) {
				hisOrder = new ws_Soa_OrderHistoryService.orders();
				
			}
			return hisOrder;
		}
		set {hisOrder = value;}
	}
	
	public string orderDate {
		get {
			if(isHisOrder) 
				return hisOrder.orderHeader.purchaseDateFormat;
			else
				return string.valueof(orderRec.Order_Date__c.month()) + '-' + string.valueof(orderRec.Order_Date__c.day()) + '-' + string.valueof(orderRec.Order_Date__c.year()).substring(2, 4);	
		}
	}
	
	public decimal orderAmount {
		get {
			if(isHisOrder) 
				return decimal.valueof(hisOrder.orderHeader.totalNetPurchaseAmount);
			else if(!isHisOrder && orderRec.Payment_Type__c == 'Credit Card' )
				return orderRec.Authorization_Amount__c;	
			else
				return orderRec.Order_Total__c;	
		}
		
	}
	//used to Display AS400 number for matching SF Orders
	public string SFOrderNo {get;set;}
	public string WebOrderNo {get;set;}
	
	public class wrapper_line {
		public ws_Soa_OrderHistoryService.lineItem lineItem {get;set;}
		public string sfStatus {get;set;}
		public wrapper_line(ws_Soa_OrderHistoryService.lineItem li, OrderStatusMap__c osm){
			lineItem=li;
			if (osm!=null) sfStatus = osm.SFDC_Order_Status__c;
		}
	}
	
}