src/objects/Order_Line_Items__c.object
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <label>Order Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Orders__c.object
<CustomObject>
    <fields>
        <fullName>Archive_Summary__c</fullName>
        <label>Archive Summary</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Archived__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Archived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Submission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Physical Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>1{0000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderLineItemArchiveSnippet.cls
public with sharing class OrderLineItemArchiveSnippet {
	
	public Orders__c orderSObj {get;set;}
	public List <Order_Line_Items__c> oliList {get;set;}
	public string testString ;


	public OrderLineItemArchiveSnippet(ApexPages.StandardController stdController){
		oliList = new List <Order_Line_Items__c>();
		testString = '1,0011001480,1,1,UPS,4.99#2,0011001480,1,1,UPS,4.99#3,0011001480,1,1,UPS,4.99#4,0011001480,1,1,UPS,4.99';
		system.debug(testString);
      	orderSObj  = (Orders__c) stdController.getRecord();
      	orderSObj =[ select id, Archive_Summary__c, order_Status__c,archived__c from Orders__c where Id =:orderSObj.id];
      	if (orderSObj.Archive_Summary__c!=null){
      		orderSObj.Archived__c=true;
      	 oliList = OrderLineItemArchiveUtilities.restoreOlisFromArchive(orderSObj);
      	}
	 SYSTEM.DEBUG(oliList);
	}

	

	
}