src/objects/WS_Integration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom Setting for all Web Service Integration</description>
    <fields>
        <fullName>Value__c</fullName>
        <description>Value Associated for the Name</description>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>WS_Integration</label>
</CustomObject>

src/classes/NBTYAddressService.cls
public with sharing class NBTYAddressService {

  public NBTYAddressService(){}
  
  public static AddressSvc.Security setupSecurity(){
	AddressSvc.AddressSvcSoap addSvc = new AddressSvc.AddressSvcSoap(WS_Integration__c.getValues('AvaTaxEndPoint').value__C);
	addSvc.Security = new AddressSvc.Security();
	addSvc.Security.UsernameToken.Username = WS_Integration__c.getValues('AvaTaxUserID').value__C;
	addSvc.Security.UsernameToken.Password =  WS_Integration__c.getValues('AvaTaxPassword').value__C;
	return addSvc.Security ;
   } 
}